export const tinyCollapseitemAuroraTheme = {
  'ti-collapse-item-icon-color': '#333333',
  'ti-collapse-item-arrow-hover-text-color': '#1890ff',
  'ti-collapse-item-header-bg-color': '#fff',
  'ti-collapse-item-header-min-height': '46px',
  'ti-collapse-item-content-border-color-top': 'transparent',
  'ti-collapse-item-header-font-weight': 'var(--ti-common-font-weight-7)',
  'ti-collapse-item-border-color-right': 'transparent',
  'ti-collapse-item-border-color-left': 'transparent',
  'ti-collapse-item-border-color-top': 'transparent',
  'ti-collapse-item-disabled-border-color-top': 'transparent',
  'ti-collapse-item-disabled-border-color-left': 'transparent',
  'ti-collapse-item-disabled-border-color-right': 'transparent',
  'ti-collapse-item-header-padding-horizontal': 'var(--ti-common-space-6x)',
  'ti-collapse-item-header-font-size': 'var(--ti-common-font-size-1)',
  'ti-collapse-item-icon-font-size': 'var(--ti-common-font-size-1)',
  'ti-collapse-item-margin-top': 'var(--ti-common-space-0)',
  'ti-collapse-item-content-padding-left': 'var(--ti-common-space-6x)',
  'ti-collapse-item-content-padding-bottom': 'var(--ti-common-space-6x)',
  'ti-collapse-item-content-padding-right': 'var(--ti-common-space-6x)',
  'ti-collapse-item-content-padding-top': 'var(--ti-common-space-0)'
}
