export const tinyCollapseItemOldTheme = {
  'ti-collapse-item-title-right-fill': 'var(--ti-common-color-text-primary, #252b3a)',
  'ti-collapse-item-title-right-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'ti-collapse-item-content-padding-bottom': 'var(--ti-common-space-3x, 12px)',
  'ti-collapse-item-content-padding-right': 'var(--ti-common-space-4x, 16px)',
  'ti-collapse-item-content-padding-left': 'var(--ti-common-space-4x, 16px)',
  'ti-collapse-item-content-padding-top': 'var(--ti-common-space-3x, 12px)',
  'ti-collapse-item-content-border-color-top': 'var(--ti-collapse-item-border-color)',
  'ti-collapse-item-content-border-color': 'var(--ti-common-color-transparent, transparent)',
  'ti-collapse-item-header-border-color-right': 'var(--ti-collapse-item-header-border-color)',
  'ti-collapse-item-header-border-color-left': 'var(--ti-collapse-item-header-border-color)',
  'ti-collapse-item-header-border-color': 'var(--ti-common-color-transparent, transparent)',
  'ti-collapse-item-header-bg-color': 'var(--ti-common-color-bg-white-emphasize, #f2f5fc)',
  'ti-collapse-item-header-padding-horizontal': 'var(--ti-common-space-4x, 16px)',
  'ti-collapse-item-header-padding-vertical': 'var(--ti-common-space-0, 0px)',
  'ti-collapse-item-arrow-hover-text-color': 'var(--ti-common-color-info, #252b3a)',
  'ti-collapse-item-arrow-margin-right': 'var(--ti-common-space-3x, 12px)',
  'ti-collapse-item-wrap-bg-color': 'var(--ti-common-color-light, #fff)',
  'ti-collapse-item-icon-color': 'var(--ti-common-color-icon-normal, #575d6c)',
  'ti-collapse-item-header-min-height': 'var(--ti-common-size-8x, 32px)',
  'ti-collapse-item-margin-top': 'var(--ti-common-space-2x, 8px)',
  'ti-collapse-item-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-collapse-item-border-length': 'var(--ti-common-border-weight-normal, 1px)',
  'ti-collapse-item-border-color': 'var(--ti-common-color-line-dividing, #dfe1e6)'
}
