export const tinyCollapseItemSmbTheme = {
  'ti-collapse-item-border-radius': '0',
  'ti-collapse-item-header-padding-vertical': 'var(--ti-common-size-3x)',
  'ti-collapse-item-header-padding-horizontal': 'var(--ti-common-space-5x)',
  'ti-collapse-item-header-min-height': 'var(--ti-common-size-height-medium)',
  'ti-collapse-item-icon-color': '#808080',
  'ti-collapse-item-border-color': 'transparent',
  'ti-collapse-item-content-border-color': 'var(--ti-common-color-light)',
  'ti-collapse-item-content-border-color-top': 'var(--ti-common-color-light)',
  'ti-collapse-item-border-length': 'var(--ti-common-border-radius-0)',
  'ti-collapse-item-content-padding-top': 'var(--ti-common-space-6x)',
  'ti-collapse-item-content-padding-right': 'var(--ti-common-space-5x)',
  'ti-collapse-item-content-padding-bottom': 'var(--ti-common-space-6x)',
  'ti-collapse-item-content-padding-left': 'var(--ti-common-space-5x)',
  'ti-collapse-item-arrow-hover-text-color': 'var(--ti-base-color-brand)',
  'ti-collapse-item-header-border-color': 'var(--ti-base-color-common-5)',
  'ti-collapse-item-title-right-color': '#1476ff',
  'ti-collapse-item-title-right-fill': '#1476ff',
  'ti-collapse-item-header-bg-color': 'var(--ti-common-color-bg-white-normal)',
  'ti-collapse-item-wrap-bg-color': 'var(--ti-common-bg-minor)',
  'ti-collapse-item-header-border-color-left': 'var(--ti-common-color-light)',
  'ti-collapse-item-header-border-color-right': 'var(--ti-common-color-light)',
  'ti-collapse-item-margin-top': 'calc(var(--ti-common-space-0) - 2px )',
  'ti-collapse-item-arrow-margin-right': 'var(--ti-common-space-3x)'
}
