export default {
  tvp: {
    tvpSearchbox: {
      defaultPlaceholder: '请选择属性筛选，或输入关键字',
      addPlaceholder: '添加筛选条件',
      tagPlaceholder: '请选择标签键/值搜索，或输入“键=值”搜索',
      dynamicPlaceholder: '请选择{newValue}搜索',
      attributeType: '属性类型',
      propertyValue: '{0}的值',
      matched: '潜在匹配项',
      allValues: '所有值',
      allProperty: '全部属性',
      operator: '运算符',
      clearAll: '清空',
      emptyValue: '空 值',
      help: '点击查看帮助',
      switchText: '切换到默认搜索项',
      tagKey: '键',
      tagValue: '值',
      minValueText: '最小值',
      maxValueText: '最大值',
      rangeMinErr: '输入值必须在{0}~{1}之间',
      rangeMaxErr: '最大值必须大于等于最小值，或者为空',
      rangeNumberTitle: '请至少输入一个值',
      rangeDateTitle: '请至少输入一个日期',
      timeLengthTitle: '可选时间跨度为{value}天内',
      rangeBeginLabel: '开始日期',
      rangeEndLabel: '结束日期',
      rulekeyword1: '关键字',
      notBeNull: '值不能为空',
      noData: '暂无匹配数据...',
      selectAll: '全选',
      confirm: '确定',
      cancel: '取消',
      equal: '等于',
      notEqual: '不等于',
      contain: '包含',
      notContain: '不包含',
      initUse: '搜索'
    }
  }
}
