export const tinyInputOldTheme = {
  'ti-input-placeholder-color': 'var(--ti-common-color-placeholder, #adb0b8)',
  'ti-input-suffix-icon-height': '1em',
  'ti-input-suffix-icon-width': '1em',
  'ti-input-count-textlength-color': 'var(--ti-common-color-text-weaken, #8a8e99)',
  'ti-input-suffix-right': 'var(--ti-common-space-3x, 8px)',
  'ti-input-prefix-padding-left': 'calc(var(--ti-common-space-8x, 32px) - 2px)',
  'ti-input-prefix-padding-right': 'calc(var(--ti-common-space-8x, 32px) - 4px)',
  'ti-input-suffix-padding-left': 'var(--ti-common-space-2x, 8px)',
  'ti-input-suffix-padding-right': 'calc(var(--ti-common-space-8x, 32px) - 2px)',
  'ti-input-padding-horizontal': 'var(--ti-common-space-2x, 8px)',
  'ti-input-icon-close-text-color': 'var(--ti-common-color-icon-normal, #5e7ce0)',
  'ti-input-icon-font-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-input-exceed-text-color': 'var(--ti-common-bg-primary, #c7000b)',
  'ti-input-small-height': 'var(--ti-common-size-height-small, 32px)',
  'ti-input-disabled-text-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-input-suffix-icon-color': 'var(--ti-common-color-icon-normal)',
  'ti-input-suffix-top-mini': '50%',
  'ti-input-suffix-top-small': '50%',
  'ti-input-suffix-top-medium': '50%',
  'ti-input-suffix-top': '50%',
  'ti-input-focus-icon-color': 'var(--ti-common-color-border-hover, #575d6c)',
  'ti-input-icon-color': 'var(--ti-common-color-border-hover, #575d6c)',
  'ti-input-hover-border-color': 'var(--ti-common-color-border-hover, #575d6c)',
  'ti-input-border-color': 'var(--ti-common-color-border, #adb0b8)',
  'ti-input-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-input-count-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-input-font-size': 'var(--ti-common-font-size-base, 12px)'
}
