export const tinyInputSmbTheme = {
  'ti-input-border-color': 'var(--ti-common-color-line-normal)',
  'ti-input-hover-border-color': 'var(--ti-common-color-line-hover)',
  'ti-input-border-radius': 'var(--ti-common-border-radius-3)',
  'ti-input-padding-horizontal': 'var(--ti-common-space-3x)',
  'ti-input-icon-color': 'var(--ti-base-color-common-2)',
  'ti-input-focus-icon-color': 'var(--ti-common-color-icon-normal)',
  'ti-input-count-font-size': 'var(--ti-common-font-size-0)',
  'ti-input-suffix-right': 'var(--ti-common-font-size-0)',
  'ti-input-suffix-icon-color': 'var(--ti-base-color-common-2)',
  'ti-input-count-textlength-color': 'var(--ti-common-color-text-primary)',
  'ti-input-suffix-padding-left': 'var(--ti-common-space-3x)',
  'ti-input-disabled-text-color': 'var(--ti-common-color-text-disabled)',
  'ti-input-disabled-bg-color': 'rgba(0,0,0,0.05)',
  'ti-input-suffix-icon-width': 'var(--ti-common-font-size-2)',
  'ti-input-suffix-icon-height': 'var(--ti-common-font-size-2)',
  'ti-input-icon-close-text-color': 'var(--ti-base-color-common-2)',
  'ti-input-icon-font-size': 'var(--ti-common-font-size-2)',
  'ti-input-font-size': 'var(--ti-common-font-size-1)',
  'ti-input-placeholder-color': 'var(--ti-base-color-common-2)',
  'ti-input-exceed-text-color': '#c7000b',
  'ti-input-suffix-top': 'var(--ti-common-space-4x)',
  'ti-input-suffix-top-medium': 'var(--ti-common-space-5x)',
  'ti-input-suffix-top-small': 'var(--ti-common-space-4x)',
  'ti-input-suffix-top-mini': 'var(--ti-common-space-3x)'
}
