export const tinyCheckboxButtonOldTheme = {
  'ti-checkbox-button-left-border-radius': '0',
  'ti-checkbox-button-right-border-radius': '0',
  'ti-checkbox-button-mini-last-right-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-checkbox-button-mini-last-left-border-radius': '0',
  'ti-checkbox-button-mini-right-border-radius': '0',
  'ti-checkbox-button-mini-left-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-checkbox-button-mini-padding-horizontal': '12px',
  'ti-checkbox-button-margin-top': '8px',
  'ti-checkbox-button-checked-display': 'none',
  'ti-checkbox-button-small-font-size': 'var(--ti-common-font-size-base)',
  'ti-checkbox-button-size-medium-height': '44px',
  'ti-checkbox-button-size-small-height': '30px',
  'ti-checkbox-button-size-small-padding-horizontal': '15px',
  'ti-checkbox-button-size-mini-border-radius': '0',
  'ti-checkbox-button-size-mini-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-checkbox-button-mini-margin-horizontal': '2px',
  'ti-checkbox-button-margin-horizontal': '2px',
  'ti-checkbox-button-height': '24px',
  'ti-checkbox-button-padding-vertical': '5px',
  'ti-checkbox-button-border-radius': '0',
  'ti-checkbox-button-border-color-hover': '#c2c2c2',
  'ti-checkbox-button-border-color': '#e9edfa',
  'ti-checkbox-button-bg-color-hover': 'var(--ti-common-color-bg-hover, #344899)',
  'ti-checkbox-button-disabled-bg-color': 'var(--ti-common-color-bg-disabled, #f5f5f6)',
  'ti-checkbox-button-checked-border-color': 'var(--ti-common-color-line-active, #5e7ce0)',
  'ti-checkbox-button-hover-text-color': 'var(--ti-common-color-text-white, #fff)',
  'ti-checkbox-shadow-color': '#dfe1e6',
  'ti-checkbox-button-bg-color': 'var(--ti-common-color-bg-light-normal, #e9edfa)'
}
