export const tinyButtonGroupOldTheme = {
  'ti-button-group-mini-line-height': '22px',
  'ti-button-group-mini-size': '24px',
  'ti-button-group-small-line-height': '30px',
  'ti-button-group-small-size': '32px',
  'ti-button-group-medium-line-height': '40px',
  'ti-button-group-medium-size': '42px',
  'ti-button-group-sup-icon-line-height': '18px',
  'ti-button-group-item-sup-position-top': 'calc(-1 * var(--ti-button-group-item-sup-height) / 2)',
  'ti-button-group-item-sup-height': 'var(--ti-common-size-4x, 16px)',
  'ti-button-group-mini-padding-horizontal': 'var(--ti-common-space-3x, 12px)',
  'ti-button-group-btn-padding-horizontal': 'calc(var(--ti-common-space-10, 10px) * 3)',
  'ti-button-group-item-li-margin-bottom': 'var(--ti-common-space-base, 4px)',
  'ti-button-group-item-active-disabled-bg-color': 'var(--ti-common-color-bg-dark-disabled, #dfe1e6)',
  'ti-button-group-item-btn-active-hover-bg-color': 'var(--ti-common-color-bg-light-emphasize, #beccfa)',
  'ti-button-group-item-active-bg-color': 'var(--ti-common-color-bg-emphasize, #5e7ce0)',
  'ti-button-group-item-btn-hover-bg-color': 'var(--ti-common-color-bg-light-emphasize, #beccfa)',
  'ti-button-group-item-active-disabled-text-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-group-item-btn-disabled-bg-color': 'var(--ti-common-color-bg-disabled, #f5f5f6)',
  'ti-button-group-item-btn-width': 'var(--ti-common-size-width-normal, 80px)',
  'ti-button-group-item-btn-text-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'ti-button-group-item-bg-color': 'var(--ti-common-color-bg-light-normal, #e9edfa)',
  'ti-button-group-left-border-radius': 'var(--ti-common-border-radius-0, 0px)',
  'ti-button-group-middle-border-radius': 'var(--ti-common-border-radius-0, 0px)',
  'ti-button-group-right-border-radius': 'var(--ti-common-border-radius-0, 0px)',
  'ti-button-group-mini-side-border-radius': 'var(--ti-common-border-radius-normal, 2px)'
}
