export const tinyButtonGroupTheme = {
  'ti-button-group-item-li-margin-bottom': 'var(--ti-common-space-2)',
  'ti-button-group-right-border-radius': 'var(--ti-common-border-radius-normal)',
  'ti-button-group-middle-border-radius': 'var(--ti-common-border-radius-normal)',
  'ti-button-group-left-border-radius': 'var(--ti-common-border-radius-normal)',
  'ti-button-group-item-btn-text-color': 'var(--ti-common-color-text-secondary)',
  'ti-button-group-item-active-bg-color': 'var(--ti-common-color-prompt)',
  'ti-button-group-item-btn-hover-bg-color': '#DEECFF',
  'ti-button-group-item-btn-disabled-bg-color': '#F0F0F0',
  'ti-button-group-item-active-disabled-bg-color': 'var(--ti-common-color-bg-dark-disabled)',
  'ti-button-group-btn-padding-horizontal': 'var(--ti-common-space-6x)',
  'ti-button-group-mini-padding-horizontal': 'var(--ti-common-space-4x)',
  'ti-button-group-item-bg-color': 'var(--ti-common-color-bg-normal)',
  'ti-button-group-item-btn-active-hover-bg-color': 'var(--ti-common-color-prompt)',
  'ti-button-group-item-btn-width': 'var(--ti-common-size-auto)',
  'ti-button-group-item-active-disabled-text-color': 'var(--ti-common-color-text-weaken)',
  'ti-button-group-item-sup-position-top': 'var(--ti-common-space-0)',
  'ti-button-group-item-sup-height': 'var(--ti-common-line-height-base)',
  'ti-button-group-mini-side-border-radius': 'var(--ti-button-group-mini-border-radius)',
  'ti-button-group-sup-icon-line-height': '22px',
  'ti-button-group-medium-size': '32px',
  'ti-button-group-medium-line-height': '30px',
  'ti-button-group-small-size': '28px',
  'ti-button-group-small-line-height': '26px',
  'ti-button-group-mini-size': '24px',
  'ti-button-group-mini-line-height': '22px'
}
