export const tinyButtonGroupTheme = {
    'ti-button-group-item-li-margin-right': '8px',
    'ti-button-group-item-active-bg-color': 'transparent',
    'ti-button-group-item-active-text-color': '#191919',
    'ti-button-group-item-active-border-color': '#191919',
    'ti-button-group-right-border-radius': 'var(--ti-common-border-radius-normal)',
    'ti-button-group-middle-border-radius': 'var(--ti-common-border-radius-normal)',
    'ti-button-group-left-border-radius': 'var(--ti-common-border-radius-normal)',
    'ti-button-group-item-btn-text-color': '#595959',
    'ti-button-group-item-active-bg-color': '#FFFFFF',
    'ti-button-group-item-btn-hover-bg-color': 'transparent',
    'ti-button-group-item-btn-hover-text-color': '#191919',
    'ti-button-group-item-active-font-size': '12px',
    'ti-button-group-item-active-text-color': '#191919',
    'ti-button-group-item-margin-top': '8px',
    'ti-button-group-mini-margin-right': '4px',
    'ti-button-group-mini-font-size': '12px',
    'ti-button-group-item-btn-disabled-bg-color': 'rgba(0,0,0,0.05)',
    'ti-button-group-item-btn-hover-border-color': '#c2c2c2',
    'ti-button-group-active-hover-border-color': '#191919',
    'ti-button-group-btn-padding-horizontal': '24px',
    'ti-button-group-mini-padding-horizontal': '16px',
    'ti-button-group-item-btn-disabled-border-color': '#dbdbdb',
    'ti-button-group-mini-border-radius': '4px',
    'ti-button-group-no-border-hover-border-color': 'transparent',
    'ti-button-group-no-border-hover-bg-color': ' rgba(0,0,0,0.05)',
    'ti-button-group-no-border-active-hover-bg-color': '#FFFFFF',
    'ti-button-group-no-border-border-color': '#191919',
}