export const classes = {
  'search-default': 'relative inline-block text-xs w-full px-3 sm:px-0',
  'pc-search-line':
    'w-full border border-solid rounded bg-color-bg-1 transition duration-300 ease-in-out border-separate hidden sm:inline-table',
  'pc-search-line-focus': 'border-color-border-focus',
  'pc-search-line-unfocus': 'border-color-border hover:border-color-border-hover',
  'pc-search-line-big': 'h-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-line-medium': 'h-[calc(theme(spacing.8)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-line-mini': 'h-[calc(theme(spacing.6)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-line-unbig': 'h-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-present': 'table-cell relative align-middle right-0 text-color-text-primary w-px whitespace-nowrap',
  'pc-search-present-big': 'pl-4 text-sm leading-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))',
  'pc-search-present-medium': 'pl-4 text-sm leading-[calc(theme(spacing.8)-2*theme(borderWidth.DEFAULT))',
  'pc-search-present-mini': 'pl-4 text-sm leading-[calc(theme(spacing.6)-2*theme(borderWidth.DEFAULT))',
  'pc-search-present-unbig': 'pl-3 text-xs leading-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-present-pointer': 'cursor-pointer',
  'pc-search-present-icon-outer':
    'h-4 leading-4 inline-block pl-2 pr-3 py-0 border-r border-solid border-color-border-separator cursor-pointer',
  'pc-search-present-icon-chevron-down': 'text-base fill-color-icon-primary hover:fill-color-icon-hover',
  'pc-search-input-background-transparent': ' border-transparent',
  'pc-search-input-background-transparent-collapse': 'bg-color-bg-1',
  'pc-search-input-default':
    'pl-2 table-cell relative align-middle right-0 text-color-text-primary border-0 outline-0 bg-transparent placeholder:text-color-none focus:placeholder:text-color-text-placeholder',
  'pc-search-input-collapse': 'w-7 float-right p-0',
  'pc-search-input-uncollapse': 'w-full',
  'pc-search-input-collapse-big': 'pl-3',
  'pc-search-input-collapse-medium': 'pl-3',
  'pc-search-input-collapse-mini': 'pl-1',
  'pc-search-input-collapse-unbig': 'pl-2',
  'pc-search-input-big':
    'pl-3 text-sm h-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))] leading-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-medium':
    'pl-3 text-sm h-[calc(theme(spacing.8)-2*theme(borderWidth.DEFAULT))] leading-[calc(theme(spacing.8)-2*theme(borderWidth.DEFAULT))] placeholder:text-sm',
  'pc-search-input-mini':
    'pl-3 text-xs h-[calc(theme(spacing.6)-2*theme(borderWidth.DEFAULT))] leading-[calc(theme(spacing.6)-2*theme(borderWidth.DEFAULT))] placeholder:text-xs',
  'pc-search-input-unbig':
    'text-xs h-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))] leading-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-btn-transtion': 'table-cell relative align-middle right-0 w-8 text-center z-10',
  'pc-search-input-btn-transtion-big': 'h-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))] translate-x-4',
  'pc-search-input-btn-transtion-medium': 'h-[calc(theme(spacing.8)-2*theme(borderWidth.DEFAULT))] translate-x-4',
  'pc-search-input-btn-transtion-mini': 'h-[calc(theme(spacing.6)-2*theme(borderWidth.DEFAULT))] translate-x-4',
  'pc-search-input-btn-transtion-unbig': 'h-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))] translate-x-3.5',

  'pc-search-input-btn-transtion-a': 'no-underline block w-8',
  'pc-search-input-btn-transtion-a-big': 'leading-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-btn-transtion-a-medium': 'leading-[calc(theme(spacing.8)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-btn-transtion-a-mini': 'leading-[calc(theme(spacing.6)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-btn-transtion-a-unbig': 'leading-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-btn-transtion-svg-size': 'text-base fill-color-icon-primary hover:fill-color-icon-hover',
  'pc-search-input-btn': 'table-cell relative align-middle right-0 text-center',
  'pc-search-input-btn-big': 'h-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))] w-11',
  'pc-search-input-btn-medium': 'h-[calc(theme(spacing.8)-2*theme(borderWidth.DEFAULT))] w-11',
  'pc-search-input-btn-mini': 'h-[calc(theme(spacing.6)-2*theme(borderWidth.DEFAULT))] w-11',
  'pc-search-input-btn-unbig': 'h-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))] w-10',
  'pc-search-input-btn-a': 'no-underline block',
  'pc-search-input-btn-a-big': 'w-11 leading-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-btn-a-medium': 'w-11 leading-[calc(theme(spacing.8)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-btn-a-mini': 'w-11 leading-[calc(theme(spacing.6)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-btn-a-unbig': 'w-10 leading-[calc(theme(spacing.7)-2*theme(borderWidth.DEFAULT))]',
  'pc-search-input-btn-icon-search-transparent': 'fill-color-bg-1',
  'pc-search-input-btn-icon-search': 'text-base fill-color-none',
  'search-selector':
    'absolute top-full left-0 overflow-hidden min-w-[theme(spacing.18)] border border-solid border-color-border rounded text-xs shadow bg-color-bg-1 text-color-text-primary mt-0.5 py-1 hidden sm:block',
  'search-selector-body': 'max-h-[theme(spacing.72)] overflow-x-hidden overflow-y-auto',
  'search-selector-poplist-item':
    'px-3 min-h-[theme(spacing.6)] leading-6 max-w-full overflow-hidden text-left text-ellipsis whitespace-nowrap cursor-pointer hover:bg-color-bg-2',
  'search-selector-poplist-item-big': 'text-sm',
  'search-selector-poplist-item-medium': 'text-sm',
  'search-selector-poplist-item-mini': 'text-xs',
  'search-selector-poplist-item-unbig': 'text-xs',
  'mobile-search': 'flex sm:hidden w-full items-center shrink-0',
  'mobile-search-input':
    'bg-color-bg-4 pl-9    placeholder:text-color-none focus:placeholder:text-color-text-placeholder rounded-full',
  'mobile-search-input-bg-change': 'bg-color-bg-1',
  'mobile-search-svg-size': 'text-base fill-color-none translate-x-1.5',
  'mobile-search-svg-size-color': 'fill-color-bg-1',
  'mobile-search-button': 'w-16 text-center cursor-pointer',
  'mobile-search-button-notShowButton': 'hidden',
  'mobile-search-input-big': 'leading-8 h-8'
}
