export const tinyGridAuroraTheme = {
  'ti-grid-header-background-color': '#f1f1f1',
  'ti-grid-medium-column-height': '46px',
  'ti-grid-default-column-height': '36px',
  'ti-grid-small-column-height': '30px',
  'ti-grid-mini-column-height': '26px',
  'ti-grid-medium-header-column-height': '46px',
  'ti-grid-default-header-column-height': '36px',
  'ti-grid-small-header-column-height': '30px',
  'ti-grid-mini-header-column-height': '26px',
  'ti-grid-header-repair-border-color': 'var(--ti-common-color-line-dividing)',
  'ti-grid-header-resizable-line-height': '60%',
  'ti-grid-header-resizable-bg-color': '#d8d8d8',
  'ti-grid-body-td-border-color': 'var(--ti-common-color-transparent)',
  'ti-grid-column-icon-text-color': '#c0c4cc',
  'ti-grid-header-icon-font-size': 'var(--ti-common-font-size-1)',
  'ti-grid-column-icon-scale-size': '0.8',
  'ti-grid-tree-icon-color': '#939599',
  'ti-grid-sort-icon-position': 'absolute',
  'ti-grid-sort-icon-right': '6px'
}
