export const tinyGridOldTheme = {
  'ti-grid-filter-checkbox-color': 'var(--ti-grid-primary-color)',
  'ti-grid-filter-checkbox-font-size': 'var(--ti-common-font-size-2)',
  'ti-grid-header-cell-text-width': '100%',
  'ti-grid-tree-expand-icon-translate-x': '-4px',
  'ti-grid-tree-expand-icon-padding-right': '0',
  'ti-grid-tree-expand-icon-font-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-grid-expand-background-color': "''",
  'ti-grid-toolbar-icon-btn-border-radius': 'calc(var(--ti-common-size-base, 4px) - 1px)',
  'ti-grid-toolbar-icon-btn-border-color': 'var(--ti-common-color-line-dividing, #dfe1e6)',
  'ti-grid-toolbar-icon-btn-width': 'calc(var(--ti-common-size-7x, 28px) + 2px)',
  'ti-grid-toolbar-icon-btn-height': 'calc(var(--ti-common-size-7x, 28px) + 2px)',
  'ti-grid-toolbar-btn-hover-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-grid-toolbar-btn-min-width': 'none',
  'ti-grid-toolbar-btn-border-radius': 'calc(var(--ti-common-size-base, 4px) - 2px)',
  'ti-grid-toolbar-btn-border-color': 'var(--ti-common-color-line-dividing, #dfe1e6)',
  'ti-grid-toolbar-btn-line-height': 'var(--ti-common-space-7x, 28px)',
  'ti-grid-toolbar-btn-padding-horizontal': 'var(--ti-common-space-3x, 12px)',
  'ti-grid-nodata-td-bg-img-url': "url('data:image/png",
  'ti-grid-mini-td-padding-horizontal': 'var(--ti-common-space-2x, 8px)',
  'ti-grid-mini-td-padding-vertical': 'var(--ti-common-space-2x, 8px)',
  'ti-grid-td-padding-horizontal': 'var(--ti-common-space-2x, 8px)',
  'ti-grid-td-padding-vertical': 'var(--ti-common-space-2x, 8px)',
  'ti-grid-mini-column-height': 'var(--ti-common-size-7x, 28px)',
  'ti-grid-small-column-height': 'var(--ti-common-size-9x, 36px)',
  'ti-grid-default-column-height': 'calc(var(--ti-common-space-10x, 40px) + 2px)',
  'ti-grid-medium-column-height': 'var(--ti-common-size-13x, 52px)',
  'ti-grid-mini-header-column-height': 'var(--ti-common-size-height-normal, 28px)',
  'ti-grid-small-header-column-height': 'var(--ti-common-size-height-normal, 28px)',
  'ti-grid-default-header-column-height': 'var(--ti-common-size-height-normal, 28px)',
  'ti-grid-medium-header-column-height': 'var(--ti-common-size-height-normal, 28px)',
  'ti-grid-loading-background-color': 'rgba(0, 0, 0, 0.2)',
  'ti-grid-row-hover-background-color': 'var(--ti-common-color-hover-background, #f2f5fc)',
  'ti-grid-row-selected-background-color': 'var(--ti-common-color-bg-white-normal, #fff)',
  'ti-grid-header-resizable-line-height': '100%',
  'ti-grid-header-resizable-bg-color': 'var(--ti-common-color-text-white, #fff)',
  'ti-grid-header-background-color': 'var(--ti-common-color-bg-white-emphasize, #f2f5fc)',
  'ti-grid-checkbox-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-grid-checkbox-icon-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-grid-checkbox-bg-color-checked': 'var(--ti-grid-primary-color)',
  'ti-grid-select-icon-font-size': 'var(--ti-common-font-size-2, 16px)',
  'ti-grid-checkbox-border-color': 'var(--ti-common-color-line-normal, #adb0b8)',
  'ti-grid-radio-bg-color-checked': 'var(--ti-grid-primary-color)',
  'ti-grid-header-repair-border-color': 'var(--ti-common-color-transparent, transparent)',
  'ti-grid-icon-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-grid-header-font-weight': 'var(--ti-common-font-weight-4, normal)',
  'ti-grid-header-text-color': 'var(--ti-common-color-info-normal, #252b3a)'
}
