export const tinyGridOldTheme = {
  'ti-grid-header-cell-text-width': '100%',
  'ti-grid-tree-expand-icon-font-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-grid-expand-background-color': "''",
  'ti-grid-toolbar-icon-btn-border-radius': 'calc(var(--ti-common-size-base, 4px) - 1px)',
  'ti-grid-toolbar-icon-btn-border-color': 'var(--ti-common-color-line-dividing, #dfe1e6)',
  'ti-grid-toolbar-icon-btn-width': 'calc(var(--ti-common-size-7x, 28px) + 2px)',
  'ti-grid-toolbar-icon-btn-height': 'calc(var(--ti-common-size-7x, 28px) + 2px)',
  'tv-Grid-cell-padding-x': 'var(--ti-common-space-2x, 8px)',
  'tv-Grid-cell-padding-y': 'var(--ti-common-space-2x, 8px)',
  'ti-grid-header-resizable-line-height': '100%',
  'ti-grid-header-resizable-bg-color': 'var(--ti-common-color-text-white, #fff)',
  'ti-grid-header-background-color': 'var(--ti-common-color-bg-white-emphasize, #f2f5fc)',
  'ti-grid-checkbox-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-grid-checkbox-icon-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-grid-checkbox-bg-color-checked': 'var(--ti-grid-primary-color)',
  'ti-grid-select-icon-font-size': 'var(--ti-common-font-size-2, 16px)',
  'ti-grid-checkbox-border-color': 'var(--ti-common-color-line-normal, #adb0b8)',
  'ti-grid-radio-bg-color-checked': 'var(--ti-grid-primary-color)',
  'ti-grid-header-repair-border-color': 'var(--ti-common-color-transparent, transparent)',
  'ti-grid-icon-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-grid-header-font-weight': 'var(--ti-common-font-weight-4, normal)'
}
