export const tinyGridSmbTheme = {
  'ti-grid-header-background-color': '#F5F5F5',
  'ti-grid-header-font-weight': 'bold',
  'ti-grid-medium-header-column-height': '46px',
  'ti-grid-default-header-column-height': 'var(--ti-common-size-height-medium)',
  'ti-grid-small-header-column-height': 'var(--ti-common-size-height-normal)',
  'ti-grid-mini-header-column-height': '26px',
  'ti-grid-medium-column-height': '52px',
  'ti-grid-default-column-height': 'var(--ti-common-size-height-large)',
  'ti-grid-small-column-height': 'var(--ti-common-size-height-medium)',
  'ti-grid-mini-column-height': 'var(--ti-common-size-height-minor)',
  'ti-grid-header-resizable-bg-color': 'rgba(0,0,0,0.15)',
  'ti-grid-header-resizable-line-height': '16px',
  'ti-grid-checkbox-border-color': 'var(--ti-common-color-line-normal)',
  'ti-grid-checkbox-border-radius': 'var(--ti-common-border-radius-2)',
  'ti-grid-header-repair-border-color': 'var(--ti-common-color-transparent)',
  'ti-grid-td-padding-horizontal': 'var(--ti-common-space-3x)',
  'ti-grid-header-text-color': 'var(--ti-common-color-text-secondary)',
  'ti-grid-row-hover-background-color': '#F5F5F5',
  'ti-grid-icon-color': 'var(--ti-common-color-icon)',
  'ti-grid-checkbox-icon-size': 'var(--ti-common-font-size-2)',
  'ti-grid-checkbox-bg-color-checked': '#1476FF',
  'ti-grid-radio-bg-color-checked': '#1476FF',
  'ti-grid-toolbar-icon-btn-height': 'var(--ti-common-size-8x)',
  'ti-grid-toolbar-icon-btn-width': 'var(--ti-common-size-8x)',
  'ti-grid-toolbar-icon-btn-border-color': 'var(--ti-common-color-line-normal)',
  'ti-grid-toolbar-icon-btn-border-radius': 'calc(var(--ti-common-size-base) + 2px)',
  'ti-grid-toolbar-btn-min-width': 'calc(var(--ti-common-size-base) * 24)',
  'ti-grid-toolbar-btn-padding-horizontal': 'var(--ti-common-space-6x)',
  'ti-grid-toolbar-btn-line-height': '30px',
  'ti-grid-toolbar-btn-border-color': '#595959', // 缺少#595959的边框公共变量
  'ti-grid-toolbar-btn-hover-border-color': 'var(--ti-common-color-line-normal)', // 缺少#595959的边框公共变量
  'ti-grid-toolbar-btn-border-radius': 'var(--ti-common-size-4x)',
  'ti-grid-select-icon-font-size': 'var(--ti-common-font-size-3)',
  'ti-grid-row-selected-background-color': '#f0f7ff',
  'ti-grid-expand-background-color': '#fafafa',
  'ti-grid-loading-background-color': 'rgba(255, 255, 255, 0.67)',
  'ti-grid-tree-expand-icon-font-size': 'var(--ti-common-font-size-2)',
  'ti-grid-tree-expand-icon-translate-x': '-2px'
}
