export const tinyGridSmbTheme = {
  'ti-grid-header-background-color': 'var(--ti-common-color-bg-white-emphasize)',
  'ti-grid-medium-header-column-height': '46px',
  'ti-grid-default-header-column-height': '40px',
  'ti-grid-small-header-column-height': '32px',
  'ti-grid-mini-header-column-height': '26px',
  'ti-grid-medium-column-height': '52px',
  'ti-grid-default-column-height': 'var(--ti-common-size-height-large)',
  'ti-grid-small-column-height': 'var(--ti-common-size-height-large)',
  'ti-grid-mini-column-height': '30px',
  'ti-grid-header-resizable-bg-color': 'rgba(0,0,0,0.15)',
  'ti-grid-header-resizable-line-height': '16px',
  'ti-grid-checkbox-border-color': 'var(--ti-common-color-line-normal)',
  'ti-grid-checkbox-border-radius': 'var(--ti-common-border-radius-2)',
  'ti-grid-header-repair-border-color': 'var(--ti-common-color-transparent)',
  'ti-grid-td-padding-horizontal': '11px',
  'ti-grid-header-text-color': 'var(--ti-common-color-text-secondary)',
  'ti-grid-row-hover-background-color': 'var(--ti-common-color-bg-white-emphasize)',
  'ti-grid-icon-color': 'var(--ti-common-color-icon)'
}
