export const tinyCarouselOldTheme = {
  'ti-carousel-arrow-hover-text-color': '#808080',
  'ti-carousel-hover-opacity': '0.6',
  'ti-carousel-opacity': '1',
  'ti-carousel-outside-button-active-bg-color': 'var(--ti-common-color-bg-dark-deep, #464c59)',
  'ti-carousel-indicator-active-border-radius': 'var(--ti-carousel-indicators-border-radius)',
  'ti-carousel-indicator-active-button-width': 'var(--ti-carousel-indicator-button-width)',
  'ti-carousel-indicator-active-background-color': 'var(--ti-base-color-transparent, transparent)',
  'ti-carousel-indicator-padding-horizontal': 'calc(var(--ti-common-space-1, 1px) * 2)',
  'ti-carousel-indicator-active-width': 'var(--ti-common-size-3x, 12px)',
  'ti-carousel-indicator-margin-right': 'var(--ti-common-space-0, 0px)',
  'ti-carousel-indicator-button-bg-color': 'var(--ti-common-color-info-disabled, #bfbfbf)',
  'ti-carousel-indicator-active-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-carousel-indicators-height': 'var(--ti-common-size-4x, 16px)',
  'ti-carousel-indicators-bg-color': 'rgba(3, 2, 2, 0.3)',
  'ti-carousel-arrow-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-carousel-arrow-bg-color': 'rgba(0, 0, 0, 0.3)',
  'ti-carousel-arrow-hover-bg-color': 'rgba(0, 0, 0, 0.6)',
  'ti-carousel-arrow-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-carousel-arrow-width': 'var(--ti-common-size-7x, 28px)',
  'ti-carousel-arrow-height': 'var(--ti-common-size-height-normal, 28px)'
}
