export const tinyTextareaSmbTheme = {
  'ti-textarea-border-color': 'var(--ti-common-color-line-normal)',
  'ti-textarea-count-font-size': 'var(--ti-common-font-size-0)',
  'ti-textarea-hover-border-color': 'var(--ti-common-color-line-normal)',
  'ti-textarea-padding-horizontal': 'var(--ti-common-space-3x)',
  'ti-textarea-padding-right': 'var(--ti-common-space-base)',
  'ti-textarea-hover-border-color': 'var(--ti-common-color-line-hover)',
  'ti-textarea-active-border-color': 'var(--ti-common-color-line-active)',
  'ti-textarea-count-width': 'calc(100% - 16px)',
  'ti-textarea-count-bottom': '0',
  'ti-textarea-inner-width': 'calc(100% - 4px)',
  'ti-textarea-count-right': '12px',
  'ti-textarea-padding-vertical': 'var(--ti-common-space-2x)',
  'ti-textarea-count-border-radius': 'var(--ti-common-border-radius-3)',
  'ti-textarea-count-text-length-color': 'var(--ti-common-color-text-primary)',
  'ti-textarea-placeholder-text-color': 'var(--ti-common-color-text-weaken)',
  'ti-textarea-scrollbar-width': '8px',
  'ti-textarea-scrollbar-bg-color': 'var(--ti-common-color-bg-dark-disabled)',
  'ti-textarea-scrollbar-border-radius': 'var(--ti-common-border-radius-2)',
  'ti-textarea-scrollbar-track-piece-bg-color': '#fff',
  'ti-textarea-scrollbar-hover-bg-color': 'var(--ti-common-color-bg-dark-disabled)',
  'ti-textarea-count-padding-right': 'var(--ti-common-space-base)',
  'ti-textarea-padding-bottom': 'var(--ti-common-space-4x)',
  'ti-textarea-disabled-bg-color': '#f2f2f2'
}
