export const musicalInstruments = [
  // : OptionGroup[]
  {
    label: 'Percussion instruments',
    instruments: [
      'Clapstick',
      'Gong',
      'Maraca',
      'Marimba',
      'Vibraphone',
      'Washboard',
      'Wood block',
      'More cowbell',
      'Spoon',
      'Steelpan',
      'Tambourine',
      'Triangle',
      'Wooden fish',
      'Xylophone',
      'Cowbell',
      'Cymbal'
    ]
  },
  {
    label: 'Stringed instruments',
    instruments: [
      'Aeolian harp',
      'Bandolin',
      'Banjo ukulele',
      'Double bass',
      'Dulcimer',
      'Fiddle',
      'Cello',
      'Chapman stick',
      'Clavichord',
      'Clavinet',
      'Piano',
      'Sitar',
      'Ukulele',
      'Viol',
      'Guitar',
      'Hammered dulcimer',
      'Harp',
      'Harpsichord',
      'Mandolin',
      'Octobass',
      'Violin',
      'Lute',
      'Lyre',
      'Maguhu',
      'Mandola',
      'Washtub bass'
    ]
  },
  {
    label: 'Wind instruments',
    instruments: [
      'Air horn',
      'Bagpipe',
      'Accordion',
      'Baritone horn',
      'Bassoon',
      'Blown bottle',
      'Bugle',
      'Doulophone',
      'English horn',
      'Euphonium',
      'Cornet',
      'Bazooka',
      'Beatboxing',
      'Didgeridoo',
      'Double bell euphonium',
      'Flugelhorn',
      'Clarinet',
      'Conch',
      'Flute',
      'French horn',
      'Kazoo',
      'Oboe',
      'Ocarina',
      'Melodeon',
      'Mezzo-soprano',
      'Pan flute',
      'Piccolo',
      'Slide whistle',
      'Sousaphone',
      'Trombone',
      'Pipe organ',
      'Recorder',
      'Saxophone',
      'Trumpet',
      'Tuba',
      'Harmonica',
      'Irish flute',
      'Jug',
      'Whistle'
    ]
  },
  {
    label: 'Membranophones',
    instruments: [
      'Drum',
      'Drum kit',
      "Jew's harp",
      'Octaban',
      'Barrel drum',
      'Bass drum',
      'Samphor',
      'Snare drum',
      'Timpani',
      'Bongo drums',
      'Conga',
      'Tom-tom'
    ]
  },
  {
    label: 'Electronic instruments',
    instruments: [
      'AlphaSphere',
      "Denis d'or",
      'Dubreq stylophone',
      'Drum machine',
      'Eigenharp',
      'Continuum Fingerboard',
      'Croix Sonore',
      'Electric guitar',
      'Electronic keyboard',
      'Audiocubes',
      'Bass pedals',
      'Electronic organ',
      'EWI',
      'Fingerboard synthesizer',
      'Mellotron',
      'MIDI keyboard',
      'Omnichord',
      'Ondes Martenot',
      'Kraakdoos',
      'Laser harp',
      'Otamatone',
      'Sampler',
      'Hammond organ',
      'Keyboard',
      'Keytar',
      'Seaboard music instrument',
      'Tenori-on',
      'Theremin',
      'trautonium',
      'Skoog',
      'Synclavier',
      'Synthesizer',
      'Teleharmonium',
      'Turntablism',
      'Turntable'
    ]
  }
].map(({ label, instruments }) => ({
  label,
  options: instruments.map((s) => ({ name: s, label: s }))
}))
