export const tinyAlertOldTheme = {
  'ti-alert-title-margin-top': 'var(--ti-common-space-0)',
  'ti-alert-info-close-hover-icon-color': 'var(--ti-alert-info-icon-color)',
  'ti-alert-info-close-icon-color': 'var(--ti-alert-info-icon-color)',
  'ti-alert-success-close-hover-icon-color': 'var(--ti-alert-success-icon-color)',
  'ti-alert-success-close-icon-color': 'var(--ti-alert-success-icon-color)',
  'ti-alert-error-close-hover-icon-color': 'var(--ti-alert-error-icon-color)',
  'ti-alert-error-close-icon-color': 'var(--ti-alert-error-icon-color)',
  'ti-alert-warning-close-hover-icon-color': 'var(--ti-alert-warning-icon-color)',
  'ti-alert-warning-close-icon-color': 'var(--ti-alert-warning-icon-color)',
  'ti-alert-large-content-padding-left': 'var(--ti-common-space-4x, 16px)',
  'ti-alert-large-icon-margin-top': 'calc(var(--ti-common-space-base, 4px) - 2px)',
  'ti-alert-large-padding-right': 'calc(var(--ti-common-space-base, 4px) * 10.5)',
  'ti-alert-large-padding-bottom': 'var(--ti-common-space-3x, 12px)',
  'ti-alert-large-padding-top': 'calc(var(--ti-common-space-base, 4px) * 3.5)',
  'ti-alert-normal-margin-vertical': 'var(--ti-common-space-2x, 8px)',
  'ti-alert-normal-padding-bottom': 'var(--ti-common-space-3x, 12px)',
  'ti-alert-normal-padding-right': 'var(--ti-common-space-4x, 16px)',
  'ti-alert-normal-padding-top': 'var(--ti-common-space-3x, 12px)',
  'ti-alert-description-margin-bottom': 'var(--ti-common-space-base, 4px)',
  'ti-alert-description-margin-top': 'var(--ti-common-space-base, 4px)',
  'ti-alert-icon-margin-top': 'var(--ti-common-space-1, 1px)',
  'ti-alert-title-font-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-alert-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-alert-close-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-alert-close-position-top': 'var(--ti-common-space-4x, 16px)',
  'ti-alert-border-weight': 'var(--ti-common-border-weight-normal, 1px)'
}
