export const tinyAlertSmbTheme = {
  'ti-alert-border-radius': 'var(--ti-common-border-radius-4)',
  'ti-alert-border-weight': 'var(--ti-common-size-0)',
  'ti-alert-close-font-size': 'var(--ti-common-font-size-2)',
  'ti-alert-error-close-icon-color': 'var(--ti-common-color-text-weaken)',
  'ti-alert-info-close-icon-color': 'var(--ti-common-color-text-weaken)',
  'ti-alert-success-close-icon-color': 'var(--ti-common-color-text-weaken)',
  'ti-alert-warning-close-icon-color': 'var(--ti-common-color-text-weaken)',
  'ti-alert-info-close-hover-icon-color': 'var(--ti-common-color-icon-darkbg-hover)',
  'ti-alert-success-close-hover-icon-color': 'var(--ti-common-color-icon-darkbg-hover)',
  'ti-alert-error-close-hover-icon-color': 'var(--ti-common-color-icon-darkbg-hover)',
  'ti-alert-warning-close-hover-icon-color': 'var(--ti-common-color-icon-darkbg-hover)',
  'ti-alert-normal-margin-vertical': 'var(--ti-common-space-4x)',
  'ti-alert-normal-padding-top': 'calc(var(--ti-common-space-2x) + 1.5px)',
  'ti-alert-normal-padding-bottom': 'calc(var(--ti-common-space-2x) + 1.5px)',
  'ti-alert-normal-padding-right': 'var(--ti-common-space-3x)',
  'ti-alert-title-font-size': 'var(--ti-common-font-size-2)',
  'ti-alert-large-icon-margin-top': 'calc(var(--ti-common-space-6) / 2)',
  'ti-alert-large-padding-top': 'var(--ti-common-space-4x)',
  'ti-alert-large-padding-bottom': 'var(--ti-common-space-4x)',
  'ti-alert-large-padding-right': 'var(--ti-common-space-4x)',
  'ti-alert-large-content-padding-left': 'var(--ti-common-space-2x)',
  'ti-alert-description-margin-bottom': 'var(--ti-common-space-0)',
  'ti-alert-description-margin-top': 'var(--ti-common-space-2x)',
  'ti-alert-icon-margin-top': 'calc(var(--ti-common-space-6) / 2)',
  'ti-alert-close-position-top': 'var(--ti-common-space-3x)'
}
