export const tinyAlertSmbTheme = {
  'ti-alert-border-radius': 'var(--ti-common-border-radius-4)',
  'ti-alert-description-font-size': 'var(--ti-common-font-size-1)',
  'ti-alert-warning-border-color': 'transparent',
  'ti-alert-error-border-color': 'transparent',
  'ti-alert-success-border-color': 'transparent',
  'ti-alert-info-border-color': 'transparent',
  'ti-alert-close-font-size': 'var(--ti-common-font-size-2)',
  'ti-alert-large-close-font-size': 'var(--ti-common-font-size-4)',
  'ti-alert-error-close-icon-color': 'var(--ti-common-color-text-weaken)',
  'ti-alert-info-close-icon-color': 'var(--ti-common-color-text-weaken)',
  'ti-alert-success-close-icon-color': 'var(--ti-common-color-text-weaken)',
  'ti-alert-warning-close-icon-color': 'var(--ti-common-color-text-weaken)',
  'ti-alert-info-close-hover-icon-color': '#191919',
  'ti-alert-success-close-hover-icon-color': '#191919',
  'ti-alert-error-close-hover-icon-color': '#191919',
  'ti-alert-warning-close-hover-icon-color': '#191919',
  'ti-alert-normal-margin-vertical': 'var(--ti-common-space-4x)',
  'ti-alert-normal-margin-horizontal': 'var(--ti-common-space-0)',
  'ti-alert-normal-content-padding-vertical': 'var(--ti-common-space-0)',
  'ti-alert-normal-content-padding-horizontal': 'var(--ti-common-space-2x)',
  'ti-alert-normal-padding-top': 'calc(var(--ti-common-space-2x) + 1px)',
  'ti-alert-normal-padding-bottom': 'calc(var(--ti-common-space-2x) + 1px)',
  'ti-alert-normal-padding-left': 'var(--ti-common-space-4x)',
  'ti-alert-normal-padding-right': 'var(--ti-common-space-3x)',
  'ti-alert-title-font-size': 'var(--ti-common-font-size-4)',
  'ti-alert-icon-font-size': 'var(--ti-common-font-size-base)',
  'ti-alert-large-icon-font-size': '21px',
  'ti-alert-large-icon-margin-top': '3px',
  'ti-alert-large-padding-top': 'var(--ti-common-space-4x)',
  'ti-alert-large-padding-bottom': 'var(--ti-common-space-4x)',
  'ti-alert-large-padding-left': 'var(--ti-common-space-4x)',
  'ti-alert-large-padding-right': 'var(--ti-common-space-4x)',
  'ti-alert-large-content-padding-left': 'var(--ti-common-space-2x)',
  'ti-alert-description-margin-bottom': '0',
  'ti-alert-description-margin-top': 'var(--ti-common-space-2x)',
  'ti-alert-description-line-height': '1.5'
}
