export default {
  'tiny-mobile-input-bg-color': '#fff',
  'tiny-mobile-input-line-height': '30px',
  'tiny-mobile-input-medium-height': '42px',
  'tiny-mobile-input-small-height': '36px',
  'tiny-mobile-input-mini-height': '24px',
  'tiny-mobile-input-color-disabled': '#999',
  'tiny-mobile-input-bg-color-disabled': '#f5f5f5',
  'tiny-mobile-input-exceed-text-color': '#f5222d',
  'tiny-mobile-input-icon-font-size': '16px',
  'tiny-mobile-input-icon-close-color': '#bfbfbf',
  'tiny-mobile-textarea-count-text-color': '#999',
  'tiny-mobile-textarea-count-font-size': '12px',
  'tiny-mobile-textarea-inner-height': '96px',
  'tiny-mobile-textarea-inner-font-size': '16px',
  'tiny-mobile-textarea-inner-text-color': '#666',
  'tiny-mobile-textarea-inner-placeholder-color': '#ccc',
  'tiny-mobile-textarea-title-font-size': '16px',
  'tiny-mobile-textarea-title-text-color': '#333',
  'tiny-mobile-textarea-showlimit-inner-height': '70px',
  'tiny-mobile-textarea-showcontent-inner-height': '66px',
  'tiny-mobile-input-form-bg-color-error': 'rgba(230, 34, 34, 0.04)'
}
