export const tinyLinkOldTheme = {
  'ti-link-svg-padding-bottom': 'unset',
  'ti-link-has-svg-hover-text-color': 'var(--ti-common-color-text-link, #526ecc)',
  'ti-link-info-disabled-text-color': 'var(--ti-common-color-info-disabled, #bfbfbf)',
  'ti-link-info-hover-text-color': 'var(--ti-common-color-info-hover, #5c6173)',
  'ti-link-warning-disabled-text-color': 'var(--ti-common-color-warning-disabled, #d3c6a2)',
  'ti-link-warning-hover-text-color': 'var(--ti-common-color-warning-hover, #fac20a)',
  'ti-link-success-disabled-text-color': 'var(--ti-common-color-success-disabled, #a6c3b9)',
  'ti-link-success-hover-text-color': 'var(--ti-common-color-success-hover, #acf2dc)',
  'ti-link-danger-disabled-text-color': 'var(--ti-common-color-danger-disabled, #d8bab5)',
  'ti-link-danger-hover-text-color': 'var(--ti-common-bg-primary-hover, #d64a52)',
  'ti-link-danger-border-color': 'var(--ti-common-bg-primary, #c7000b)',
  'ti-link-danger-text-color': 'var(--ti-common-bg-primary, #c7000b)',
  'ti-link-primary-disabled-text-color': 'var(--ti-common-color-primary-disabled, #a0cfff)',
  'ti-link-primary-hover-text-color': 'var(--ti-common-color-primary-hover, #7693f5)',
  'ti-link-default-hover-border-color': 'var(--ti-link-default-hover-text-color)',
  'ti-link-default-disabled-text-color': 'var(--ti-common-color-info-disabled, #bfbfbf)',
  'ti-link-default-hover-text-color': 'var(--ti-common-color-text-link, #526ecc)',
  'ti-link-default-border-color': 'var(--ti-common-color-line-active, #5e7ce0)',
  'ti-link-default-text-color': 'var(--ti-common-color-info-text, #252b3a)',
  'ti-link-icon-hover-text-weight': 'var(--ti-common-font-weight-5, 500)',
  'ti-link-svg-margin-right': '0px',
  'ti-link-svg-height': '1em',
  'ti-link-svg-width': '1em',
  'ti-link-has-icon-underline-width': '100%',
  'ti-link-font-weight': 'var(--ti-common-font-weight-5, 500)'
}
