export const tinyLinkSmbTheme = {
  'ti-link-svg-width': '16px',
  'ti-link-svg-height': 'var(--ti-common-size-5x)',
  'ti-link-svg-margin-right': '4px',
  'ti-link-font-weight': 'var(--ti-common-font-weight-4)',
  'ti-link-default-hover-border-color': '#595959',
  'ti-link-default-hover-text-color': 'var(--ti-common-color-text-highlight)',
  'ti-link-default-text-color': 'var(--ti-common-color-text-highlight)',
  'ti-link-default-disabled-text-color': '#C2C2C2',
  'ti-link-icon-hover-text-weight': 'var(--ti-common-font-weight-4)',
  'ti-link-default-border-color': '#1476FF',
  'ti-link-has-icon-underline-width': 'calc(100% - 20px)',
  'ti-link-has-svg-hover-text-color': '#1476FF',
  'ti-link-primary-disabled-text-color': 'var(--ti-common-color-primary-disabled-text)',
  'ti-link-danger-disabled-text-color': 'var(--ti-common-color-danger-disabled-text)',
  'ti-link-success-disabled-text-color': 'var(--ti-common-color-success-disabled-text)',
  'ti-link-warning-disabled-text-color': 'var(--ti-common-color-warning-disabled-text)',
  'ti-link-info-disabled-text-color': 'var(--ti-common-color-info-disabled-text)',
  'ti-link-danger-text-color': '#c7000b',
  'ti-link-danger-border-color': '#c7000b',
  'ti-link-svg-padding-bottom': 'var(--ti-common-space-2)',
  'ti-link-primary-hover-text-color': 'var(--ti-common-color-text-primary)',
  'ti-link-success-hover-text-color': 'var(--ti-common-color-success)',
  'ti-link-warning-hover-text-color': 'var(--ti-common-color-warn-text)',
  'ti-link-danger-hover-text-color': '#C7000B',
  'ti-link-info-hover-text-color': 'var(--ti-common-color-text-primary)'
}
