import ActionMenu from '@opentiny/vue-action-menu'
import Alert from '@opentiny/vue-alert'
import Amount from '@opentiny/vue-amount'
import Anchor from '@opentiny/vue-anchor'
import Area from '@opentiny/vue-area'
import Autocomplete from '@opentiny/vue-autocomplete'
import Badge from '@opentiny/vue-badge'
import BaseSelect from '@opentiny/vue-base-select'
import Breadcrumb from '@opentiny/vue-breadcrumb'
import BreadcrumbItem from '@opentiny/vue-breadcrumb-item'
import BulletinBoard from '@opentiny/vue-bulletin-board'
import Button from '@opentiny/vue-button'
import ButtonGroup from '@opentiny/vue-button-group'
import Calendar from '@opentiny/vue-calendar'
import CalendarView from '@opentiny/vue-calendar-view'
import Card from '@opentiny/vue-card'
import CardGroup from '@opentiny/vue-card-group'
import CardTemplate from '@opentiny/vue-card-template'
import Carousel from '@opentiny/vue-carousel'
import CarouselItem from '@opentiny/vue-carousel-item'
import Cascader from '@opentiny/vue-cascader'
import CascaderMenu from '@opentiny/vue-cascader-menu'
import CascaderNode from '@opentiny/vue-cascader-node'
import CascaderPanel from '@opentiny/vue-cascader-panel'
import Checkbox from '@opentiny/vue-checkbox'
import CheckboxButton from '@opentiny/vue-checkbox-button'
import CheckboxGroup from '@opentiny/vue-checkbox-group'
import Col from '@opentiny/vue-col'
import Collapse from '@opentiny/vue-collapse'
import CollapseItem from '@opentiny/vue-collapse-item'
import CollapseTransition from '@opentiny/vue-collapse-transition'
import ColorPicker from '@opentiny/vue-color-picker'
import ColorSelectPanel from '@opentiny/vue-color-select-panel'
import Company from '@opentiny/vue-company'
import ConfigProvider from '@opentiny/vue-config-provider'
import Container from '@opentiny/vue-container'
import Country from '@opentiny/vue-country'
import Crop from '@opentiny/vue-crop'
import Currency from '@opentiny/vue-currency'
import DatePanel from '@opentiny/vue-date-panel'
import DatePicker from '@opentiny/vue-date-picker'
import DatePickerMobileFirst from '@opentiny/vue-date-picker-mobile-first'
import DateRange from '@opentiny/vue-date-range'
import DateTable from '@opentiny/vue-date-table'
import Dept from '@opentiny/vue-dept'
import DialogBox from '@opentiny/vue-dialog-box'
import DialogSelect from '@opentiny/vue-dialog-select'
import Divider from '@opentiny/vue-divider'
import Drawer from '@opentiny/vue-drawer'
import DropRoles from '@opentiny/vue-drop-roles'
import DropTimes from '@opentiny/vue-drop-times'
import Dropdown from '@opentiny/vue-dropdown'
import DropdownItem from '@opentiny/vue-dropdown-item'
import DropdownMenu from '@opentiny/vue-dropdown-menu'
import DynamicScroller from '@opentiny/vue-dynamic-scroller'
import DynamicScrollerItem from '@opentiny/vue-dynamic-scroller-item'
import Espace from '@opentiny/vue-espace'
import Exception from '@opentiny/vue-exception'
import FallMenu from '@opentiny/vue-fall-menu'
import FileUpload from '@opentiny/vue-file-upload'
import FilterBox from '@opentiny/vue-filter-box'
import FilterPanel from '@opentiny/vue-filter-panel'
import FloatButton from '@opentiny/vue-float-button'
import Floatbar from '@opentiny/vue-floatbar'
import Flowchart from '@opentiny/vue-flowchart'
import FluentEditor from '@opentiny/vue-fluent-editor'
import Form from '@opentiny/vue-form'
import FormItem from '@opentiny/vue-form-item'
import Fullscreen from '@opentiny/vue-fullscreen'
import Grid from '@opentiny/vue-grid'
import GridColumn from '@opentiny/vue-grid-column'
import GridManager from '@opentiny/vue-grid-manager'
import GridSelect from '@opentiny/vue-grid-select'
import GridToolbar from '@opentiny/vue-grid-toolbar'
import Guide from '@opentiny/vue-guide'
import Hrapprover from '@opentiny/vue-hrapprover'
import Image from '@opentiny/vue-image'
import ImageViewer from '@opentiny/vue-image-viewer'
import Input from '@opentiny/vue-input'
import IpAddress from '@opentiny/vue-ip-address'
import Layout from '@opentiny/vue-layout'
import Link from '@opentiny/vue-link'
import LinkMenu from '@opentiny/vue-link-menu'
import Loading from '@opentiny/vue-loading'
import Locales from '@opentiny/vue-locales'
import LogonUser from '@opentiny/vue-logon-user'
import Logout from '@opentiny/vue-logout'
import Message from '@opentiny/vue-message'
import Milestone from '@opentiny/vue-milestone'
import MindMap from '@opentiny/vue-mind-map'
import Modal from '@opentiny/vue-modal'
import MonthRange from '@opentiny/vue-month-range'
import MonthTable from '@opentiny/vue-month-table'
import NavMenu from '@opentiny/vue-nav-menu'
import Notify from '@opentiny/vue-notify'
import NumberAnimation from '@opentiny/vue-number-animation'
import Numeric from '@opentiny/vue-numeric'
import Option from '@opentiny/vue-option'
import OptionGroup from '@opentiny/vue-option-group'
import Pager from '@opentiny/vue-pager'
import PagerItem from '@opentiny/vue-pager-item'
import Panel from '@opentiny/vue-panel'
import Picker from '@opentiny/vue-picker'
import PopUpload from '@opentiny/vue-pop-upload'
import Popconfirm from '@opentiny/vue-popconfirm'
import Popeditor from '@opentiny/vue-popeditor'
import Popover from '@opentiny/vue-popover'
import Popup from '@opentiny/vue-popup'
import Progress from '@opentiny/vue-progress'
import QrCode from '@opentiny/vue-qr-code'
import QuarterPanel from '@opentiny/vue-quarter-panel'
import QueryBuilder from '@opentiny/vue-query-builder'
import Radio from '@opentiny/vue-radio'
import RadioButton from '@opentiny/vue-radio-button'
import RadioGroup from '@opentiny/vue-radio-group'
import Rate from '@opentiny/vue-rate'
import RecycleScroller from '@opentiny/vue-recycle-scroller'
import River from '@opentiny/vue-river'
import Roles from '@opentiny/vue-roles'
import Row from '@opentiny/vue-row'
import ScrollText from '@opentiny/vue-scroll-text'
import Scrollbar from '@opentiny/vue-scrollbar'
import Search from '@opentiny/vue-search'
import Select from '@opentiny/vue-select'
import SelectWrapper from '@opentiny/vue-select-wrapper'
import SelectDropdown from '@opentiny/vue-select-dropdown'
import SelectedBox from '@opentiny/vue-selected-box'
import Skeleton from '@opentiny/vue-skeleton'
import SkeletonItem from '@opentiny/vue-skeleton-item'
import Slider from '@opentiny/vue-slider'
import Space from '@opentiny/vue-space'
import Split from '@opentiny/vue-split'
import Statistic from '@opentiny/vue-statistic'
import Steps from '@opentiny/vue-steps'
import Sticky from '@opentiny/vue-sticky'
import Switch from '@opentiny/vue-switch'
import TabItem from '@opentiny/vue-tab-item'
import Table from '@opentiny/vue-table'
import Tabs from '@opentiny/vue-tabs'
import Tag from '@opentiny/vue-tag'
import TagGroup from '@opentiny/vue-tag-group'
import TextPopup from '@opentiny/vue-text-popup'
import Time from '@opentiny/vue-time'
import TimeLine from '@opentiny/vue-time-line'
import TimePanel from '@opentiny/vue-time-panel'
import TimePicker from '@opentiny/vue-time-picker'
import TimeRange from '@opentiny/vue-time-range'
import TimeSelect from '@opentiny/vue-time-select'
import TimeSpinner from '@opentiny/vue-time-spinner'
import TimelineItem from '@opentiny/vue-timeline-item'
import ToggleMenu from '@opentiny/vue-toggle-menu'
import Tooltip from '@opentiny/vue-tooltip'
import TopBox from '@opentiny/vue-top-box'
import Transfer from '@opentiny/vue-transfer'
import TransferPanel from '@opentiny/vue-transfer-panel'
import Tree from '@opentiny/vue-tree'
import TreeMenu from '@opentiny/vue-tree-menu'
import TreeSelect from '@opentiny/vue-tree-select'
import Upload from '@opentiny/vue-upload'
import UploadDragger from '@opentiny/vue-upload-dragger'
import UploadList from '@opentiny/vue-upload-list'
import User from '@opentiny/vue-user'
import UserAccount from '@opentiny/vue-user-account'
import UserContact from '@opentiny/vue-user-contact'
import UserHead from '@opentiny/vue-user-head'
import UserLink from '@opentiny/vue-user-link'
import VirtualScrollBox from '@opentiny/vue-virtual-scroll-box'
import VirtualTree from '@opentiny/vue-virtual-tree'
import Watermark from '@opentiny/vue-watermark'
import Wizard from '@opentiny/vue-wizard'
import YearRange from '@opentiny/vue-year-range'
import YearTable from '@opentiny/vue-year-table'
import { $prefix } from '@opentiny/vue-common'

const components = [
  ActionMenu,
  Alert,
  Amount,
  Anchor,
  Area,
  Autocomplete,
  Badge,
  BaseSelect,
  Breadcrumb,
  BreadcrumbItem,
  BulletinBoard,
  Button,
  ButtonGroup,
  Calendar,
  CalendarView,
  Card,
  CardGroup,
  CardTemplate,
  Carousel,
  CarouselItem,
  Cascader,
  CascaderMenu,
  CascaderNode,
  CascaderPanel,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Col,
  Collapse,
  CollapseItem,
  CollapseTransition,
  ColorPicker,
  ColorSelectPanel,
  Company,
  ConfigProvider,
  Container,
  Country,
  Crop,
  Currency,
  DatePanel,
  DatePicker,
  DatePickerMobileFirst,
  DateRange,
  DateTable,
  Dept,
  DialogBox,
  DialogSelect,
  Divider,
  Drawer,
  DropRoles,
  DropTimes,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  DynamicScroller,
  DynamicScrollerItem,
  Espace,
  Exception,
  FallMenu,
  FileUpload,
  FilterBox,
  FilterPanel,
  FloatButton,
  Floatbar,
  Flowchart,
  FluentEditor,
  Form,
  FormItem,
  Fullscreen,
  Grid,
  GridColumn,
  GridManager,
  GridSelect,
  GridToolbar,
  Guide,
  Hrapprover,
  Image,
  ImageViewer,
  Input,
  IpAddress,
  Layout,
  Link,
  LinkMenu,
  Loading,
  Locales,
  LogonUser,
  Logout,
  Message,
  Milestone,
  MindMap,
  Modal,
  MonthRange,
  MonthTable,
  NavMenu,
  Notify,
  NumberAnimation,
  Numeric,
  Option,
  OptionGroup,
  Pager,
  PagerItem,
  Panel,
  Picker,
  PopUpload,
  Popconfirm,
  Popeditor,
  Popover,
  Popup,
  Progress,
  QrCode,
  QuarterPanel,
  QueryBuilder,
  Radio,
  RadioButton,
  RadioGroup,
  Rate,
  RecycleScroller,
  River,
  Roles,
  Row,
  ScrollText,
  Scrollbar,
  Search,
  Select,
  SelectWrapper,
  SelectDropdown,
  SelectedBox,
  Skeleton,
  SkeletonItem,
  Slider,
  Space,
  Split,
  Statistic,
  Steps,
  Sticky,
  Switch,
  TabItem,
  Table,
  Tabs,
  Tag,
  TagGroup,
  TextPopup,
  Time,
  TimeLine,
  TimePanel,
  TimePicker,
  TimeRange,
  TimeSelect,
  TimeSpinner,
  TimelineItem,
  ToggleMenu,
  Tooltip,
  TopBox,
  Transfer,
  TransferPanel,
  Tree,
  TreeMenu,
  TreeSelect,
  Upload,
  UploadDragger,
  UploadList,
  User,
  UserAccount,
  UserContact,
  UserHead,
  UserLink,
  VirtualScrollBox,
  VirtualTree,
  Watermark,
  Wizard,
  YearRange,
  YearTable
]

export const install = (app, opts = {}) => {
  const regex = new RegExp('^' + $prefix)

  const appProperties = app.config?.globalProperties || app.prototype
  appProperties.tiny_mode = { value: 'pc' }

  components.forEach((component) => {
    const name = component.name
    const alias = opts.alias || opts.prefix

    if (typeof component.install !== 'function') return

    if (name && alias) {
      app.component(name.replace(regex, alias), component)
    } else {
      component.install(app)
    }
  })
}

export const version = '3.27.0'

export {
  ActionMenu,
  ActionMenu as TinyActionMenu,
  Alert,
  Alert as TinyAlert,
  Amount,
  Amount as TinyAmount,
  Anchor,
  Anchor as TinyAnchor,
  Area,
  Area as TinyArea,
  Autocomplete,
  Autocomplete as TinyAutocomplete,
  Badge,
  Badge as TinyBadge,
  BaseSelect,
  BaseSelect as TinyBaseSelect,
  Breadcrumb,
  Breadcrumb as TinyBreadcrumb,
  BreadcrumbItem,
  BreadcrumbItem as TinyBreadcrumbItem,
  BulletinBoard,
  BulletinBoard as TinyBulletinBoard,
  Button,
  Button as TinyButton,
  ButtonGroup,
  ButtonGroup as TinyButtonGroup,
  Calendar,
  Calendar as TinyCalendar,
  CalendarView,
  CalendarView as TinyCalendarView,
  Card,
  Card as TinyCard,
  CardGroup,
  CardGroup as TinyCardGroup,
  CardTemplate,
  CardTemplate as TinyCardTemplate,
  Carousel,
  Carousel as TinyCarousel,
  CarouselItem,
  CarouselItem as TinyCarouselItem,
  Cascader,
  Cascader as TinyCascader,
  CascaderMenu,
  CascaderMenu as TinyCascaderMenu,
  CascaderNode,
  CascaderNode as TinyCascaderNode,
  CascaderPanel,
  CascaderPanel as TinyCascaderPanel,
  Checkbox,
  Checkbox as TinyCheckbox,
  CheckboxButton,
  CheckboxButton as TinyCheckboxButton,
  CheckboxGroup,
  CheckboxGroup as TinyCheckboxGroup,
  Col,
  Col as TinyCol,
  Collapse,
  Collapse as TinyCollapse,
  CollapseItem,
  CollapseItem as TinyCollapseItem,
  CollapseTransition,
  CollapseTransition as TinyCollapseTransition,
  ColorPicker,
  ColorPicker as TinyColorPicker,
  ColorSelectPanel,
  ColorSelectPanel as TinyColorSelectPanel,
  Company,
  Company as TinyCompany,
  ConfigProvider,
  ConfigProvider as TinyConfigProvider,
  Container,
  Container as TinyContainer,
  Country,
  Country as TinyCountry,
  Crop,
  Crop as TinyCrop,
  Currency,
  Currency as TinyCurrency,
  DatePanel,
  DatePanel as TinyDatePanel,
  DatePicker,
  DatePicker as TinyDatePicker,
  DatePickerMobileFirst,
  DatePickerMobileFirst as TinyDatePickerMobileFirst,
  DateRange,
  DateRange as TinyDateRange,
  DateTable,
  DateTable as TinyDateTable,
  Dept,
  Dept as TinyDept,
  DialogBox,
  DialogBox as TinyDialogBox,
  DialogSelect,
  DialogSelect as TinyDialogSelect,
  Divider,
  Divider as TinyDivider,
  Drawer,
  Drawer as TinyDrawer,
  DropRoles,
  DropRoles as TinyDropRoles,
  DropTimes,
  DropTimes as TinyDropTimes,
  Dropdown,
  Dropdown as TinyDropdown,
  DropdownItem,
  DropdownItem as TinyDropdownItem,
  DropdownMenu,
  DropdownMenu as TinyDropdownMenu,
  DynamicScroller,
  DynamicScroller as TinyDynamicScroller,
  DynamicScrollerItem,
  DynamicScrollerItem as TinyDynamicScrollerItem,
  Espace,
  Espace as TinyEspace,
  Exception,
  Exception as TinyException,
  FallMenu,
  FallMenu as TinyFallMenu,
  FileUpload,
  FileUpload as TinyFileUpload,
  FilterBox,
  FilterBox as TinyFilterBox,
  FilterPanel,
  FilterPanel as TinyFilterPanel,
  FloatButton,
  FloatButton as TinyFloatButton,
  Floatbar,
  Floatbar as TinyFloatbar,
  Flowchart,
  Flowchart as TinyFlowchart,
  FluentEditor,
  FluentEditor as TinyFluentEditor,
  Form,
  Form as TinyForm,
  FormItem,
  FormItem as TinyFormItem,
  Fullscreen,
  Fullscreen as TinyFullscreen,
  Grid,
  Grid as TinyGrid,
  GridColumn,
  GridColumn as TinyGridColumn,
  GridManager,
  GridManager as TinyGridManager,
  GridSelect,
  GridSelect as TinyGridSelect,
  GridToolbar,
  GridToolbar as TinyGridToolbar,
  Guide,
  Guide as TinyGuide,
  Hrapprover,
  Hrapprover as TinyHrapprover,
  Image,
  Image as TinyImage,
  ImageViewer,
  ImageViewer as TinyImageViewer,
  Input,
  Input as TinyInput,
  IpAddress,
  IpAddress as TinyIpAddress,
  Layout,
  Layout as TinyLayout,
  Link,
  Link as TinyLink,
  LinkMenu,
  LinkMenu as TinyLinkMenu,
  Loading,
  Loading as TinyLoading,
  Locales,
  Locales as TinyLocales,
  LogonUser,
  LogonUser as TinyLogonUser,
  Logout,
  Logout as TinyLogout,
  Message,
  Message as TinyMessage,
  Milestone,
  Milestone as TinyMilestone,
  MindMap,
  MindMap as TinyMindMap,
  Modal,
  Modal as TinyModal,
  MonthRange,
  MonthRange as TinyMonthRange,
  MonthTable,
  MonthTable as TinyMonthTable,
  NavMenu,
  NavMenu as TinyNavMenu,
  Notify,
  Notify as TinyNotify,
  NumberAnimation,
  NumberAnimation as TinyNumberAnimation,
  Numeric,
  Numeric as TinyNumeric,
  Option,
  Option as TinyOption,
  OptionGroup,
  OptionGroup as TinyOptionGroup,
  Pager,
  Pager as TinyPager,
  PagerItem,
  PagerItem as TinyPagerItem,
  Panel,
  Panel as TinyPanel,
  Picker,
  Picker as TinyPicker,
  PopUpload,
  PopUpload as TinyPopUpload,
  Popconfirm,
  Popconfirm as TinyPopconfirm,
  Popeditor,
  Popeditor as TinyPopeditor,
  Popover,
  Popover as TinyPopover,
  Popup,
  Popup as TinyPopup,
  Progress,
  Progress as TinyProgress,
  QrCode,
  QrCode as TinyQrCode,
  QuarterPanel,
  QuarterPanel as TinyQuarterPanel,
  QueryBuilder,
  QueryBuilder as TinyQueryBuilder,
  Radio,
  Radio as TinyRadio,
  RadioButton,
  RadioButton as TinyRadioButton,
  RadioGroup,
  RadioGroup as TinyRadioGroup,
  Rate,
  Rate as TinyRate,
  RecycleScroller,
  RecycleScroller as TinyRecycleScroller,
  River,
  River as TinyRiver,
  Roles,
  Roles as TinyRoles,
  Row,
  Row as TinyRow,
  ScrollText,
  ScrollText as TinyScrollText,
  Scrollbar,
  Scrollbar as TinyScrollbar,
  Search,
  Search as TinySearch,
  Select,
  Select as TinySelect,
  SelectWrapper,
  SelectWrapper as TinySelectWrapper,
  SelectDropdown,
  SelectDropdown as TinySelectDropdown,
  SelectedBox,
  SelectedBox as TinySelectedBox,
  Skeleton,
  Skeleton as TinySkeleton,
  SkeletonItem,
  SkeletonItem as TinySkeletonItem,
  Slider,
  Slider as TinySlider,
  Space,
  Space as TinySpace,
  Split,
  Split as TinySplit,
  Statistic,
  Statistic as TinyStatistic,
  Steps,
  Steps as TinySteps,
  Sticky,
  Sticky as TinySticky,
  Switch,
  Switch as TinySwitch,
  TabItem,
  TabItem as TinyTabItem,
  Table,
  Table as TinyTable,
  Tabs,
  Tabs as TinyTabs,
  Tag,
  Tag as TinyTag,
  TagGroup,
  TagGroup as TinyTagGroup,
  TextPopup,
  TextPopup as TinyTextPopup,
  Time,
  Time as TinyTime,
  TimeLine,
  TimeLine as TinyTimeLine,
  TimePanel,
  TimePanel as TinyTimePanel,
  TimePicker,
  TimePicker as TinyTimePicker,
  TimeRange,
  TimeRange as TinyTimeRange,
  TimeSelect,
  TimeSelect as TinyTimeSelect,
  TimeSpinner,
  TimeSpinner as TinyTimeSpinner,
  TimelineItem,
  TimelineItem as TinyTimelineItem,
  ToggleMenu,
  ToggleMenu as TinyToggleMenu,
  Tooltip,
  Tooltip as TinyTooltip,
  TopBox,
  TopBox as TinyTopBox,
  Transfer,
  Transfer as TinyTransfer,
  TransferPanel,
  TransferPanel as TinyTransferPanel,
  Tree,
  Tree as TinyTree,
  TreeMenu,
  TreeMenu as TinyTreeMenu,
  TreeSelect,
  TreeSelect as TinyTreeSelect,
  Upload,
  Upload as TinyUpload,
  UploadDragger,
  UploadDragger as TinyUploadDragger,
  UploadList,
  UploadList as TinyUploadList,
  User,
  User as TinyUser,
  UserAccount,
  UserAccount as TinyUserAccount,
  UserContact,
  UserContact as TinyUserContact,
  UserHead,
  UserHead as TinyUserHead,
  UserLink,
  UserLink as TinyUserLink,
  VirtualScrollBox,
  VirtualScrollBox as TinyVirtualScrollBox,
  VirtualTree,
  VirtualTree as TinyVirtualTree,
  Watermark,
  Watermark as TinyWatermark,
  Wizard,
  Wizard as TinyWizard,
  YearRange,
  YearRange as TinyYearRange,
  YearTable,
  YearTable as TinyYearTable
}

export default {
  ActionMenu,
  TinyActionMenu: ActionMenu,
  Alert,
  TinyAlert: Alert,
  Amount,
  TinyAmount: Amount,
  Anchor,
  TinyAnchor: Anchor,
  Area,
  TinyArea: Area,
  Autocomplete,
  TinyAutocomplete: Autocomplete,
  Badge,
  TinyBadge: Badge,
  BaseSelect,
  TinyBaseSelect: BaseSelect,
  Breadcrumb,
  TinyBreadcrumb: Breadcrumb,
  BreadcrumbItem,
  TinyBreadcrumbItem: BreadcrumbItem,
  BulletinBoard,
  TinyBulletinBoard: BulletinBoard,
  Button,
  TinyButton: Button,
  ButtonGroup,
  TinyButtonGroup: ButtonGroup,
  Calendar,
  TinyCalendar: Calendar,
  CalendarView,
  TinyCalendarView: CalendarView,
  Card,
  TinyCard: Card,
  CardGroup,
  TinyCardGroup: CardGroup,
  CardTemplate,
  TinyCardTemplate: CardTemplate,
  Carousel,
  TinyCarousel: Carousel,
  CarouselItem,
  TinyCarouselItem: CarouselItem,
  Cascader,
  TinyCascader: Cascader,
  CascaderMenu,
  TinyCascaderMenu: CascaderMenu,
  CascaderNode,
  TinyCascaderNode: CascaderNode,
  CascaderPanel,
  TinyCascaderPanel: CascaderPanel,
  Checkbox,
  TinyCheckbox: Checkbox,
  CheckboxButton,
  TinyCheckboxButton: CheckboxButton,
  CheckboxGroup,
  TinyCheckboxGroup: CheckboxGroup,
  Col,
  TinyCol: Col,
  Collapse,
  TinyCollapse: Collapse,
  CollapseItem,
  TinyCollapseItem: CollapseItem,
  CollapseTransition,
  TinyCollapseTransition: CollapseTransition,
  ColorPicker,
  TinyColorPicker: ColorPicker,
  ColorSelectPanel,
  TinyColorSelectPanel: ColorSelectPanel,
  Company,
  TinyCompany: Company,
  ConfigProvider,
  TinyConfigProvider: ConfigProvider,
  Container,
  TinyContainer: Container,
  Country,
  TinyCountry: Country,
  Crop,
  TinyCrop: Crop,
  Currency,
  TinyCurrency: Currency,
  DatePanel,
  TinyDatePanel: DatePanel,
  DatePicker,
  TinyDatePicker: DatePicker,
  DatePickerMobileFirst,
  TinyDatePickerMobileFirst: DatePickerMobileFirst,
  DateRange,
  TinyDateRange: DateRange,
  DateTable,
  TinyDateTable: DateTable,
  Dept,
  TinyDept: Dept,
  DialogBox,
  TinyDialogBox: DialogBox,
  DialogSelect,
  TinyDialogSelect: DialogSelect,
  Divider,
  TinyDivider: Divider,
  Drawer,
  TinyDrawer: Drawer,
  DropRoles,
  TinyDropRoles: DropRoles,
  DropTimes,
  TinyDropTimes: DropTimes,
  Dropdown,
  TinyDropdown: Dropdown,
  DropdownItem,
  TinyDropdownItem: DropdownItem,
  DropdownMenu,
  TinyDropdownMenu: DropdownMenu,
  DynamicScroller,
  TinyDynamicScroller: DynamicScroller,
  DynamicScrollerItem,
  TinyDynamicScrollerItem: DynamicScrollerItem,
  Espace,
  TinyEspace: Espace,
  Exception,
  TinyException: Exception,
  FallMenu,
  TinyFallMenu: FallMenu,
  FileUpload,
  TinyFileUpload: FileUpload,
  FilterBox,
  TinyFilterBox: FilterBox,
  FilterPanel,
  TinyFilterPanel: FilterPanel,
  FloatButton,
  TinyFloatButton: FloatButton,
  Floatbar,
  TinyFloatbar: Floatbar,
  Flowchart,
  TinyFlowchart: Flowchart,
  FluentEditor,
  TinyFluentEditor: FluentEditor,
  Form,
  TinyForm: Form,
  FormItem,
  TinyFormItem: FormItem,
  Fullscreen,
  TinyFullscreen: Fullscreen,
  Grid,
  TinyGrid: Grid,
  GridColumn,
  TinyGridColumn: GridColumn,
  GridManager,
  TinyGridManager: GridManager,
  GridSelect,
  TinyGridSelect: GridSelect,
  GridToolbar,
  TinyGridToolbar: GridToolbar,
  Guide,
  TinyGuide: Guide,
  Hrapprover,
  TinyHrapprover: Hrapprover,
  Image,
  TinyImage: Image,
  ImageViewer,
  TinyImageViewer: ImageViewer,
  Input,
  TinyInput: Input,
  IpAddress,
  TinyIpAddress: IpAddress,
  Layout,
  TinyLayout: Layout,
  Link,
  TinyLink: Link,
  LinkMenu,
  TinyLinkMenu: LinkMenu,
  Loading,
  TinyLoading: Loading,
  Locales,
  TinyLocales: Locales,
  LogonUser,
  TinyLogonUser: LogonUser,
  Logout,
  TinyLogout: Logout,
  Message,
  TinyMessage: Message,
  Milestone,
  TinyMilestone: Milestone,
  MindMap,
  TinyMindMap: MindMap,
  Modal,
  TinyModal: Modal,
  MonthRange,
  TinyMonthRange: MonthRange,
  MonthTable,
  TinyMonthTable: MonthTable,
  NavMenu,
  TinyNavMenu: NavMenu,
  Notify,
  TinyNotify: Notify,
  NumberAnimation,
  TinyNumberAnimation: NumberAnimation,
  Numeric,
  TinyNumeric: Numeric,
  Option,
  TinyOption: Option,
  OptionGroup,
  TinyOptionGroup: OptionGroup,
  Pager,
  TinyPager: Pager,
  PagerItem,
  TinyPagerItem: PagerItem,
  Panel,
  TinyPanel: Panel,
  Picker,
  TinyPicker: Picker,
  PopUpload,
  TinyPopUpload: PopUpload,
  Popconfirm,
  TinyPopconfirm: Popconfirm,
  Popeditor,
  TinyPopeditor: Popeditor,
  Popover,
  TinyPopover: Popover,
  Popup,
  TinyPopup: Popup,
  Progress,
  TinyProgress: Progress,
  QrCode,
  TinyQrCode: QrCode,
  QuarterPanel,
  TinyQuarterPanel: QuarterPanel,
  QueryBuilder,
  TinyQueryBuilder: QueryBuilder,
  Radio,
  TinyRadio: Radio,
  RadioButton,
  TinyRadioButton: RadioButton,
  RadioGroup,
  TinyRadioGroup: RadioGroup,
  Rate,
  TinyRate: Rate,
  RecycleScroller,
  TinyRecycleScroller: RecycleScroller,
  River,
  TinyRiver: River,
  Roles,
  TinyRoles: Roles,
  Row,
  TinyRow: Row,
  ScrollText,
  TinyScrollText: ScrollText,
  Scrollbar,
  TinyScrollbar: Scrollbar,
  Search,
  TinySearch: Search,
  Select,
  TinySelect: Select,
  SelectWrapper,
  TinySelectWrapper: SelectWrapper,
  SelectDropdown,
  TinySelectDropdown: SelectDropdown,
  SelectedBox,
  TinySelectedBox: SelectedBox,
  Skeleton,
  TinySkeleton: Skeleton,
  SkeletonItem,
  TinySkeletonItem: SkeletonItem,
  Slider,
  TinySlider: Slider,
  Space,
  TinySpace: Space,
  Split,
  TinySplit: Split,
  Statistic,
  TinyStatistic: Statistic,
  Steps,
  TinySteps: Steps,
  Sticky,
  TinySticky: Sticky,
  Switch,
  TinySwitch: Switch,
  TabItem,
  TinyTabItem: TabItem,
  Table,
  TinyTable: Table,
  Tabs,
  TinyTabs: Tabs,
  Tag,
  TinyTag: Tag,
  TagGroup,
  TinyTagGroup: TagGroup,
  TextPopup,
  TinyTextPopup: TextPopup,
  Time,
  TinyTime: Time,
  TimeLine,
  TinyTimeLine: TimeLine,
  TimePanel,
  TinyTimePanel: TimePanel,
  TimePicker,
  TinyTimePicker: TimePicker,
  TimeRange,
  TinyTimeRange: TimeRange,
  TimeSelect,
  TinyTimeSelect: TimeSelect,
  TimeSpinner,
  TinyTimeSpinner: TimeSpinner,
  TimelineItem,
  TinyTimelineItem: TimelineItem,
  ToggleMenu,
  TinyToggleMenu: ToggleMenu,
  Tooltip,
  TinyTooltip: Tooltip,
  TopBox,
  TinyTopBox: TopBox,
  Transfer,
  TinyTransfer: Transfer,
  TransferPanel,
  TinyTransferPanel: TransferPanel,
  Tree,
  TinyTree: Tree,
  TreeMenu,
  TinyTreeMenu: TreeMenu,
  TreeSelect,
  TinyTreeSelect: TreeSelect,
  Upload,
  TinyUpload: Upload,
  UploadDragger,
  TinyUploadDragger: UploadDragger,
  UploadList,
  TinyUploadList: UploadList,
  User,
  TinyUser: User,
  UserAccount,
  TinyUserAccount: UserAccount,
  UserContact,
  TinyUserContact: UserContact,
  UserHead,
  TinyUserHead: UserHead,
  UserLink,
  TinyUserLink: UserLink,
  VirtualScrollBox,
  TinyVirtualScrollBox: VirtualScrollBox,
  VirtualTree,
  TinyVirtualTree: VirtualTree,
  Watermark,
  TinyWatermark: Watermark,
  Wizard,
  TinyWizard: Wizard,
  YearRange,
  TinyYearRange: YearRange,
  YearTable,
  TinyYearTable: YearTable,
  install
} as any
