export const tinyPagerOldTheme = {
  'tv-Pager-sizes-num-margin-right': 'var(--ti-common-space-base, 4px)',
  'tv-Pager-mini-min-width': '18px',
  'tv-Pager-selector-padding-y': 'var(--ti-common-space-3x, 12px)',
  'tv-Pager-input-btn-padding-horizontal': '6px',
  'tv-Pager-sizes-input-hover-text-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'tv-Pager-prev-next-hover-bg-color': 'var(--ti-common-color-hover-background, #f2f5fc)',
  'tv-Pager-dot-is-popup-svg-font-size': '14px',
  'tv-Pager-svg-font-size': 'var(--tv-Pager-font-size)',
  'tv-Pager-total-svg-fill-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'tv-Pager-total-line-height': '24px',
  'tv-Pager-total-height': '24px',
  'tv-Pager-total-font-size': '12px',
  'tv-Pager-btn-svg-fill-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'tv-Pager-next-margin-left': '6px',
  'tv-Pager-next-margin-right': '6px',
  'tv-Pager-next-padding-right': '4px',
  'tv-Pager-prev-margin-right': '4px',
  'tv-Pager-prev-margin-left': '4px',
  'tv-Pager-prev-padding-right': '6px',
  'tv-Pager-prev-padding-left': '6px',
  'tv-Pager-goto-btn-text-hover-color': 'var(--ti-common-color-text-highlight, #526ecc)',
  'tv-Pager-poplist-item-min-height': '30px',
  'tv-Pager-poplist-item-selected-bg-color': 'var(--ti-common-color-selected-background, #5e7ce0)',
  'tv-Pager-poplist-item-hover-text-color': 'var(--ti-common-color-text-highlight, #526ecc)',
  'tv-Pager-poplist-item-hover-bg-color': 'var(--ti-common-color-hover-background, #f2f5fc)',
  'tv-Pager-li-item-hover-font-weight': 'var(--ti-common-font-weight-normal)',
  'tv-Pager-li-item-hover-text-color': 'var(--ti-common-color-text-highlight, #526ecc)',
  'tv-Pager-li-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'tv-Pager-poplist-item-padding-horizontal': 'var(--ti-common-space-6, 6px)',
  'tv-Pager-input-padding-horizontal': '0',
  'tv-Pager-input-width': '40px',
  'tv-Pager-min-width': 'auto',
  'tv-Pager-height': 'var(--ti-common-size-height-mini, 24px)',
  'tv-Pager-normal-text-padding-left': 'calc(var(--ti-common-space-base) * 3 + 2px, 14px)',
  'tv-Pager-mini-font-size': 'var(--ti-common-font-size-base, 12px)',
  'tv-Pager-input-padding-y': '10px',
  'tv-Pager-input-height': 'var(--ti-common-size-height-mini, 24px)',
  'tv-Pager-input-border-color': 'var(--ti-common-color-border, #adb0b8)',
  'tv-Pager-active-font-weight': 'var(--ti-common-font-weight-normal)',
  'tv-Pager-active-bg-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'tv-Pager-active-font-color': 'var(--ti-common-color-text-white, #fff)',
  'tv-Pager-primary-bg-color': 'var(--ti-common-color-primary-normal, #5e7ce0)'
}
