export const tinyPagerOldTheme = {
  'ti-pager-sizes-num-margin-right': 'var(--ti-common-space-base, 4px)',
  'ti-pager-mini-min-width': '18px',
  'ti-pager-selector-padding-vertical': 'var(--ti-common-space-3x, 12px)',
  'ti-pager-input-btn-padding-horizontal': '6px',
  'ti-pager-sizes-input-hover-text-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-pager-group-sizes-margin-right': '16px',
  'ti-pager-prev-next-hover-bg-color': 'var(--ti-common-color-hover-background, #f2f5fc)',
  'ti-pager-dot-is-popup-svg-font-size': '14px',
  'ti-pager-svg-font-size': 'var(--ti-pager-font-size)',
  'ti-pager-total-svg-fill-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-pager-total-line-height': '24px',
  'ti-pager-total-height': '24px',
  'ti-pager-total-font-size': '12px',
  'ti-pager-btn-svg-fill-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-pager-next-margin-left': '6px',
  'ti-pager-next-margin-right': '6px',
  'ti-pager-next-padding-right': '4px',
  'ti-pager-prev-margin-right': '4px',
  'ti-pager-prev-margin-left': '4px',
  'ti-pager-prev-padding-right': '6px',
  'ti-pager-prev-padding-left': '6px',
  'ti-pager-goto-btn-text-hover-color': 'var(--ti-common-color-text-highlight, #526ecc)',
  'ti-pager-poplist-item-min-height': '30px',
  'ti-pager-poplist-item-selected-bg-color': 'var(--ti-common-color-selected-background, #5e7ce0)',
  'ti-pager-poplist-item-hover-text-color': 'var(--ti-common-color-text-highlight, #526ecc)',
  'ti-pager-poplist-item-hover-bg-color': 'var(--ti-common-color-hover-background, #f2f5fc)',
  'ti-pager-li-item-hover-font-weight': 'var(--ti-common-font-weight-normal)',
  'ti-pager-li-item-hover-text-color': 'var(--ti-common-color-text-highlight, #526ecc)',
  'ti-pager-li-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-pager-poplist-item-padding-horizontal': 'var(--ti-common-space-6, 6px)',
  'ti-pager-input-padding-horizontal': '0',
  'ti-pager-input-width': '40px',
  'ti-pager-min-width': 'auto',
  'ti-pager-height': 'var(--ti-common-size-height-mini, 24px)',
  'ti-pager-normal-text-padding-left': 'calc(var(--ti-common-space-base) * 3 + 2px, 14px)',
  'ti-pager-mini-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-pager-input-padding-vertical': '10px',
  'ti-pager-input-height': 'var(--ti-common-size-height-mini, 24px)',
  'ti-pager-input-border-color': 'var(--ti-common-color-border, #adb0b8)',
  'ti-pager-active-font-weight': 'var(--ti-common-font-weight-normal)',
  'ti-pager-active-bg-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-pager-active-font-color': 'var(--ti-common-color-text-white, #fff)',
  'ti-pager-primary-bg-color': 'var(--ti-common-color-primary-normal, #5e7ce0)'
}
