import ActionSheet from '@opentiny/vue-action-sheet';
import Alert from '@opentiny/vue-alert';
import Avatar from '@opentiny/vue-avatar';
import Badge from '@opentiny/vue-badge';
import Button from '@opentiny/vue-button';
import Checkbox from '@opentiny/vue-checkbox';
import CheckboxGroup from '@opentiny/vue-checkbox-group';
import DatePicker from '@opentiny/vue-date-picker';
import DialogBox from '@opentiny/vue-dialog-box';
import DropdownItem from '@opentiny/vue-dropdown-item';
import DropdownMenu from '@opentiny/vue-dropdown-menu';
import Exception from '@opentiny/vue-exception';
import FileUpload from '@opentiny/vue-file-upload';
import Form from '@opentiny/vue-form';
import FormItem from '@opentiny/vue-form-item';
import Fullscreen from '@opentiny/vue-fullscreen';
import ImageViewer from '@opentiny/vue-image-viewer';
import Input from '@opentiny/vue-input';
import List from '@opentiny/vue-list';
import MiniPicker from '@opentiny/vue-mini-picker';
import NavBar from '@opentiny/vue-nav-bar';
import Numeric from '@opentiny/vue-numeric';
import PickerColumn from '@opentiny/vue-picker-column';
import Popup from '@opentiny/vue-popup';
import Progress from '@opentiny/vue-progress';
import PullRefresh from '@opentiny/vue-pull-refresh';
import Radio from '@opentiny/vue-radio';
import Search from '@opentiny/vue-search';
import Slider from '@opentiny/vue-slider';
import Switch from '@opentiny/vue-switch';
import TabItem from '@opentiny/vue-tab-item';
import Tabbar from '@opentiny/vue-tabbar';
import TabbarItem from '@opentiny/vue-tabbar-item';
import TabbarItemMobile from '@opentiny/vue-tabbar-item/lib/mobile';
import Tabs from '@opentiny/vue-tabs';
import TimeLine from '@opentiny/vue-time-line';
import Upload from '@opentiny/vue-upload';
import UploadList from '@opentiny/vue-upload-list';
export declare const install: (app: any, opts?: {}) => void;
declare const version = "3.0.0";
export { version, ActionSheet, Alert, Avatar, Badge, Button, Checkbox, CheckboxGroup, DatePicker, DialogBox, DropdownItem, DropdownMenu, Exception, FileUpload, Form, FormItem, Fullscreen, ImageViewer, Input, List, MiniPicker, NavBar, Numeric, PickerColumn, Popup, Progress, PullRefresh, Radio, Search, Slider, Switch, TabItem, Tabbar, TabbarItem, TabbarItemMobile, Tabs, TimeLine, Upload, UploadList };
declare const _default: {
    version: string;
    ActionSheet: any;
    Alert: any;
    Avatar: any;
    Badge: any;
    Button: any;
    Checkbox: any;
    CheckboxGroup: any;
    DatePicker: any;
    DialogBox: any;
    DropdownItem: any;
    DropdownMenu: any;
    Exception: any;
    FileUpload: any;
    Form: any;
    FormItem: any;
    Fullscreen: any;
    ImageViewer: any;
    Input: any;
    List: any;
    MiniPicker: any;
    NavBar: any;
    Numeric: any;
    PickerColumn: any;
    Popup: any;
    Progress: any;
    PullRefresh: any;
    Radio: any;
    Search: any;
    Slider: any;
    Switch: any;
    TabItem: any;
    Tabbar: any;
    TabbarItem: any;
    TabbarItemMobile: any;
    Tabs: any;
    TimeLine: any;
    Upload: any;
    UploadList: any;
    install: (app: any, opts?: {}) => void;
};
export default _default;
