// https://github.com/miyuesc/bpmn-js-i18n-zh/tree/main

export default {
  'Select an element to edit its properties.': '选择要编辑其属性的元素。',
  'Multiple elements are selected. Select a single element to edit its properties.':
    '多个元素被选择。选择单个元素以编辑其属性。',

  'General': '通用',
  'Compensation': '补偿',
  'Documentation': '文档',
  'Element documentation': '元素文档',
  'Process documentation': '流程文档',
  'Error': '错误',
  'Message': '消息',
  'Signal': '信号',
  'Link': '链接',
  'Escalation': '升级',
  'Timer': '时间',
  'Completion condition': '完成条件',
  'Loop cardinality': '循环基数',
  'Multi-instance': '多实例',
  'Wait for completion': '结束等待',
  '<none>': '无',
  'Create new ...': '创建...',
  'Activity reference': '活动引用',
  'Global error reference': '全局错误引用',
  'Global escalation reference': '全局升级引用',
  'Global message reference': '全局消息引用',
  'Global signal reference': '全局信号引用',
  'Name': '名称',
  'Participant Name': '协助名称',
  'Process name': '流程名称',
  'Process ID': '流程 ID',
  'Participant ID': '协助 ID',
  'Code': '编码',
  'Executable': '可执行',
  'Date': '日期时间',
  'Duration': '持续时间',
  'Cycle': '循环周期',
  'Type': '类型',
  'Value': '值',
  'Documentation: Timer events': '文档：定时事件',
  'UTC time': 'UTC 时间格式',
  'UTC plus 2 hours zone offset': 'UTC 加 2 小时时区偏移',

  'A specific point in time defined as ISO 8601 combined date and time representation.':
    '定义为 ISO 8601 组合日期和时间表示的特定时间点。',
  'A cycle defined as ISO 8601 repeating intervals format.': '定义为 ISO 8601 重复间隔格式的循环周期。',
  'A time duration defined as ISO 8601 durations format.': '定义为ISO 8601重复间隔格式的持续时间。',
  'every 10 seconds, up to 5 times': '每 10 秒，最多执行 5 次',
  'every day, infinitely': '每天，不停止',
  '15 seconds': '15 秒',
  '1 hour and 30 minutes': '1 小时 30 分钟',
  '14 days': '14 天',

  'ID must not be empty.': 'ID 不能为空。',
  'ID must not contain spaces.': 'ID 不能包含空格。',
  'ID must not contain prefix.': 'ID 不能包含前缀。',
  'ID must be unique.': 'ID 必须唯一。',
  'ID must be a valid QName.': 'ID 必须是有效的 QName。'
}
