export default {
  'tiny-mobile-tabs-text-color': '#333',
  'tiny-mobile-tabs-bg-color': '#fff',
  'tiny-mobile-tabs-font-size': '14px',
  'tiny-mobile-tabs-header-height': '48px',
  'tiny-mobile-tabs-border-color': '#ccc',
  'tiny-mobile-tabs-color-active': '#4a79fe',
  'tiny-mobile-tabs-children-text-color': '#000',
  'tiny-mobile-tabs-children-border-color': '#eee',
  'tiny-mobile-tabs-new-tab-width': '44px',
  'tiny-mobile-tabs-icon-font-size': '24px',
  'tiny-mobile-tabs-icon-color': '#bbb',
  'tiny-mobile-tabs-item-text-color': '#595959',
  'tiny-mobile-tabs-item-text-color-active': '#191919',
  'tiny-mobile-tabs-line-bg-color-active': '#4a79fe',
}
