/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    TinyActionSheet: (typeof import('@opentiny/vue'))['ActionSheet']
    TinyAlert: (typeof import('@opentiny/vue'))['Alert']
    TinyBaseSelect: (typeof import('@opentiny/vue'))['BaseSelect']
    TinyButton: (typeof import('@opentiny/vue'))['Button']
    TinyCascaderSelect: (typeof import('@opentiny/vue'))['CascaderSelect']
    TinyCell: (typeof import('@opentiny/vue'))['Cell']
    TinyCheckbox: (typeof import('@opentiny/vue'))['Checkbox']
    TinyCheckboxGroup: (typeof import('@opentiny/vue'))['CheckboxGroup']
    TinyCol: (typeof import('@opentiny/vue'))['Col']
    TinyCustomSwitch: (typeof import('@opentiny/vue'))['CustomSwitch']
    TinyDialogBox: (typeof import('@opentiny/vue'))['DialogBox']
    TinyDropdown: (typeof import('@opentiny/vue'))['Dropdown']
    TinyDropdownItem: (typeof import('@opentiny/vue'))['DropdownItem']
    TinyDropdownMenu: (typeof import('@opentiny/vue'))['DropdownMenu']
    TinyException: (typeof import('@opentiny/vue'))['Exception']
    TinyFilterBox: (typeof import('@opentiny/vue'))['FilterBox']
    TinyGrid: (typeof import('@opentiny/vue'))['Grid']
    TinyGridColumn: (typeof import('@opentiny/vue'))['GridColumn']
    TinyInput: (typeof import('@opentiny/vue'))['Input']
    TinyLayout: (typeof import('@opentiny/vue'))['Layout']
    TinyModal: (typeof import('@opentiny/vue'))['Modal']
    TinyOption: (typeof import('@opentiny/vue'))['Option']
    TinyOptionGroup: (typeof import('@opentiny/vue'))['OptionGroup']
    TinyPager: (typeof import('@opentiny/vue'))['Pager']
    TinyPopover: (typeof import('@opentiny/vue'))['Popover']
    TinyRadio: (typeof import('@opentiny/vue'))['Radio']
    TinyRadioGroup: (typeof import('@opentiny/vue'))['RadioGroup']
    TinyRecycleScroller: (typeof import('@opentiny/vue'))['RecycleScroller']
    TinyRow: (typeof import('@opentiny/vue'))['Row']
    TinySearch: (typeof import('@opentiny/vue'))['Search']
    TinySelect: (typeof import('@opentiny/vue'))['Select']
    TinySelectedBox: (typeof import('@opentiny/vue'))['SelectedBox']
    TinySplit: (typeof import('@opentiny/vue'))['Split']
    TinyTabItem: (typeof import('@opentiny/vue'))['TabItem']
    TinyTabs: (typeof import('@opentiny/vue'))['Tabs']
    TinyTagGroup: (typeof import('@opentiny/vue'))['TagGroup']
    TinyTimePickerMobile: (typeof import('@opentiny/vue'))['TimePickerMobile']
    TinyTooltip: (typeof import('@opentiny/vue'))['Tooltip']
    TinyTree: (typeof import('@opentiny/vue'))['Tree']
    TinyUserHead: (typeof import('@opentiny/vue'))['UserHead']
  }
}
