export const tinyTransferOldTheme = {
  'ti-transfer-svg-font-size': '14px',
  'ti-transfer-button-height': '30px',
  'ti-transfer-button-width': '30px',
  'ti-transfer-header-padding-right': 'var(--ti-common-space-2x, 8px)',
  'ti-transfer-header-padding-left': 'var(--ti-common-space-2x, 8px)',
  'ti-transfer-panel-item-padding-left': 'var(--ti-common-space-2x, 8px)',
  'ti-transfer-panel-body-list-padding-bottom': 'var(--ti-common-space-6, 6px)',
  'ti-transfer-panel-body-list-padding-top': 'var(--ti-common-space-6, 6px)',
  'ti-transfer-header-border-color': 'var(--ti-common-color-line-normal, #adb0b8)',
  'ti-transfer-header-bg-color': 'var(--ti-common-color-bg-white-emphasize, #f2f5fc)',
  'ti-transfer-header-height': 'var(--ti-common-size-10x, 40px)',
  'ti-transfer-panel-item-hover-bg-color': 'var(--ti-common-color-hover-background, #f2f5fc)',
  'ti-transfer-panel-item-text-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-transfer-panel-item-height': '30px',
  'ti-transfer-panel-border-color': 'var(--ti-common-color-line-normal, #adb0b8)',
  'ti-transfer-button-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-transfer-button-padding-bottom': 'var(--ti-common-space-2x, 8px)',
  'ti-transfer-button-padding-top': 'var(--ti-common-space-2x, 8px)',
  'ti-transfer-button-padding-right': 'var(--ti-common-space-2x, 8px)',
  'ti-transfer-button-padding-left': 'var(--ti-common-space-2x, 8px)',
  'ti-transfer-button-bg-color': 'var(--ti-common-color-bg-emphasize, #5e7ce0)',
  'ti-transfer-font-size': 'var(--ti-common-font-size-1, 14px)'
}
