export const tinyLoadingSmbTheme = {
  'ti-loading-text-color': 'var(--ti-common-color-text-secondary)',
  'ti-loading-text-font-size': 'var(--ti-common-font-size-2)',
  'ti-loading-text-margin-vertical': 'var(--ti-common-space-4x)',
  'ti-loading-spinner-width': '16px',
  'ti-loading-spinner-height': '16px',
  'ti-loading-fullscreen-height': '16px',
  'ti-loading-fullscreen-width': '16px',
  'ti-loading-fullscreen-small-width': '16px',
  'ti-loading-fullscreen-medium-width': '24px',
  'ti-loading-fullscreen-large-width': '32px',
  'ti-loading-fullscreen-small-height': '16px',
  'ti-loading-fullscreen-medium-height': '24px',
  'ti-loading-fullscreen-large-height': '32px',
  'ti-loading-spinner-small-height': '16px',
  'ti-loading-spinner-medium-height': '24px',
  'ti-loading-spinner-large-height': '32px',
  'ti-loading-spinner-small-width': '16px',
  'ti-loading-spinner-medium-width': '24px',
  'ti-loading-spinner-large-width': '32px'
}
