export const tinyDialogBoxAuroraTheme = {
  'ti-dialog-box-head-padding-top': 'var(--ti-common-space-2x)',
  'ti-dialog-box-head-padding-horizontal': 'var(--ti-common-space-6x)',
  'ti-dialog-box-head-padding-bottom': 'var(--ti-common-space-2x)',
  'ti-dialog-box-head-title-font-size': 'var(--ti-common-font-size-1)',
  'ti-dialog-box-head-border-bottom-color': 'var(--ti-common-color-line-normal)',
  'ti-dialog-box-close-icon-size': 'var(--ti-common-font-size-2)',
  'ti-dialog-box-close-icon-color': '#c4c4c4',
  'ti-dialog-box-btn-position-top': 'calc(var(--ti-dialog-box-head-padding-top) + 2px)',
  'ti-dialog-box-btn-position-right': 'var(--ti-dialog-box-head-padding-horizontal)',
  'ti-dialog-box-body-padding-vertical': 'var(--ti-common-space-6x)',
  'ti-dialog-box-body-padding-horizontal': 'var(--ti-common-space-6x)',
  'ti-dialog-box-footer-padding-top': '0',
  'ti-dialog-box-footer-padding-horizontal': '0',
  'ti-dialog-box-footer-margin-bottom': 'var(--ti-common-space-6x)',
  'ti-dialog-box-drawer-min-width': '30%',
  'ti-dialog-box-drawer-footer-text-align': 'center',
  'ti-dialog-box-drawer-padding-left': '0px',
  'ti-dialog-box-drawer-padding-right': '0px',
  'ti-dialog-box-drawer-header-padding-top': 'var(--ti-common-space-2x)',
  'ti-dialog-box-drawer-header-padding-bottom': 'var(--ti-common-space-2x)',
  'ti-dialog-box-drawer-header-padding-left': 'var(--ti-common-space-6x)',
  'ti-dialog-box-drawer-body-padding-right': 'var(--ti-common-space-6x)',
  'ti-dialog-box-wrapper-display': 'flex',
  'ti-dialog-box-wrapper-align-items': 'center'
}
