export const tinyDialogBoxSmbTheme = {
  'ti-dialog-box-drawer-padding-right': 'var(--ti-common-space-8x)',
  'ti-dialog-box-border-radius': 'var(--ti-common-border-radius-4)',
  'ti-dialog-box-shadow': 'var(--ti-common-shadow-4-down)',
  'ti-dialog-box-head-title-font-size': 'var(--ti-common-font-size-4)',
  'ti-dialog-box-head-padding-bottom': 'var(--ti-common-space-6x)',
  'ti-dialog-box-close-icon-size': 'var(--ti-common-font-size-5)',
  'ti-dialog-box-close-icon-color': 'var(--ti-common-color-icon-normal)',
  'ti-dialog-box-close-icon-color-hover': 'var(--ti-common-color-icon-hover)',
  'ti-dialog-box-body-text-color': 'var(--ti-common-color-text-primary)',
  'ti-dialog-box-footer-btn-min-width': 'calc(var(--ti-common-space-base) * 24)',
  'ti-dialog-box-drawer-divider-border-color': 'transparent',
  'ti-dialog-box-footer-margin-bottom': 'var(--ti-common-space-8x)',
  'ti-dialog-box-footer-align': 'right',
  'ti-dialog-box-footer-padding-top': 'var(--ti-common-space-6x)',
  'ti-dialog-box-resize-icon-color': 'var(--ti-common-color-icon-normal)',
  'ti-dialog-box-resize-icon-color-hover': 'var(--ti-common-color-icon-normal)',
  'ti-dialog-box-resize-icon-size': 'var(--ti-common-font-size-2)',
  'ti-dialog-box-btn-tools-position-top': 'var(--ti-common-size-3x)',
  'ti-dialog-box-btn-tools-position-right': 'var(--ti-common-size-3x)'
}
