/**
* Copyright (c) 2022 - present TinyVue Authors.
* Copyright (c) 2022 - present Huawei Cloud Computing Technologies Co., Ltd.
*
* Use of this source code is governed by an MIT-style license.
*
* THE OPEN SOURCE SOFTWARE IN THIS PRODUCT IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
* BUT WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR
* A PARTICULAR PURPOSE. SEE THE APPLICABLE LICENSES FOR MORE DETAILS.
*
*/

export default {
  'tiny-date-picker-width': '280px',
  'tiny-date-picker-font-size': '12px',
  'tiny-date-picker-text-color': '#333',
  'tiny-date-picker-bg-color': '#fff',
  'tiny-date-picker-border-radius': '2px',
  'tiny-date-picker-border-color': '#d9d9d9',
  'tiny-date-picker-hover-bg-color': '#e6f7ff',
  'tiny-date-picker-disabled-text-color': '#999',
  'tiny-date-picker-disabled-bg-color': '#f5f5f5',
  'tiny-date-picker-selected-bg-color': '#f5f5f5',
  'tiny-date-picker-icon-font-size': '14px',
  'tiny-date-picker-current-select-bg-color': '#1890ff',
  'tiny-date-picker-current-border-color': '#1890ff',
  'tiny-date-table-td-border-radius': '15px',
  'tiny-date-table-td-pre-month-text-color': '#999',
  'tiny-date-table-td-nomal-text-color': '#fff',
  'tiny-date-table-td-range-bg-color': '#f2f6fc',
  'tiny-month-table-td-text-bg-color': '#40a9ff',
  'tiny-month-table-td-range-bg-color': '#f2f6fc',
  'tiny-month-table-td-date-text-color': '#fff',
  'tiny-month-table-td-date-border-radius': '24px',
  'tiny-year-table-td-text-color': '#40a9ff',
  'tiny-year-table-td-icon-color': '#303133',
  'tiny-time-spinner-arrow-text-color': '#909399',
  'tiny-time-spinner-arrow-hover-text-color': '#40a9ff',
  'tiny-time-spinner-item-active-text-color': '#303133',
  'tiny-picker-panel-line-height': '30px',
  'tiny-picker-panel-shortcut-font-size': '14px',
  'tiny-picker-panel-icon-color-btn': '#999',
  'tiny-picker-panel-icon-color-btn-hover': '#40a9ff',
  'tiny-picker-panel-icon-color-btn-disabled': '#bfbfbf',
  'tiny-date-picker-header-label-hover-text-color': '#40a9ff',
  'tiny-date-range-picker-header-font-size': '16px',
  'tiny-date-range-picker-time-header-icon-color': '#303133',
  'tiny-time-range-picker-header-font-size': '14px',
  'tiny-time-panel-footer-height': '36px',
  'tiny-time-panel-btn-text-color': '#303133',
  'tiny-time-panel-btn-confirm-text-color': '#40a9ff',
  'tiny-range-separator-text-color': '#303133',

  'tiny-date-picker-current-border-radius': '0',
  'tiny-date-picker-range-bg-color': '#e9edfa',
  'tiny-date-picker-range-hover-bg-color': '#e9edfa',
  'tiny-date-table-td-width': '36px',
  'tiny-date-table-td-height': '34px',
  'tiny-date-table-td-padding-vertical': '4px',
  'tiny-date-table-td-padding-horizontal': '0',
  'tiny-date-table-td-span-width': '36px',
  'tiny-date-table-td-span-height': '24px',
  'tiny-date-table-th-text-color': '#adb0b8',
  'tiny-date-table-td-today-border-color': '#5e7ce0',
  'tiny-date-table-td-today-text-color': '#333',
  'tiny-date-table-week-current-bg-color': '#e9edfa',
  'tiny-date-table-week-current-hover-bg-color': '#beccfa',
  'tiny-time-spinner-item-font-weight': '700',
  'tiny-time-spinner-item-bg-color': 'transparent',
  'tiny-time-spinner-list-border-color': 'transparent',
  'tiny-picker-panel-border-color': 'rgba(0, 0, 0, 0.15)',
  'tiny-picker-panel-box-shadow': '2px 3px 7px rgba(0, 0, 0, 0.15)',
  'tiny-time-panel-border-color': '#d9d9d9',
  'tiny-time-panel-box-shadow': '0 2px 12px 0 rgba(0, 0, 0, 0.1)',
  'tiny-time-panel-btn-bg-color': 'transparent',
  'tiny-time-panel-btn-padding-vertical': '0',
  'tiny-time-panel-btn-padding-horizontal': '5px',
  'tiny-time-panel-btn-border-radius': '2px',
  'tiny-time-panel-btn-height': '28px',
  'tiny-time-panel-btn-min-width': 'inherit',
  'tiny-time-panel-btn-font-weight': '800',
  'tiny-time-panel-btn-confirm-hover-bg-color': 'transparent',
  'tiny-date-editor-input-icon-color-fill': '#575d6c'
}
