import { test, expect } from '@playwright/test'

test('基础用法', async ({ page }) => {
  page.on('pageerror', (exception) => expect(exception).toBeNull())
  await page.goto('carousel#basic-usage')
  const preview = page.locator('#basic-usage')
  const carouselItems = preview.locator('div.tiny-carousel__item')
  await page.locator('div').filter({ hasText: /^1$/ }).click()
  await preview.locator('.tiny-carousel__container > button:nth-child(2)').click()
  await preview.locator('.tiny-carousel__container > button:nth-child(2)').click()
  await preview.locator('.tiny-carousel__container > button:nth-child(2)').click()
  await preview.locator('.tiny-carousel__container > button:nth-child(2)').click()
  await expect(carouselItems.first()).toHaveCSS('transform', 'matrix(1, 0, 0, 1, -704, 0)')
  await preview.locator('.tiny-carousel__arrow').first().click()
  await preview.locator('.tiny-carousel__arrow').first().click()
  await preview.locator('.tiny-carousel__arrow').first().click()
  await preview.locator('.tiny-carousel__arrow').first().click()
  await preview.getByRole('list').getByRole('button').nth(1).click()
  await preview.getByRole('list').getByRole('button').nth(2).click()
  await preview.getByRole('list').getByRole('button').nth(3).click()
  await expect(carouselItems.first()).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 704, 0)')
})
