export const tinyPopeditorOldTheme = {
  'ti-popeditor-tree-input-sufffix-visibility': 'visible',
  'ti-popeditor-tree-input-prefix-visibility': 'hidden',
  'ti-popeditor-tree-input-padding-right': 'calc(var(--ti-common-space-8x, 32px) - 4px)',
  'ti-popeditor-tree-input-padding-left': 'var(--ti-common-space-2x, 8px)',
  'ti-popeditor-search-footer-text-align': 'center',
  'ti-popeditor-search-item-padding-left': 'var(--ti-common-space-0, 0px)',
  'ti-popeditor-search-item-padding-right': 'var(--ti-common-space-0, 0px)',
  'ti-popeditor-search-item-text-align': 'right',
  'ti-popeditor-search-item-width': '160px',
  'ti-popeditor-footer-padding-top': 'var(--ti-common-space-7x, 28px)',
  'ti-popeditor-footer-text-align': 'center',
  'ti-popeditor-pager-padding-top': 'var(--ti-common-space-6x, 24px)',
  'ti-popeditor-tabs-header-padding-horizontal': 'var(--ti-common-space-10, 10px)',
  'ti-popeditor-tabs-body-item-padding-horizontal': 'var(--ti-common-space-3x, 12px)',
  'ti-popeditor-tabs-body-item-padding-top': 'var(--ti-common-space-3x, 12px)',
  'ti-popeditor-tabs-body-right-padding-left': 'var(--ti-common-space-base, 4px)',
  'ti-popeditor-tabs-body-right-padding-bottom': 'var(--ti-common-space-0, 0px)',
  'ti-popeditor-tabs-body-right-padding-right': 'var(--ti-common-space-base, 4px)',
  'ti-popeditor-tabs-body-right-padding-top': 'var(--ti-common-space-0, 0px)',
  'ti-popeditor-tabs-body-left-padding-left': 'var(--ti-common-space-base, 4px)',
  'ti-popeditor-tabs-body-left-padding-bottom': 'var(--ti-common-space-0, 0px)',
  'ti-popeditor-tabs-body-left-padding-right': 'var(--ti-common-space-base, 4px)',
  'ti-popeditor-tabs-body-left-padding-top': 'var(--ti-common-space-0, 0px)',
  'ti-popeditor-tabs-li-margin-right': 'var(--ti-common-space-0, 0px)',
  'ti-popeditor-tabs-li-padding-horizontal': 'var(--ti-common-space-5x, 20px)',
  'ti-popeditor-search-footer-margin-bottom': 'var(--ti-common-space-3x, 12px)',
  'ti-popeditor-search-footer-margin-top': 'var(--ti-common-space-3x, 12px)',
  'ti-popeditor-search-item-margin-bottom': 'var(--ti-common-space-3x, 12px)',
  'ti-popeditor-tabs-font-size': 'var(--ti-common-font-size-1)',
  'ti-popeditor-tabs-li-line-height': 'var(--ti-common-size-10x, 40px)',
  'ti-popeditor-tabs-li-height': 'var(--ti-common-size-10x, 40px)',
  'ti-popeditor-border-color': 'var(--ti-common-color-border, #adb0b8)'
}
