export const tinyPopeditorSmbTheme = {
  'ti-popeditor-pager-padding-top': 'var(--ti-common-space-3x)',
  'ti-popeditor-tabs-body-item-padding-top': 'var(--ti-common-space-4x)',
  'ti-popeditor-footer-text-align': 'right',
  'ti-popeditor-footer-padding-top': 'var(--ti-common-space-6x)',
  'ti-popeditor-tabs-li-padding-horizontal': 'var(--ti-common-space-0)',
  'ti-popeditor-border-color': 'var(--ti-common-border-color-transparent-8)',
  'ti-popeditor-tabs-header-padding-horizontal': 'var(--ti-common-space-0)',
  'ti-popeditor-tabs-body-item-padding-horizontal': 'var(--ti-common-space-0)',
  'ti-popeditor-search-item-width': '80px',
  'ti-popeditor-search-item-text-align': 'left',
  'ti-popeditor-search-item-padding-right': 'var(--ti-common-space-4x)',
  'ti-popeditor-search-item-padding-left': 'var(--ti-common-space-4x)',
  'ti-popeditor-search-footer-text-align': 'right',
  'ti-popeditor-search-item-margin-bottom': 'var(--ti-common-space-6x)',
  'ti-popeditor-search-footer-margin-top': 'var(--ti-common-space-0)',
  'ti-popeditor-search-footer-margin-bottom': 'var(--ti-common-space-6x)',
  'ti-popeditor-tabs-li-height': 'calc(var(--ti-common-size-8x) + 2px)',
  'ti-popeditor-tabs-li-line-height': 'var(--ti-common-line-height-2)',
  'ti-popeditor-tabs-li-margin-right': 'var(--ti-common-space-8x)',
  'ti-popeditor-tabs-font-size': 'var(--ti-common-font-size-2)',
  'ti-popeditor-tabs-body-left-padding-top': 'var(--ti-common-space-0)',
  'ti-popeditor-tabs-body-left-padding-right': 'var(--ti-common-space-4x)',
  'ti-popeditor-tabs-body-left-padding-bottom': 'var(--ti-common-space-0)',
  'ti-popeditor-tabs-body-left-padding-left': 'var(--ti-common-space-0)',
  'ti-popeditor-tabs-body-right-padding-top': 'var(--ti-common-space-0)',
  'ti-popeditor-tabs-body-right-padding-right': 'var(--ti-common-space-0)',
  'ti-popeditor-tabs-body-right-padding-bottom': 'var(--ti-common-space-0)',
  'ti-popeditor-tabs-body-right-padding-left': 'var(--ti-common-space-4x)',
  'ti-popeditor-tree-input-padding-left': 'calc(var(--ti-common-space-8x, 32px) - 4px)',
  'ti-popeditor-tree-input-padding-right': 'var(--ti-common-space-2x, 8px)',
  'ti-popeditor-tree-input-prefix-visibility': 'visible',
  'ti-popeditor-tree-input-sufffix-visibility': 'hidden'
}
