export const tinyGuideAuroraTheme = {
  'ti-guide-title-text-color': '#333d48',
  'ti-guide-title-line-height': '20px',
  'ti-guide-cancel-icon-font-size': '30px',
  'ti-guide-cancel-icon-font-weight': '300',
  'ti-guide-cancel-icon-color': '#333d48',
  'ti-guide-cancel-icon-font-weight': '300',
  'ti-guide-cancel-hover-icon-color': 'rgba(0, 0, 0, 0.75)',
  'ti-guide-text-text-color': '#333d48',
  'ti-guide-text-line-height': '20px',
  'ti-guide-text-font-size': '14px',
  'ti-guide-text-padding-top': '24px',
  'ti-guide-text-padding-horizontal': '24px',
  'ti-guide-text-scrollbar-width': '4px',
  'ti-guide-text-scrollbar-height': '40px',
  'ti-guide-text-scrollbar-border-radius': '2px',
  'ti-guide-text-scrollbar-border-color': 'rgba(57, 57, 57, 0.3)',
  'ti-guide-footer-border-bottom-left-radius': '4px',
  'ti-guide-footer-border-bottom-right-radius': '4px',
  'ti-guide-footer-padding-left': '24px',
  'ti-guide-footer-padding-right': '24px',
  'ti-guide-footer-padding-bottom': '24px',
  'ti-guide-button-border-radius': '4px',
  'ti-guide-progresss-text-color': '#161e26',
  'ti-guide-button-bg-color': '#0067d1',
  'ti-guide-button-hover-bg-color': '#0072e8',
  'ti-guide-button-focus-bg-color': '#0067d1',
  'ti-guide-button-active-bg-color': '#005bba',
  'ti-guide-button-disable-bg-color': 'rgba(0, 103, 209, 0.3)',
  'ti-guide-button-disable-text-color': '#fff',
  'ti-guide-button-secondary-text-color': '#161e26',
  'ti-guide-button-secondary-border-color': 'rgba(22, 30, 38, 0.2)',
  'ti-guide-button-secondary-hover-border-color': '#161e26',
  'ti-guide-button-secondary-hover-bg-color': '#161e26',
  'ti-guide-button-secondary-active-bg-color': '#005bba',
  'ti-guide-button-secondary-focus-bg-color': '#161e26',
  'ti-guide-button-secondary-disabled-bg-color': 'rgba(22, 30, 38, 0.05)',
  'ti-guide-button-secondary-disabled-text-color': 'rgba(22, 30, 38, 0.3)',
  'ti-guide-button-secondary-disabled-border-color': 'rgba(22, 30, 38, 0.1)'
}
