export const tinyGuideOldTheme = {
  'ti-guide-progresss-text-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'ti-guide-button-height': 'var(--ti-common-size-height-normal, 32px)',
  'ti-guide-button-width': 'calc(var(--ti-common-line-height-6, 48px) * 2)',
  'ti-guide-button-active-bg-color': 'var(--ti-common-color-primary-active, #7693f5)',
  'ti-guide-button-focus-bg-color': 'var(--ti-common-color-primary-active, #7693f5)',
  'ti-guide-button-hover-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-guide-button-hover-bg-color': 'var(--ti-common-color-primary-hover, #7693f5)',
  'ti-guide-button-bg-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-guide-button-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-guide-button-border': 'var(--ti-common-color-text-white, #fff)',
  'ti-guide-button-text-color': 'var(--ti-common-color-text-white, #fff)',
  'ti-guide-footer-padding-bottom': 'var(--ti-common-space-6x, 24px)',
  'ti-guide-footer-padding-right': 'var(--ti-common-space-6x, 24px)',
  'ti-guide-footer-padding-left': 'var(--ti-common-space-6x, 24px)',
  'ti-guide-footer-border-bottom-left-radius': 'var(--ti-common-border-radius-1, 4px)',
  'ti-guide-footer-border-bottom-right-radius': 'var(--ti-common-border-radius-1, 4px)',
  'ti-guide-text-padding-bottom': 'calc(var(--ti-common-space-base, 4px) * 5.5)',
  'ti-guide-text-padding-horizontal': 'var(--ti-common-space-6x, 24px)',
  'ti-guide-text-padding-top': 'var(--ti-common-space-6x, 24px)',
  'ti-guide-text-line-height': 'var(--ti-common-line-height-4, 20px)',
  'ti-guide-text-text-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'ti-guide-progress-style-left': 'var(--ti-common-space-6x, 24px)',
  'ti-guide-cancel-icon-margin-right': 'var(--ti-common-space-0, 0px)',
  'ti-guide-cancel-icon-margin-top': '-6px',
  'ti-guide-title-text-font-size': 'var(--ti-common-font-size-3, 18px)',
  'ti-guide-title-line-height': 'var(--ti-common-line-height-6, 32px)',
  'ti-guide-header-padding-top': 'var(--ti-common-space-6x, 24px)',
  'ti-guide-header-padding-right': 'var(--ti-common-space-6x, 24px)',
  'ti-guide-header-padding-left': 'var(--ti-common-space-6x, 24px)',
  'ti-guide-header-border-top-right-radius': 'var(--ti-common-border-radius-1, 4px)',
  'ti-guide-header-border-top-left-radius': 'var(--ti-common-border-radius-1, 4px)'
}
