export const tinyGuideSmbTheme = {
  'ti-guide-header-padding-top': 'var(--ti-common-space-4x)',
  'ti-guide-header-padding-left': 'var(--ti-common-space-4x)',
  'ti-guide-header-padding-right': 'var(--ti-common-space-4x)',
  'ti-guide-footer-padding-left': 'var(--ti-common-space-4x)',
  'ti-guide-footer-padding-right': 'var(--ti-common-space-4x)',
  'ti-guide-footer-padding-bottom': 'var(--ti-common-space-4x)',
  'ti-guide-text-padding-horizontal': 'var(--ti-common-space-4x)',
  'ti-guide-text-padding-bottom': 'var(--ti-common-space-6x)',
  'ti-guide-text-padding-top': 'var(--ti-common-space-2x)',
  'ti-guide-button-width': 'calc(var(--ti-common-line-height-8) + 8px)',
  'ti-guide-button-height': 'var(--ti-common-line-height-2)',
  'ti-guide-progress-style-left': 'var(--ti-common-space-4x)',
  'ti-guide-title-text-font-size': 'var(--ti-common-font-size-2)',
  'ti-guide-title-line-height': 'var(--ti-common-line-height-2)',
  'ti-guide-text-line-height': 'var(--ti-common-line-height-2)',
  'ti-guide-button-bg-color': 'var(--ti-base-color-bg-5)',
  'ti-guide-button-text-color': '#191919',
  'ti-guide-button-hover-bg-color': 'var(--ti-base-color-bg-5)',
  'ti-guide-button-active-bg-color': 'var(--ti-base-color-bg-5)',
  'ti-guide-button-focus-bg-color': 'var(--ti-base-color-bg-5)',
  'ti-guide-button-hover-border-color': '#191919',
  'ti-guide-button-border': '#c2c2c2',
  'ti-guide-cancel-icon-margin-top': 'calc(var(--ti-common-space-base) * (-3))',
  'ti-guide-cancel-icon-margin-right': 'var(--ti-common-space-0)',
  'ti-guide-button-border-radius': 'var(--ti-common-size-25x)'
}
