export const tinyGuideSmbTheme = {
  'ti-guide-header-padding-top': 'var(--ti-common-space-6x)',
  'ti-guide-header-padding-left': 'var(--ti-common-space-6x)',
  'ti-guide-header-padding-right': 'var(--ti-common-space-6x)',
  'ti-guide-footer-padding-left': 'var(--ti-common-space-6x)',
  'ti-guide-footer-padding-right': 'var(--ti-common-space-6x)',
  'ti-guide-footer-padding-bottom': 'var(--ti-common-space-6x)',
  'ti-guide-text-padding-horizontal': 'var(--ti-common-space-6x)',
  'ti-guide-text-padding-bottom': 'var(--ti-common-space-6x)',
  'ti-guide-text-padding-top': 'var(--ti-common-space-2x)',
  'ti-guide-button-width': 'calc(var(--ti-common-line-height-8) + 8px)',
  'ti-guide-button-height': 'var(--ti-common-line-height-2)',
  'ti-guide-progress-style-left': 'var(--ti-common-space-6x)',
  'ti-guide-title-text-font-size': 'var(--ti-common-font-size-2)',
  'ti-guide-title-line-height': 'var(--ti-common-line-height-2)',
  'ti-guide-text-line-height': 'var(--ti-common-line-height-2)',
  'ti-guide-button-bg-color': 'var(--ti-common-color-light)',
  'ti-guide-button-text-color': '#191919',
  'ti-guide-button-hover-bg-color': 'var(--ti-common-color-light)',
  'ti-guide-button-active-bg-color': 'var(--ti-common-color-light)',
  'ti-guide-button-focus-bg-color': 'var(--ti-common-color-light)',
  'ti-guide-button-hover-border-color': '#C2C2C2',
  'ti-guide-button-border': '#595959',
  'ti-guide-text-text-color': '#595959',
  'ti-guide-progresss-text-color': '#808080',
  'ti-guide-cancel-icon-margin-top': 'calc(var(--ti-common-space-base) * (-6))',
  'ti-guide-cancel-icon-margin-right': 'calc(var(--ti-common-space-base) * (-2))',
  'ti-guide-header-border-top-left-radius': 'var(--ti-common-border-radius-4)',
  'ti-guide-header-border-top-right-radius': 'var(--ti-common-border-radius-4)',
  'ti-guide-footer-border-bottom-right-radius': 'var(--ti-common-border-radius-4)',
  'ti-guide-footer-border-bottom-left-radius': 'var(--ti-common-border-radius-4)',
  'ti-guide-button-border-radius': 'var(--ti-common-size-25x)'
}
