import { expect, test } from '@playwright/test'

test('nest-remote-method', async ({ page }) => {
  await page.goto('select#nest-remote-grid')
  const input = page.locator('#preview .tiny-input__inner').first()
  const suffixSvg = page.locator('.tiny-input__suffix .tiny-select__caret').first()

  await expect(suffixSvg).toBeHidden()
  const dropdown = page.locator('.grid-remote')
  await expect(dropdown).toBeHidden()
  await input.focus()
  await input.fill(' ')
  await input.press('Enter')
  await page.waitForTimeout(1000)
  await expect(dropdown).toBeVisible()
  await expect(dropdown.locator('.tiny-grid__body tbody')).toBeEmpty()
  await input.fill('')
  await input.press('Enter')
  await page.waitForTimeout(1000)
  await expect(dropdown.locator('.tiny-grid__body tbody')).not.toBeEmpty()
  await page.getByRole('row', { name: '5100000' }).locator('div').first().click()
  await expect(input).toHaveValue('5100000')
  await input.click()
  await expect(page.getByRole('row', { name: '5100000' })).toHaveClass(/row__current/)
  await page.getByRole('row', { name: '5900003' }).locator('div').first().click()
  await expect(input).toHaveValue('5900003')
  await input.click()
  await expect(page.getByRole('row', { name: '5900003' })).toHaveClass(/row__current/)
})

test('nest-remote-config', async ({ page }) => {
  await page.goto('select#nest-remote-grid')
  const input = page.locator('#preview .tiny-input__inner').nth(1)
  const suffixSvg = page.locator('.tiny-input__suffix .tiny-select__caret').nth(1)

  await expect(suffixSvg).toBeVisible()
  const dropdown = page.locator('.grid-remote-config')
  await expect(dropdown).toBeHidden()
  await input.click()
  await page.waitForTimeout(1000)
  await expect(dropdown).toBeVisible()
  await expect(dropdown.locator('.tiny-grid__body tbody')).not.toBeEmpty()
  await page.getByRole('row', { name: '5100000' }).getByRole('cell').first().click()
  await expect(input).toHaveValue('5100000')
  await input.click()
  await expect(page.getByRole('row', { name: '5100000' })).toHaveClass(/row__current/)
  await page.getByRole('row', { name: '5900003' }).getByRole('cell').first().click()
  await expect(input).toHaveValue('5900003')
  await input.click()
  await expect(page.getByRole('row', { name: '5900003' })).toHaveClass(/row__current/)
  await input.fill(' ')
  await input.press('Enter')
  await page.waitForTimeout(1000)
  await expect(dropdown).toBeVisible()
  await expect(dropdown.locator('.tiny-grid__body tbody')).toBeEmpty()
})
