import { expect, test } from '@playwright/test'

test('grid-much-data', async ({ page }) => {
  await page.goto('select#nest-radio-grid-much-data')
  const input = page.locator('#preview .tiny-input__inner')
  const suffixSvg = await page.locator('#preview .tiny-select__caret').first()

  await expect(suffixSvg).toHaveCount(1)
  await expect(suffixSvg).toBeVisible()
  const dropdown = page.locator('.tiny-select-dropdown')
  await expect(dropdown).toBeHidden()
  await input.click()
  await page.waitForTimeout(1000)
  await expect(dropdown).toBeVisible()
  await expect(dropdown.locator('.tiny-grid__body tbody')).not.toBeEmpty()
  await page.getByRole('row', { name: '华南区0 广东省 广州市' }).getByRole('cell').first().click()
  await expect(input).toHaveValue('广州市')
  await input.click()
  await page.waitForTimeout(1000)
  await expect(dropdown.locator('.tiny-grid-body__row').first()).toHaveClass(/row__current/)
  await expect((await dropdown.locator('.tiny-grid-body__row').all()).length).toEqual(7)
  await expect(page.getByRole('row', { name: '华南区12 广东省 广州市' })).not.toBeInViewport()
  await dropdown.locator('.tiny-grid-body__row').nth(6).scrollIntoViewIfNeeded()
  await expect((await dropdown.locator('.tiny-grid-body__row').all()).length).toEqual(7)
  await page.waitForTimeout(1000)
  await dropdown.locator('.tiny-grid-body__row').nth(6).scrollIntoViewIfNeeded()
  await expect((await dropdown.locator('.tiny-grid-body__row').all()).length).toEqual(7)
  await page.waitForTimeout(1000)
  await page.getByRole('row', { name: '华南区12 广东省 广州市' }).getByRole('cell').first().click()
})
