import { expect, test } from '@playwright/test'

test('remote-method', async ({ page }) => {
  await page.goto('select#nest-grid-remote-filter')
  const input = page.getByRole('textbox').nth(1)
  const suffixSvg = page.locator('.tiny-input__suffix .tiny-select__caret').first()

  await expect(suffixSvg).toBeHidden()
  const dropdown = page.locator('.grid-remote')
  await expect(dropdown).toBeHidden()
  await input.fill(' ')
  await input.press('Enter')
  await page.waitForTimeout(1000)
  await expect(dropdown).toBeVisible()
  await expect(dropdown.locator('.tiny-grid__body tbody')).toBeEmpty()
  await input.fill('')
  await input.press('Enter')
  await page.waitForTimeout(1000)
  await expect(dropdown.locator('.tiny-grid__body tbody')).not.toBeEmpty()
  await page.getByRole('row', { name: '华南区0 广东省0 广州市0' }).getByRole('cell').first().click()
  const tags = page.locator('.tiny-select .tiny-tag')
  await expect((await tags.all()).length).toEqual(1)
  await expect(tags.first()).toContainText(/广州市0/)
  await page.getByRole('row', { name: '华南区1 广东省1 广州市1' }).getByRole('cell').first().click()
  await expect((await tags.all()).length).toEqual(2)
  await expect(tags.first()).toContainText(/广州市0/)
  await expect(tags.nth(1)).toContainText(/广州市1/)
})

test('remote-config', async ({ page }) => {
  await page.goto('select#nest-grid-remote-filter')
  const input = page.getByRole('textbox').nth(3)
  const suffixSvg = page.locator('.tiny-input__suffix .tiny-select__caret').nth(1)

  await expect(suffixSvg).toBeVisible()
  const dropdown = page.locator('.grid-remote-config')
  await expect(dropdown).toBeHidden()
  await input.click()
  await page.waitForTimeout(1000)
  await expect(dropdown).toBeVisible()
  await expect(dropdown.locator('.tiny-grid__body tbody')).not.toBeEmpty()
  await page.getByRole('row', { name: '华南区0 广东省0 广州市0' }).getByRole('cell').first().click()
  const tags = page.locator('.tiny-select .tiny-tag')
  await expect((await tags.all()).length).toEqual(1)
  await expect(tags.first()).toContainText(/广州市0/)
  await page.getByRole('row', { name: '华南区1 广东省1 广州市1' }).getByRole('cell').first().click()
  await expect((await tags.all()).length).toEqual(2)
  await expect(tags.first()).toContainText(/广州市0/)
  await expect(tags.nth(1)).toContainText(/广州市1/)
  await tags.nth(0).locator('.tiny-svg').click()
  await tags.nth(0).locator('.tiny-svg').click()
  await expect((await tags.all()).length).toEqual(0)
  await input.fill(' ')
  await input.press('Enter')
  await page.waitForTimeout(1000)
  await expect(dropdown).toBeVisible()
  await expect(dropdown.locator('.tiny-grid__body tbody')).toBeEmpty()
})
