import { test, expect } from '@playwright/test'

test('radio-optimization', async ({ page }) => {
  await page.goto('select#optimization')
  const select = page.locator('#preview .tiny-select').first()
  const input = page.locator('#preview .tiny-input__inner').first()

  await select.click()
  await page.waitForTimeout(1000)
  const options = page.locator('.tiny-select-dropdown__list').getByRole('listitem')
  await page.waitForTimeout(1000)
  await expect((await options.all()).length).toEqual(10)
  await expect(options.filter({ hasText: '黄金糕17' })).not.toBeInViewport()
  await options.nth(9).scrollIntoViewIfNeeded()
  await page.waitForTimeout(1000)
  await options.nth(9).scrollIntoViewIfNeeded()
  await expect(options.filter({ hasText: '黄金糕17' })).toBeInViewport()
  await options.filter({ hasText: '黄金糕17' }).click()
  await expect(input).toHaveValue('黄金糕17')
})

test('select-optimization', async ({ page }) => {
  await page.goto('select#optimization')
  const select = page.locator('#preview .tiny-select').nth(1)
  const tags = page.locator('#preview .tiny-select .tiny-tag')

  await select.click()
  await page.waitForTimeout(1000)
  const options = page.locator('.tiny-select-dropdown__list').getByRole('listitem')
  await expect((await options.all()).length).toEqual(10)
  await expect(options.filter({ hasText: '黄金糕17' })).not.toBeInViewport()
  await expect(options.filter({ hasText: '黄金糕16' })).not.toBeInViewport()
  await options.nth(9).scrollIntoViewIfNeeded()
  await page.waitForTimeout(1000)
  await options.nth(9).scrollIntoViewIfNeeded()
  await expect(options.filter({ hasText: '黄金糕16' })).toBeInViewport()
  await expect(options.filter({ hasText: '黄金糕17' })).toBeInViewport()
  await options.filter({ hasText: '黄金糕17' }).click()
  await expect(tags.first()).toHaveText('黄金糕17')
  await expect((await tags.all()).length).toEqual(1)
  await options.filter({ hasText: '黄金糕16' }).click()
  await expect((await tags.all()).length).toEqual(2)
  await expect(tags.nth(1)).toHaveText('+ 1')
})
