import { test, expect } from '@playwright/test'

test('search-allow-copy', async ({ page }) => {
  await page.goto('select#search-allow-copy')
  const input = page.locator('#preview .tiny-input__inner')
  const options = page.locator('.tiny-select-dropdown').locator('.tiny-option')

  await input.click()
  await input.fill('双皮')
  await input.press('Enter')
  await page.waitForTimeout(1000)
  await page.mouse.move(340, 356)
  await page.waitForTimeout(1000)
  await page.mouse.down()
  await page.waitForTimeout(1000)
  await page.mouse.move(278, 356)
  await page.waitForTimeout(200)
  await page.mouse.up()
  await page.keyboard.press('Control+C')
  const valueInput = page.locator('.custom')
  await expect(valueInput).toHaveValue('')
  await valueInput.focus()
  await page.keyboard.press('Control+V')
  await page.waitForTimeout(200)
  await expect(valueInput).toHaveValue('双皮')
})
