export const tinyStepsOldTheme = {
  'ti-steps-timeline-dot-primary-bg-color': 'var(--ti-steps-timeline-dot-bg-color)',
  'ti-steps-timeline-item-secondary-text-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-steps-timeline-item-padding-bottom': 'var(--ti-common-size-5x, 20px)',
  'ti-steps-timeline-dot-bg-color': 'var(--ti-common-color-line-dividing, #dfe1e6)',
  'ti-steps-timeline-dot-border-color': 'var(--ti-common-color-line-dividing, #dfe1e6)',
  'ti-steps-timeline-shape-dot-content-margin-left': 'var(--ti-common-size-3x, 12px)',
  'ti-steps-timeline-vertical-line-margin-left': 'var(--ti-common-size-3x, 12px)',
  'ti-steps-timeline-line-margin-vertical': 'var(--ti-common-size-base, 4px)',
  'ti-steps-timeline-date-time-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-steps-advanced-count-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-steps-advanced-count-bg-color': 'var(--ti-common-bg-primary, #c7000b)',
  'ti-steps-advanced-link-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-steps-advanced-li-text-color': 'var(--ti-common-color-selected-text-color, #fff)',
  'ti-steps-mini-font-size-base': 'var(--ti-common-font-size-base, 12px)',
  'ti-steps-mini-number-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-steps-disabled-select-icon-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-steps-disabled-select-icon-bg-color': 'var(--ti-common-color-bg-white-normal, #fff)',
  'ti-steps-disabled-name-text-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-steps-disabled-border-color': 'var(--ti-steps-disabled-icon-color)',
  'ti-steps-disabled-icon-bg-color': 'var(--ti-common-color-bg-disabled, #f5f5f6)',
  'ti-steps-error-icon-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-steps-timeline-date-time-text-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'ti-steps-unselected-border-color': 'var(--ti-steps-unselected-icon-color)',
  'ti-steps-doing-line-border-color': 'var(--ti-common-color-bg-secondary, #adb0b8)',
  'ti-steps-line-bg-color': 'var(--ti-common-color-bg-secondary, #adb0b8)',
  'ti-steps-done-icon-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-steps-done-icon-color': 'var(--ti-common-color-icon-active, #5e7ce0)',
  'ti-steps-line-active-bg-color': 'var(--ti-common-color-line-active, #5e7ce0)',
  'ti-steps-done-text-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'ti-steps-advanced-desc-active-text-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-steps-active-font-weight': 'var(--ti-common-font-weight-4, normal)',
  'ti-steps-custom-icon-width-height': 'var(--ti-common-space-6x, 24px)',
  'ti-steps-vertical-title-margin-top': 'var(--ti-common-space-3x, 12px)',
  'ti-steps-description-text-color': 'var(--ti-common-color-text-secondary, #575d6c)',
  'ti-steps-bottom-divider-margin-top': 'var(--ti-common-space-4x, 16px)',
  'ti-steps-content-margin-top': 'var(--ti-common-space-6, 6px)',
  'ti-steps-text-margin-left': 'var(--ti-common-space-base, 4px)',
  'ti-steps-icon-hover-text-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-steps-icon-size': 'var(--ti-common-size-5x, 20px)',
  'ti-steps-text-color-hover': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-steps-font-size-hover': 'var(--ti-common-font-weight-4, normal)',
  'ti-steps-circle-width-height': 'var(--ti-common-size-5x, 20px)'
}
