export const tinyStepsOldTheme = {
  'tv-Steps-timeline-dot-primary-bg-color': 'var(--tv-Steps-timeline-dot-bg-color)',
  'tv-Steps-timeline-item-secondary-text-font-size': 'var(--ti-common-font-size-base, 12px)',
  'tv-Steps-timeline-item-padding-bottom': 'var(--ti-common-size-5x, 20px)',
  'tv-Steps-timeline-dot-bg-color': 'var(--ti-common-color-line-dividing, #dfe1e6)',
  'tv-Steps-timeline-dot-border-color': 'var(--ti-common-color-line-dividing, #dfe1e6)',
  'tv-Steps-timeline-shape-dot-content-margin-left': 'var(--ti-common-size-3x, 12px)',
  'tv-Steps-timeline-vertical-line-margin-left': 'var(--ti-common-size-3x, 12px)',
  'tv-Steps-timeline-line-margin-vertical': 'var(--ti-common-size-base, 4px)',
  'tv-Steps-advance-count-font-size': 'var(--ti-common-font-size-base, 12px)',
  'tv-Steps-advance-count-bg-color': 'var(--ti-common-bg-primary, #c7000b)',
  'tv-Steps-advance-link-font-size': 'var(--ti-common-font-size-base, 12px)',
  'tv-Steps-advance-li-text-color': 'var(--ti-common-color-selected-text-color, #fff)',
  'tv-Steps-mini-font-size-base': 'var(--ti-common-font-size-base, 12px)',
  'tv-Steps-mini-number-font-size': 'var(--ti-common-font-size-base, 12px)',
  'tv-Steps-line-number-active-text-color-disabled': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'tv-Steps-line-number-active-bg-color-disabled': 'var(--ti-common-color-bg-white-normal, #fff)',
  'tv-Steps-line-title-text-color-disabled': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'tv-Steps-disabled-border-color': 'var(--tv-Steps-disabled-icon-color)',
  'tv-Steps-disabled-icon-bg-color': 'var(--ti-common-color-bg-disabled, #f5f5f6)',
  'tv-Steps-error-icon-size': 'var(--ti-common-font-size-1, 14px)',
  'tv-Steps-timeline-date-time-text-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'tv-Steps-node-border-color': 'var(--tv-Steps-unselected-icon-color)',
  'tv-Steps-line-doing-border-color': 'var(--ti-common-color-bg-secondary, #adb0b8)',
  'tv-Steps-line-bg-color': 'var(--ti-common-color-bg-secondary, #adb0b8)',
  'tv-Steps-done-icon-size': 'var(--ti-common-font-size-1, 14px)',
  'tv-Steps-done-icon-color': 'var(--ti-common-color-icon-active, #5e7ce0)',
  'tv-Steps-line-active-bg-color': 'var(--ti-common-color-line-active, #5e7ce0)',
  'tv-Steps-done-text-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'tv-Steps-line-desc-text-color-active': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'tv-Steps-active-font-weight': 'var(--ti-common-font-weight-4, normal)',
  'tv-Steps-custom-icon-size': 'var(--ti-common-space-6x, 24px)',
  'tv-Steps-line-vertical-title-margin-top': 'var(--ti-common-space-3x, 12px)',
  'tv-Steps-node-desc-text-color': 'var(--ti-common-color-text-secondary, #575d6c)',
  'tv-Steps-bottom-divider-margin-top': 'var(--ti-common-space-4x, 16px)',
  'tv-Steps-content-margin-top': 'var(--ti-common-space-6, 6px)',
  'tv-Steps-text-margin-left': 'var(--ti-common-space-base, 4px)',
  'tv-Steps-line-number-text-color-hover': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'tv-Steps-icon-size': 'var(--ti-common-size-5x, 20px)',
  'tv-Steps-node-title-text-color-hover': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'tv-Steps-content-font-weight-hover': 'var(--ti-common-font-weight-4, normal)',
  'tv-Steps-node-circle-size': 'var(--ti-common-size-5x, 20px)'
}
