export const tinyCascaderNodeSmbTheme = {
  'ti-cascader-node-label-padding-horizontal': '0px',
  'ti-cascader-node-postfix-right': '16px',
  'ti-cascader-node-disabled-bg-color': '#fff',
  'ti-cascader-node-disabled-icon-color': '#c2c2c2',
  'ti-cascader-node-label-max-width': '126px',
  'ti-cascader-node-selectable-active-bg-color': '#fff',
  'ti-cascader-node-active-font-weight': 'bold',
  'ti-cascader-node-hover-text-color': '#191919',
  'ti-cascader-node-prefix-display': 'none',
  'ti-cascader-node-icon-color': '#191919',
  'ti-cascader-node-icon-font-size': '12px',
  'ti-cascader-node-text-color': '#191919',
  'ti-cascader-node-active-icon-color': '#191919',
}
