export const tinyRadioButtonOldTheme = {
  'ti-radio-button-checked-disabled-bg-color': '#bfbfbf',
  'ti-radio-button-active-disabled-bg-color': 'var(--ti-common-color-bg-dark-disabled)',
  'ti-radio-button-active-disabled-color': 'var(--ti-common-color-text-weaken)',
  'ti-radio-button-padding-verticals': 'var(--ti-common-space-3x)',
  'ti-radio-button-child-right-border-radius': '0',
  'ti-radio-button-child-left-border-radius': 'var(--ti-common-space-2)',
  'ti-radio-button-border-left': '1px',
  'ti-radio-button-margin-right': 'unset',
  'ti-radio-button-disabled-bg-color': 'var(--ti-common-color-bg-disabled, #f5f5f6)',
  'ti-radio-button-disabled-checked-text-color': 'var(--ti-common-color-text-weaken, #808080)',
  'ti-radio-button-checked-hover-box-shadow': '-1px 0 0 0 var(--ti-common-color-primary-hover, #7693f5)',
  'ti-radio-button-checked-hover-border-color': 'var(--ti-common-color-primary-hover, #7693f5)',
  'ti-radio-button-checked-hover-bg-color': 'var(--ti-common-color-primary-hover, #7693f5)',
  'ti-radio-button-checked-normal-box-shadow': '-1px 0 0 0 var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-radio-button-checked-normal-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-radio-button-checked-normal-bg-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-radio-button-bg-color': 'var(--ti-common-color-light, #fff)',
  'ti-radio-button-border-radius': '0',
  'ti-radio-button-hover-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-radio-button-text-color': 'var(--ti-common-color-info-normal, #252b3a)'
}
