export const tinyDropdownItemSmbTheme = {
  'ti-dropdown-item-expand-icon-size': 'var(--ti-common-font-size-2)',
  'ti-dropdown-item-padding-vertical': 'var(--ti-common-space-0)',
  'ti-dropdown-item-padding-horizontal': 'var(--ti-common-space-4x)',
  'ti-dropdown-item-hover-text-color': 'var(--ti-common-color-text-primary)',
  'ti-dropdown-item-icon-color-hover': 'var(--ti-common-color-text-link-hover)',
  'ti-dropdown-item-expand-svg-margin-left': 'var(--ti-common-space-0)',
  'ti-dropdown-item-expand-svg-margin-right': 'var(--ti-common-space-2x)',
  'ti-dropdown-item-content-margin-left': 'calc(var(--ti-dropdown-item-expand-icon-size) + var(--ti-common-space-2x))',
  'ti-dropdown-item-max-width': 'var(--ti-common-size-auto)',
  'ti-dropdown-item-height': 'var(--ti-common-size-height-normal)',
  'ti-dropdown-item-icon-color': 'var(--ti-common-color-icon)',
  'ti-dropdown-item-content-font-weight-hover': 'var(--ti-common-font-weight-6)',
  'ti-dropdown-item-active-bg-color': 'var(--ti-common-color-bg-white-normal)',
  'ti-dropdown-item-active-text-color': '#1476FF',
  'ti-dropdown-item-content-text-hover': '#1476FF',
  'ti-dropdown-item-before-bg-color': 'transparent',
  'ti-dropdown-item-divided-border-color': 'transparent',
  'ti-dropdown-item-content-bg-hover': 'transparent',
  'ti-dropdown-item-before-height': '0',
  'ti-dropdown-item-bg-color-selected': 'var(--ti-common-color-bg-white-normal)',
  'ti-dropdown-item-text-color-selected': '#1476FF',
  'ti-dropdown-item-font-weight-selected': 'var(--ti-common-font-weight-6)'
}
