/**
 * Copyright (c) 2022 - present TinyVue Authors.
 * Copyright (c) 2022 - present Huawei Cloud Computing Technologies Co., Ltd.
 *
 * Use of this source code is governed by an MIT-style license.
 *
 * THE OPEN SOURCE SOFTWARE IN THIS PRODUCT IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR
 * A PARTICULAR PURPOSE. SEE THE APPLICABLE LICENSES FOR MORE DETAILS.
 *
 */

export default [
  'action-menu',
  'bulletin-board',
  'button-group',
  'card-container',
  'card-item',
  'card-layout',
  'card-template',
  'carousel-item',
  'cascader-menu',
  'cascader-panel',
  'cascader-node',
  'checkbox-button',
  'checkbox-group',
  'context-menu',
  'collapse-item',
  'detail-page',
  'dialog-box',
  'dropdown-item',
  'dropdown-menu',
  'drop-roles',
  'drop-times',
  'date-panel',
  'date-picker',
  'data-range',
  'date-table',
  'fall-menu',
  'form-item',
  'img-preview',
  'img-preview-item',
  'ip-address',
  'link-menu',
  'month-range',
  'month-table',
  'nav-menu',
  'option-group',
  'option',
  'pop-editor',
  'popup-horiz-menu',
  'popup-menu',
  'popconfirm',
  'popconfirm-popover',
  'picker-panel',
  'quick-link-menu',
  'time-picker',
  'time-spinner',
  'time-panel',
  'time-range',
  'time-select',
  'scroll-text',
  'slide-bar',
  'slide-img',
  'select-dropdown',
  'suggest-popup',
  'tab-item',
  'tabs-dropdown',
  'textarea',
  'text-parse',
  'text-popup',
  'toggle-menu',
  'tree-menu',
  'upload-list',
  'user-account',
  'user-card',
  'user-contact',
  'user-head',
  'user-link',
  'year-table'
]
