/**
 * Copyright (c) 2022 - present TinyVue Authors.
 * Copyright (c) 2022 - present Huawei Cloud Computing Technologies Co., Ltd.
 *
 * Use of this source code is governed by an MIT-style license.
 *
 * THE OPEN SOURCE SOFTWARE IN THIS PRODUCT IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR
 * A PARTICULAR PURPOSE. SEE THE APPLICABLE LICENSES FOR MORE DETAILS.
 *
 */

// 键名对应变量名前面的2或3个字段，键值对应此类变量需要挂载到的类名。通过对象索引提高主题化生成速度
export default {
  'action-menu': 'action-menu',
  'bulletin-board': 'bulletin-board',
  'button-group': 'button-group',
  'card-container': 'card-container',
  'card-item': 'card-item',
  'card-layout': 'card-layout',
  'card-template': 'card-template',
  'carousel-item': 'carousel-item',
  'cascader-menu': 'cascader-menu',
  'cascader-panel': 'cascader-panel',
  'cascader-node': 'cascader-node',
  'checkbox-button': 'checkbox-button',
  'checkbox-group': 'checkbox-group',
  'context-menu': 'context-menu',
  'collapse-item': 'collapse-item',
  'detail-page': 'detail-page',
  'dialog-box': 'dialog-box',
  'dropdown-item': 'dropdown-item',
  'dropdown-menu': 'dropdown-menu',
  'drop-roles': 'drop-roles',
  'drop-times': 'drop-times',
  'date-panel': 'date-panel',
  'date-picker': 'date-picker',
  'data-range': 'data-range',
  'date-table': 'date-table',
  'fall-menu': 'fall-menu',
  'form-item': 'form-item',
  'img-preview': 'img-preview',
  'img-preview-item': 'img-preview-item',
  'ip-address': 'ip-address',
  'link-menu': 'link-menu',
  'month-range': 'month-range',
  'month-table': 'month-table',
  'nav-menu': 'nav-menu',
  'option-group': 'option-group',
  'popup-horiz-menu': 'popup-horiz-menu',
  'popup-menu': 'popup-menu',
  'popconfirm-popover': 'popconfirm-popover',
  'picker-panel': 'picker-panel',
  'quick-link-menu': 'quick-link-menu',
  'time-picker': 'time-picker',
  'time-spinner': 'time-spinner',
  'time-panel': 'time-panel',
  'time-range': 'time-range',
  'time-select': 'time-select',
  'scroll-text': 'scroll-text',
  'slide-bar': 'slide-bar',
  'slide-img': 'slide-img',
  'select-dropdown': 'select-dropdown',
  'suggest-popup': 'suggest-popup',
  'tab-item': 'tab-item',
  'tabs-dropdown': 'tabs-dropdown',
  'text-parse': 'text-parse',
  'text-popup': 'text-popup',
  'toggle-menu': 'toggle-menu',
  'tree-menu': 'tree-menu',
  'upload-list': 'upload-list',
  'upload-tip': 'upload__tip',
  'upload-dragger': 'upload-dragger',
  'user-account': 'user-account',
  'user-card': 'user-card',
  'user-contact': 'user-contact',
  'user-head': 'user-head',
  'user-link': 'user-link',
  'year-table': 'year-table'
}
