export const tinyWizardOldTheme = {
  'tv-Wizard-time-right-title-margin-bottom': 'var(----ti-common-space-2x, 8px)',
  'tv-Wizard-time-right-padding-vertical': 'var(--ti-common-size-base, 4px)',
  'tv-Wizard-time-right-margin-left': 'var(--ti-common-space-3x, 12px)',
  'tv-Wizard-time-right-text-align': 'center',
  'tv-Wizard-time-dot-size': 'calc(var(--ti-common-size-base, 4) * 2.5)',
  'tv-Wizard-time-left-line-height': '1.2em',
  'tv-Wizard-time-left-icon-size': 'var(--ti-common-font-size-base, 14px)',
  'tv-Wizard-time-left-icon-margin-left': 'var(--ti-common-space-base, 4px)',
  'tv-Wizard-time-left-icon-color': 'auto',
  'tv-Wizard-time-left-icon-margin-right': 'var(--ti-common-space-0, 0px)',
  'tv-Wizard-time-left-point-position-top': '-14px',
  'tv-Wizard-time-left-position-top': '-24px',
  'tv-Wizard-time-left-margin-right': 'var(--ti-common-space-0, 0px)',
  'tv-Wizard-time-left-min-width': 'var(--ti-common-size-25x, 100px)',
  'tv-Wizard-time-node-icon-height': 'var(--ti-common-line-height-4, 20px)',
  'tv-Wizard-time-node-icon-width': 'var(--ti-common-size-4x, 16px)',
  'tv-Wizard-time-node-border-weight': 'var(--ti-common-border-weight-1, 2px)',
  'tv-Wizard-time-node-size': 'var(--ti-common-font-size-5, 24px)',
  'tv-Wizard-vertical-wait-desc-text-color': 'inherit',
  'tv-Wizard-vertical-desc-text-color': 'inherit',
  'tv-Wizard-vertical-desc-font-size': 'var(--ti-common-font-size-1, 14px)',
  'tv-Wizard-vertical-title-line-height': 'auto',
  'tv-Wizard-vertical-desc-margin-top': 'var(--ti-common-space-2x, 8px)',
  'tv-Wizard-vertical-text-margin-left': '15px',
  'tv-Wizard-vertical-node-box-height': 'auto',
  'tv-Wizard-vertical-icon-position-top': '-14px',
  'tv-Wizard-vertical-line-position-top': '0px',
  'tv-Wizard-vertical-icon-position': 'relative',
  'tv-Wizard-vertical-line-height': 'var(--ti-common-size-22x, 88px)',
  'tv-Wizard-vertical-line-width': 'var(--ti-common-size-base, 4px)',
  'tv-Wizard-button-group-text-align': 'right',
  'tv-Wizard-button-margin-left': 'var(--ti-common-space-2x, 8px)',
  'tv-Wizard-button-group-margin-top': 'var(--ti-common-space-10, 10px)',
  'tv-Wizard-node-title-margin-top': 'var(--ti-common-space-6, 6px)',
  'tv-Wizard-lines-normal-border-weight': '0px',
  'tv-Wizard-node-doing-font-weight': 'normal',
  'tv-Wizard-right-lines-doing-bg-color': 'var(--ti-common-color-bg-emphasize, #5e7ce0)',
  'tv-Wizard-chart-icon-bg-color': 'var(--ti-common-color-line-disabled, #dfe1e6)',
  'tv-Wizard-last-lines-bg-color': 'var(--tv-Wizard-lines-normal-bg-color, #dfe1e6)',
  'tv-Wizard-time-last-lines-bg-color': 'none',
  'tv-Wizard-lines-normal-bg-color': '#c2c4c7',
  'tv-Wizard-first-lines-bg-color': 'var(--ti-common-color-bg-emphasize, #5e7ce0)',
  'tv-Wizard-lines-margin-horizontal': 'var(--ti-common-space-0, 0px)',
  'tv-Wizard-lines-width': 'calc(var(--ti-common-size-base, 4px) * 12.5)',
  'tv-Wizard-lines-height': 'var(--ti-common-size-base, 4px)',
  'tv-Wizard-node-size': 'var(--ti-common-font-size-4, 20px)',
  'tv-Wizard-icon-bg-color': 'var(--ti-common-color-bg-emphasize, #5e7ce0)',
  'tv-Wizard-normal-icon-color': 'var(--ti-common-color-light, #fff)',
  'tv-Wizard-icon-color': 'var(--ti-common-color-light, #fff)'
}
