export const tinyWizardSmbTheme = {
  'ti-wizard-icon-bg-color': 'var(--ti-common-color-light)',
  'ti-wizard-icon-color': 'var(--ti-common-color-bg-emphasize)',
  'ti-wizard-node-size': 'var(--ti-common-font-size-6)',
  'ti-wizard-lines-height': 'var(--ti-common-border-weight-normal)',
  'ti-wizard-lines-width': 'var(--ti-common-size-width-minor)',
  'ti-wizard-lines-margin-horizontal': 'var(--ti-common-dropdown-gap)',
  'ti-wizard-first-lines-bg-color': 'var(--ti-common-color-transparent)',
  'ti-wizard-last-lines-bg-color': 'var(--ti-common-color-transparent)',
  'ti-wizard-right-lines-doing-bg-color': 'var(--ti-common-color-line-disabled)',
  'ti-wizard-lines-normal-bg-color': 'var(--ti-common-color-line-disabled)',
  'ti-wizard-chart-icon-bg-color': 'var(--ti-common-color-bg-light-normal)',
  'ti-wizard-lines-normal-border-weight': 'var(--ti-common-border-weight-normal)',
  'ti-wizard-normal-icon-color': 'var(--ti-common-color-text-disabled)',
  'ti-wizard-node-doing-font-weight': 'var(--ti-common-font-weight-bold)',
  'ti-wizard-node-title-margin-top': 'var(--ti-common-dropdown-gap)',
  'ti-wizard-button-group-margin-top': 'calc(var(--ti-common-space-base) * 9)',
  'ti-wizard-button-group-text-align': 'left',
  'ti-wizard-button-margin-left': 'var(--ti-common-space-3x)',
  'ti-wizard-vertical-line-width': 'var(--ti-common-border-weight-normal)',
  'ti-wizard-vertical-line-height': 'var(--ti-common-line-height-8)',
  'ti-wizard-vertical-icon-position': 'absolute',
  'ti-wizard-vertical-line-position-top': '54px',
  'ti-wizard-vertical-icon-position-top': '-40px',
  'ti-wizard-vertical-node-box-height':
    'calc(var(--ti-wizard-vertical-line-height) + var(--ti-wizard-node-size) + 16px)',
  'ti-wizard-vertical-text-margin-left': '21.5px',
  'ti-wizard-vertical-desc-margin-top': 'var(--ti-common-space-0)',
  'ti-wizard-vertical-title-line-height': 'var(--ti-common-line-height-number)',
  'ti-wizard-vertical-desc-font-size': 'var(--ti-common-font-size-0)',
  'ti-wizard-vertical-desc-text-color': 'var(--ti-common-color-text-weaken)',
  'ti-wizard-vertical-wait-desc-text-color': 'var(--ti-common-color-bg-emphasize)',
  'ti-wizard-time-node-size': 'var(--ti-common-font-size-6)',
  'ti-wizard-time-node-border-weight': '0',
  'ti-wizard-time-last-lines-bg-color': 'var(--ti-common-color-bg-emphasize)',
  'ti-wizard-time-node-icon-width': 'var(--ti-common-font-size-6)',
  'ti-wizard-time-node-icon-height': 'var(--ti-common-font-size-6)',
  'ti-wizard-time-left-margin-right': 'var(--ti-common-space-2x)',
  'ti-wizard-time-left-position-top': '-28px',
  'ti-wizard-time-left-point-position-top': '-15px',
  'ti-wizard-time-left-icon-color': 'var(--ti-common-color-icon-normal)',
  'ti-wizard-time-left-icon-margin-right': 'var(--ti-common-space-10)',
  'ti-wizard-time-left-min-width': 'var(--ti-common-size-width-medium)',
  'ti-wizard-time-left-icon-margin-left': 'var(--ti-common-space-2x)',
  'ti-wizard-time-left-icon-size': 'var(--ti-common-font-size-2)',
  'ti-wizard-time-left-line-height': 'var(--ti-common-line-height-number)',
  'ti-wizard-time-dot-size': 'var(--ti-common-size-3x)',
  'ti-wizard-time-right-text-align': 'left',
  'ti-wizard-time-right-margin-left': '15.5px',
  'ti-wizard-time-right-padding-vertical': 'var(--ti-common-space-0)',
  'ti-wizard-time-right-title-margin-bottom': 'var(--ti-common-space-0)'
}
