export const tinyMilestoneOldTheme = {
  'ti-milestone-dot-display': 'block',
  'ti-milestone-flag-line-bg-color': '#333',
  'ti-milestone-flag-line-margin-left': '50%',
  'ti-milestone-flag-desc-line-height': '14px',
  'ti-milestone-flag-line-height': '14px',
  'ti-milestone-flag-desc-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-milestone-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-milestone-flag-desc-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-milestone-flag-name-font-weight': 'var(--ti-common-font-weight-4)',
  'ti-milestone-flag-content-bg-color': '#333',
  'ti-milestone-flag-content-border-radius': 'var(--ti-common-border-radius-1, 4px)',
  'ti-milestone-flag-padding': 'var(--ti-common-size-0, 0px) var(--ti-common-size-base, 4px)',
  'ti-milestone-flag-height': '34px',
  'ti-milestone-flag-width': '50px',
  'ti-milestone-status-font-size': 'var(--ti-common-font-size-1)',
  'ti-milestone-line-top': '-8px',
  'ti-milestone-line-left': '50%',
  'ti-milestone-line-width': '100%',
  'ti-milestone-line-height': 'var(--ti-common-size-base, 4px)',
  'ti-milestone-line-bg-color-completed': '#dbdbdb',
  'ti-milestone-line-bg-color': '#dbdbdb',
  'ti-milestone-icon-top': 'var(--ti-common-size-base, 4px)',
  'ti-milestone-icon-left': "~'calc(50% - 10px)'",
  'ti-milestone-icon-color': '#1890ff',
  'ti-milestone-icon-size': 'var(--ti-common-font-size-base)',
  'ti-milestone-icon-border-width-completed': 'var(--ti-common-border-weight-1)',
  'ti-milestone-icon-border-width': 'var(--ti-common-size-0)',
  'ti-milestone-icon-height': 'var(--ti-common-size-5x, 20px)',
  'ti-milestone-icon-width': 'var(--ti-common-size-5x, 20px)'
}
