export const tinyMilestoneOldTheme = {
  'tv-Milestone-dot-display': 'block',
  'tv-Milestone-flag-line-bg-color': '#333',
  'tv-Milestone-flag-line-margin-left': '50%',
  'tv-Milestone-flag-line-height': '14px',
  'tv-Milestone-flag-desc-font-size': 'var(--ti-common-font-size-base, 12px)',
  'tv-Milestone-text-color': 'var(--ti-common-color-light, #fff)',
  'tv-Milestone-flag-desc-text-color': 'var(--ti-common-color-light, #fff)',
  'tv-Milestone-flag-name-font-weight': 'var(--ti-common-font-weight-4)',
  'tv-Milestone-flag-bg-color': '#333',
  'tv-Milestone-flag-border-radius': 'var(--ti-common-border-radius-1, 4px)',
  'tv-Milestone-flag-padding': 'var(--ti-common-size-0, 0px) var(--ti-common-size-base, 4px)',
  'tv-Milestone-flag-height': '34px',
  'tv-Milestone-flag-width': '50px',
  'tv-Milestone-status-font-size': 'var(--ti-common-font-size-1)',
  'tv-Milestone-line-top': '-8px',
  'tv-Milestone-line-left': '50%',
  'tv-Milestone-line-width': '100%',
  'tv-Milestone-line-height': 'var(--ti-common-size-base, 4px)',
  'tv-Milestone-line-bg-color-completed': '#dbdbdb',
  'tv-Milestone-line-bg-color': '#dbdbdb',
  'tv-Milestone-icon-top': 'var(--ti-common-size-base, 4px)',
  'tv-Milestone-icon-left': "~'calc(50% - 10px)'",
  'tv-Milestone-icon-color': '#1890ff',
  'tv-Milestone-icon-size': 'var(--ti-common-font-size-base)',
  'tv-Milestone-icon-border-width-completed': 'var(--ti-common-border-weight-1)',
  'tv-Milestone-icon-border-width': 'var(--ti-common-size-0)',
  'tv-Milestone-icon-height': 'var(--ti-common-size-5x, 20px)',
  'tv-Milestone-icon-width': 'var(--ti-common-size-5x, 20px)'
}
