/**
* Copyright (c) 2022 - present TinyVue Authors.
* Copyright (c) 2022 - present Huawei Cloud Computing Technologies Co., Ltd.
*
* Use of this source code is governed by an MIT-style license.
*
* THE OPEN SOURCE SOFTWARE IN THIS PRODUCT IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
* BUT WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR
* A PARTICULAR PURPOSE. SEE THE APPLICABLE LICENSES FOR MORE DETAILS.
*
*/

export default {
  'tiny-button-border-radius': '2px',
  'tiny-button-plain-disabled-text-color': '#adb0b8',
  'tiny-button-padding-vertical': '0',
  'tiny-button-padding-horizontal': '8px',
  'tiny-button-font-size': '12px',
  'tiny-button-size-normal-min-width': '80px',
  'tiny-button-size-normal-max-width': '120px',
  'tiny-button-size-normal-height': '30px',
  'tiny-button-size-normal-padding': '8px',
  'tiny-button-size-large-min-width': '80px',
  'tiny-button-size-large-max-width': '140px',
  'tiny-button-size-large-height': '48px',
  'tiny-button-size-large-font-size': '16px',
  'tiny-button-size-large-padding': '14px',
  'tiny-button-size-medium-min-width': '80px',
  'tiny-button-size-medium-max-width': '130px',
  'tiny-button-size-medium-height': '42px',
  'tiny-button-size-medium-font-size': '14px',
  'tiny-button-size-medium-padding': '12px',
  'tiny-button-size-small-min-width': '80px',
  'tiny-button-size-small-max-width': '120px',
  'tiny-button-size-small-height': '36px',
  'tiny-button-size-small-font-size': '14px',
  'tiny-button-size-small-padding': '10px',
  'tiny-button-size-mini-min-width': '80px',
  'tiny-button-size-mini-max-width': '120px',
  'tiny-button-size-mini-height': '24px',
  'tiny-button-size-mini-font-size': '12px',
  'tiny-button-size-mini-padding': '4px',
  'tiny-button-normal-text-color': '#1890ff',
  'tiny-button-normal-border-color': '#d9d9d9',
  'tiny-button-normal-background-color': '#fff',
  'tiny-button-normal-hover-text-color': '#1890ff',
  'tiny-button-normal-hover-border-color': '#1890ff',
  'tiny-button-normal-hover-background-color': '#fff',
  'tiny-button-normal-active-text-color': '#1890ff',
  'tiny-button-normal-active-border-color': '#1890ff',
  'tiny-button-normal-active-background-color': '#e6f7ff',
  'tiny-button-normal-disabled-text-color': '#bfbfbf',
  'tiny-button-normal-disabled-border-color': '#d9d9d9',
  'tiny-button-normal-disabled-background-color': '#f5f5f5',
  'tiny-button-text-color': '#1890ff',
  'tiny-button-text-color-hover': '#40a9ff',
  'tiny-button-text-color-active': '#096dd9',
  'tiny-button-text-color-disabled': '#999',
  'tiny-button-primary-bg-color': '#fff',
  'tiny-button-primary-normal-bg-color': '#1890ff',
  'tiny-button-primary-disabled-text-color': '#fff',
  'tiny-button-primary-disabled-bg-color': '#d9d9d9',
  'tiny-button-primary-disabled-border-color': '#dfe1e6',
  'tiny-button-primary-text-color': '#fff',
  'tiny-button-primary-hover-bg-color': '#40a9ff',
  'tiny-button-primary-active-bg-color': '#096dd9',
  'tiny-button-primary-plain-bg-color': 'rgba(24, 144, 255, 0.06)',
  'tiny-button-primary-plain-disabled-bg-color': 'rgba(191, 191, 191, 0.1)',
  'tiny-button-success-text-color': '#fff',
  'tiny-button-success-normal-bg-color': '#52c41a',
  'tiny-button-success-disabled-text-color': '#fff',
  'tiny-button-success-disabled-border-color': '#dfe1e6',
  'tiny-button-success-disabled-bg-color': '#a6c3b9',
  'tiny-button-success-hover-bg-color': '#73d13d',
  'tiny-button-success-active-bg-color': '#389e0d',
  'tiny-button-success-plain-bg-color': 'rgba(82, 196, 26, 0.06)',
  'tiny-button-success-plain-disabled-bg-color': 'rgba(166, 195, 185, 0.1)',
  'tiny-button-warning-text-color': '#fff',
  'tiny-button-warning-normal-bg-color': '#faad14',
  'tiny-button-warning-disabled-text-color': '#fff',
  'tiny-button-warning-disabled-border-color': '#dfe1e6',
  'tiny-button-warning-disabled-bg-color': '#d3c6a2',
  'tiny-button-warning-hover-bg-color': '#ffc53d',
  'tiny-button-warning-active-bg-color': '#ffc53d',
  'tiny-button-warning-plain-bg-color': 'rgba(250, 173, 20, 0.06)',
  'tiny-button-warning-plain-disabled-bg-color': 'rgba(211, 198, 162, 0.1)',
  'tiny-button-danger-text-color': '#fff',
  'tiny-button-danger-normal-bg-color': '#f5222d',
  'tiny-button-danger-disabled-text-color': '#fff',
  'tiny-button-danger-disabled-border-color': '#dfe1e6',
  'tiny-button-danger-disabled-bg-color': '#d8bab5',
  'tiny-button-danger-hover-bg-color': '#ff4d4f',
  'tiny-button-danger-active-bg-color': '#cf1322',
  'tiny-button-danger-plain-bg-color': 'rgba(245, 34, 45, 0.06)',
  'tiny-button-danger-plain-disabled-bg-color': 'rgba(216, 186, 181, 0.1)',
  'tiny-button-info-text-color': '#fff',
  'tiny-button-info-normal-bg-color': '#333333',
  'tiny-button-info-disabled-text-color': '#fff',
  'tiny-button-info-disabled-border-color': '#dfe1e6',
  'tiny-button-info-disabled-bg-color': '#bfbfbf',
  'tiny-button-info-hover-bg-color': '#54657e',
  'tiny-button-info-active-bg-color': '#54657e',
  'tiny-button-info-plain-bg-color': 'rgba(51, 51, 51, 0.06)',
  'tiny-button-info-plain-disabled-bg-color': 'rgba(191, 191, 191, 0.1)'
}
