export const tinyButtonOldTheme = {
  'ti-button-only-icon-disabled-border-color': 'var(--ti-common-color-line-disabled, #dfe1e6)',
  'ti-button-only-icon-hover-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-only-icon-border-color': 'var(--ti-common-color-border, #adb0b8)',
  'ti-button-only-icon-border-radius': '2px',
  'ti-button-only-icon-padding-horizontal': '7px',
  'ti-button-only-icon-text-width': 'unset',
  'ti-button-only-icon-min-width': 'unset',
  'ti-button-only-icon-width': 'var(ti-common-size-width-minor, 30px)',
  'ti-button-icon-font-size': 'var(--ti-common-font-size-0, 12px)',
  'ti-button-text-size-mini-svg-height': '1em',
  'ti-button-text-size-mini-svg-width': '1em',
  'ti-button-text-size-mini-height': 'var(--ti-common-size-height-mini, 24px)',
  'ti-button-text-size-mini-min-width': 'var(--ti-common-size-16x, 64px)',
  'ti-button-text-size-small-svg-height': '1em',
  'ti-button-text-size-small-svg-width': '1em',
  'ti-button-text-size-small-height': 'var(--ti-common-size-height-small, 32px)',
  'ti-button-text-size-small-min-width': 'var(--ti-common-size-18x, 72px)',
  'ti-button-text-size-default-svg-height': '1em',
  'ti-button-text-size-default-svg-width': '1em',
  'ti-button-text-size-default-height': 'var(--ti-common-size-height-normal, 28px)',
  'ti-button-text-size-default-min-width': 'var(--ti-common-size-20x, 80px)',
  'ti-button-text-size-medium-svg-height': '1em',
  'ti-button-text-size-medium-svg-width': '1em',
  'ti-button-text-size-medium-height': 'var(--ti-common-size-height-medium, 40px)',
  'ti-button-text-size-medium-min-width': 'var(--ti-common-size-22x, 88px)',
  'ti-button-text-size-large-svg-height': '1em',
  'ti-button-text-size-large-svg-width': '1em',
  'ti-button-text-size-large-height': 'var(--ti-common-size-height-large, 48px)',
  'ti-button-text-size-large-min-width': 'var(--ti-common-size-24x, 96px)',
  'ti-button-size-normal-padding': 'var(--ti-common-space-2x, 8px)',
  'ti-button-danger-ghost-disabled-border-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-danger-ghost-disabled-text-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-danger-ghost-hover-border-color': 'var(--ti-common-color-danger-hover, #d64a52)',
  'ti-button-danger-ghost-hover-text-color': 'var(--ti-common-color-danger-hover, #d64a52)',
  'ti-button-danger-ghost-border-color': 'var(--ti-common-color-danger-normal, #c7000b)',
  'ti-button-danger-ghost-text-color': 'var(--ti-common-color-danger-normal, #c7000b)',
  'ti-button-warning-ghost-disabled-border-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-warning-ghost-disabled-text-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-warning-ghost-hover-border-color': 'var(--ti-common-color-warning-active, #fac20a)',
  'ti-button-warning-ghost-hover-text-color': 'var(--ti-common-color-warning-active, #fac20a)',
  'ti-button-warning-ghost-border-color': 'var(--ti-common-color-warning-normal, #fa9841)',
  'ti-button-warning-ghost-text-color': 'var(--ti-common-color-warning-normal, #fa9841)',
  'ti-button-info-ghost-disabled-border-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-info-ghost-disabled-text-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-info-ghost-hover-border-color': 'var(--ti-common-color-info-hover, #5c6173)',
  'ti-button-info-ghost-hover-text-color': 'var(--ti-common-color-info-hover, #5c6173)',
  'ti-button-info-ghost-border-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-button-info-ghost-text-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-button-success-ghost-disabled-border-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-success-ghost-disabled-text-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-success-ghost-hover-border-color': 'var(--ti-common-color-success-active, #acf2dc)',
  'ti-button-success-ghost-hover-text-color': 'var(--ti-common-color-success-active, #acf2dc)',
  'ti-button-success-ghost-border-color': 'var(--ti-common-color-success-normal, #50d4ab)',
  'ti-button-success-ghost-text-color': 'var(--ti-common-color-success-normal, #50d4ab)',
  'ti-button-primary-ghost-disabled-border-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-primary-ghost-disabled-text-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-primary-ghost-hover-border-color': 'var(--ti-common-color-primary-hover, #7693f5)',
  'ti-button-primary-ghost-hover-text-color': 'var(--ti-common-color-primary-hover, #7693f5)',
  'ti-button-primary-ghost-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-primary-ghost-text-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-ghost-disabled-border-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-ghost-disabled-text-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-ghost-hover-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-info-plain-disabled-bg-color':
    'var(\n    --ti-common-color-info-plain-disabled-bg-color,\n    rgba(191, 191, 191, 0.1)\n  )',
  'ti-button-info-plain-hover-border-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-button-info-plain-border-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-button-info-plain-hover-bg-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-button-info-plain-bg-color': 'var(--ti-common-color-info-bg, rgba(51, 51, 51, 0.06))',
  'ti-button-info-plain-hover-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-info-plain-text-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-button-info-disabled-border-color': 'var(--ti-common-color-info-disabled-border, #dfe1e6)',
  'ti-button-info-disabled-text-color': 'var(--ti-common-color-info-disabled-text, #adb0b8)',
  'ti-button-info-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-info-disabled-bg-color': 'var(--ti-common-color-info-disabled-bgcolor, #f5f5f6)',
  'ti-button-info-active-bg-color': 'var(--ti-common-color-info-active, #5c6173)',
  'ti-button-info-hover-border-color': 'var(--ti-common-color-info-hover, #5c6173)',
  'ti-button-info-hover-bg-color': 'var(--ti-common-color-info-hover, #5c6173)',
  'ti-button-info-normal-border-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-button-info-normal-bg-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-button-danger-plain-disabled-border-color': 'var(--ti-common-color-danger-disabled-bgcolor, #f5f5f6)',
  'ti-button-danger-plain-disabled-bg-color': 'var(--ti-common-color-danger-disabled-bgcolor, #f5f5f6)',
  'ti-button-danger-plain-hover-border-color': 'var(--ti-common-color-danger-normal, #c7000b)',
  'ti-button-danger-plain-border-color': 'var(--ti-common-color-danger-normal, #c7000b)',
  'ti-button-danger-plain-hover-bg-color': 'var(--ti-common-color-danger-normal, #c7000b)',
  'ti-button-danger-plain-bg-color': 'var(--ti-common-color-error-bg, #ffeeed)',
  'ti-button-danger-plain-hover-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-danger-plain-text-color': 'var(--ti-common-color-danger-normal, #c7000b)',
  'ti-button-danger-disabled-border-color': 'var(--ti-common-color-danger-disabled-border, #dfe1e6)',
  'ti-button-danger-disabled-text-color': 'var(--ti-common-color-danger-disabled-text, #adb0b8)',
  'ti-button-danger-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-danger-disabled-bg-color': 'var(--ti-common-color-danger-disabled-bgcolor, #f5f5f6)',
  'ti-button-danger-active-bg-color': 'var(--ti-common-color-danger-active, #b12220)',
  'ti-button-danger-hover-border-color': 'var(--ti-common-color-danger-hover, #d64a52)',
  'ti-button-danger-hover-bg-color': 'var(--ti-common-color-danger-hover, #d64a52)',
  'ti-button-danger-normal-border-color': 'var(--ti-common-color-danger-normal, #c7000b)',
  'ti-button-danger-normal-bg-color': 'var(--ti-common-color-danger-normal, #c7000b)',
  'ti-button-warning-plain-disabled-bg-color':
    'var(\n    --ti-common-color-warning-plain-disabled-bg-color,\n    rgba(211, 198, 162, 0.1)\n  )',
  'ti-button-warning-plain-hover-border-color': 'var(--ti-common-color-warning-normal, #fa9841)',
  'ti-button-warning-plain-border-color': 'var(--ti-common-color-warning-normal, #fa9841)',
  'ti-button-warning-plain-hover-bg-color': 'var(--ti-common-color-warning-normal, #fa9841)',
  'ti-button-warning-plain-bg-color': 'var(--ti-common-color-warn-bg, #fff3e8)',
  'ti-button-warning-plain-hover-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-warning-plain-text-color': 'var(--ti-common-color-warning-normal, #fa9841)',
  'ti-button-warning-disabled-border-color': 'var(--ti-common-color-warning-disabled-border, #dfe1e6)',
  'ti-button-warning-disabled-text-color': 'var(--ti-common-color-warning-disabled-text, #adb0b8)',
  'ti-button-warning-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-warning-disabled-bg-color': 'var(--ti-common-color-warning-disabled-bgcolor, #f5f5f6)',
  'ti-button-warning-active-bg-color': 'var(--ti-common-color-warning-active, #fac20a)',
  'ti-button-warning-hover-bg-color': 'var(--ti-common-color-warning-hover, #fac20a)',
  'ti-button-warning-normal-border-color': 'var(--ti-common-color-warning-normal, #fa9841)',
  'ti-button-warning-normal-bg-color': 'var(--ti-common-color-warning-normal, #fa9841)',
  'ti-button-success-plain-disabled-bg-color':
    'var(\n    --ti-common-color-success-plain-disabled-bg-color,\n    rgba(166, 195, 185, 0.1)\n  )',
  'ti-button-success-plain-hover-border-color': 'var(--ti-common-color-success-normal, #50d4ab)',
  'ti-button-success-plain-border-color': 'var(--ti-common-color-success-normal, #50d4ab)',
  'ti-button-success-plain-hover-bg-color': 'var(--ti-common-color-success-normal, #50d4ab)',
  'ti-button-success-plain-bg-color': 'var(--ti-common-color-success-bg, #edfff9)',
  'ti-button-success-plain-hover-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-success-plain-text-color': 'var(--ti-common-color-success-normal, #50d4ab)',
  'ti-button-success-disabled-border-color': 'var(--ti-common-color-success-disabled-border, #dfe1e6)',
  'ti-button-success-disabled-text-color': 'var(--ti-common-color-success-disabled-text, #adb0b8)',
  'ti-button-success-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-success-disabled-bg-color': 'var(--ti-common-color-success-disabled-bgcolor, #f5f5f6)',
  'ti-button-success-active-bg-color': 'var(--ti-common-color-success-active, #acf2dc)',
  'ti-button-success-hover-border-color': 'var(--ti-common-color-success-hover, #acf2dc)',
  'ti-button-success-hover-bg-color': 'var(--ti-common-color-success-hover, #acf2dc)',
  'ti-button-success-normal-border-color': 'var(--ti-common-color-success-normal, #50d4ab)',
  'ti-button-success-normal-bg-color': 'var(--ti-common-color-success-normal, #50d4ab)',
  'ti-button-primary-plain-disabled-bg-color':
    'var(\n    --ti-common-color-primary-plain-disabled-bg-color,\n    rgba(191, 191, 191, 0.1)\n  )',
  'ti-button-primary-plain-hover-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-primary-plain-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-primary-plain-hover-bg-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-primary-plain-bg-color': 'var(--ti-common-color-prompt-bg, #ebf6ff)',
  'ti-button-primary-plain-hover-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-primary-plain-text-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-primary-disabled-border-color': 'var(--ti-common-color-primary-disabled-border, #dfe1e6)',
  'ti-button-primary-disabled-text-color': 'var(--ti-common-color-primary-disabled-text, #adb0b8)',
  'ti-button-primary-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-button-primary-active-bg-color': 'var(--ti-common-color-primary-active, #7693f5)',
  'ti-button-primary-hover-border-color': 'var(--ti-common-color-primary-hover, #7693f5)',
  'ti-button-primary-hover-bg-color': 'var(--ti-common-color-primary-hover, #7693f5)',
  'ti-button-primary-normal-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-primary-normal-bg-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-text-svg-padding-horizontal': 'var(--ti-common-size-2x, 8px)',
  'ti-button-text-has-svg-hover-text-color': 'var(--ti-common-color-text-link, #526ecc)',
  'ti-button-text-has-svg-text-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'ti-button-text-has-svg-icon-margin-right': 'var(--ti-common-size-2x, 8px)',
  'ti-button-text-svg-disabled-fill-color': 'var(--ti-common-color-text-disabled, #adb0b8)',
  'ti-button-text-svg-hover-fill-color': 'var(--ti-button-text-color-hover)',
  'ti-button-text-svg-fill-color': 'var(--ti-common-color-text-secondary, #575d6c)',
  'ti-button-text-hover-border-radius': '0px',
  'ti-button-text-only-icon-hover-bg-color': 'transparent',
  'ti-button-text-hover-bg-color': 'transparent',
  'ti-button-text-svg-height': '1em',
  'ti-button-text-svg-width': '1em',
  'ti-button-text-hover-weight': 'var(--ti-common-font-weight-4, normal)',
  'ti-button-text-color-hover': 'var(--ti-common-color-text-link-hover, #344899)',
  'ti-button-text-hover-text-decoration': 'none',
  'ti-button-text-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-plain-disabled-border-color': 'var(--ti-common-color-line-disabled, #dfe1e6)',
  'ti-button-plain-border-color': 'var(--ti-common-color-border, #adb0b8)',
  'ti-button-normal-disabled-border-color': 'var(--ti-common-color-line-disabled, #dfe1e6)',
  'ti-button-normal-hover-border-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-button-normal-border-color': 'var(--ti-common-color-border, #adb0b8)',
  'ti-button-normal-text-color': 'var(--ti-common-color-text-primary, #252b3a)',
  'ti-button-size-mini-min-width': 'var(--ti-common-size-16x, 64px)',
  'ti-button-size-mini-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-button-size-small-margin-left': '8px',
  'ti-button-size-small-min-width': 'var(--ti-common-size-18x, 72px)',
  'ti-button-size-small-padding-horizontal': 'var(--ti-common-size-3x, 12px)',
  'ti-button-size-small-font-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-button-size-medium-margin-left': '8px',
  'ti-button-size-medium-min-width': 'var(--ti-common-size-22x, 88px)',
  'ti-button-size-medium-padding-horizontal': 'var(--ti-common-size-7x, 28px)',
  'ti-button-size-large-margin-left': '8px',
  'ti-button-size-large-min-width': 'var(--ti-common-size-24x, 96px)',
  'ti-button-size-large-padding-horizontal': 'var(--ti-common-size-8x, 32px)',
  'ti-button-size-large-font-size': 'var(--ti-common-font-size-2, 16px)',
  'ti-button-size-normal-padding-horizontal': 'var(--ti-common-size-5x, 20px)',
  'ti-button-size-normal-min-width': 'var(--ti-common-size-width-normal, 80px)',
  'ti-button-loading-font-size': 'var(--ti-common-font-size-1)',
  'ti-button-loading-bg-color': 'rgba(255, 255, 255, 0.35)',
  'ti-button-border-radius': 'var(--ti-common-border-radius-normal, 2px)'
}
