import { test, expect } from '@playwright/test'

test('测试表单文本对齐', async ({ page }) => {
  page.on('pageerror', (exception) => expect(exception).toBeNull())
  await page.goto('form#label-align')

  const preview = page.locator('#preview')
  const form = preview.locator('.tiny-form')
  const formItem = form.locator('.tiny-form-item')
  const switchBtn = preview.locator('.tiny-switch')
  const firstItemLabel = formItem.first().locator('.tiny-form-item__label')
  const firstItemContent = formItem.first().locator('.tiny-form-item__content')

  await switchBtn.click()
  await expect(form).not.toHaveClass(/label-align/)
  await switchBtn.click()
  await expect(form).toHaveClass(/label-align/)
  let labelBox = await firstItemLabel.boundingBox()
  let contentBox = await firstItemContent.boundingBox()
  expect(labelBox.y).toEqual(contentBox.y)
  await preview.getByRole('button', { name: 'top' }).click()
  labelBox = await firstItemLabel.boundingBox()
  contentBox = await firstItemContent.boundingBox()
  expect(labelBox.y).toBeLessThan(contentBox.y)
  await preview.getByRole('button', { name: 'right' }).click()
  labelBox = await firstItemLabel.boundingBox()
  contentBox = await firstItemContent.boundingBox()
  expect(contentBox.y).toEqual(labelBox.y)
  await expect(firstItemLabel).toHaveCSS('text-align', 'right')
})
