export default {
  'tiny-mobile-search-height': '44px',
  'tiny-mobile-search-input-height': '32px',
  'tiny-mobile-search-input-border-radius': '32px',
  'tiny-mobile-search-input-bg-color-gray': '#f5f5f5',
  'tiny-mobile-search-input-bg-color-primary': 'rgba(255, 255, 255, 0.15)',
  'tiny-mobile-search-font-size': '14px',
  'tiny-mobile-search-text-color-gray': '#191919',
  'tiny-mobile-search-text-color-primary': '#fff',
  'tiny-mobile-search-icon-fill-color-gray': '#dbdbdb',
  'tiny-mobile-search-icon-fill-color-primary': '#fff',
  'tiny-mobile-search-caret-color-primary': '#fff',
  'tiny-mobile-search-caret-color-gray': '#4a79fe',
  'tiny-mobile-search-bg-color-primary': '#3168f1',
  'tiny-mobile-search-bg-color-gray': '#fff',
  'tiny-mobile-search-placeholder-text-color-primary': '#dbe5fc',
  'tiny-mobile-search-placeholder-text-color-gray': '#acacac',
}
