export const tinyTagAuroraTheme = {
  'ti-tag-primary-text-color': 'var(--ti-common-color-icon-normal)',
  'ti-tag-primary-close-icon-color': 'var(--ti-common-color-icon-normal)',
  'ti-tag-primary-close-hover-icon-color': 'var(--ti-common-color-icon-normal)',
  'ti-tag-primary-border-color': 'rgba(24,144,255,.15)',
  'ti-tag-primary-background-color': 'rgba(24,144,255,.06)',
  // 成功类
  'ti-tag-success-text-color': 'var(--ti-common-color-data-1)',
  'ti-tag-success-background-color': 'rgba(82,196,26,.06)',
  'ti-tag-success-border-color': 'rgba(82,196,26,.15)',
  // 警告类
  'ti-tag-warning-text-color': 'var(--ti-common-color-data-7)',
  'ti-tag-warning-background-color': 'rgba(250,173,20,.06)',
  'ti-tag-warning-border-color': 'rgba(250,173,20,.15)',
  // 危险类
  'ti-tag-danger-text-color': 'var(--ti-common-color-data-8)',
  'ti-tag-danger-background-color': 'rgba(245,34,45,.06)',
  'ti-tag-danger-border-color': 'rgba(245,34,45,.15)',
  // dark主题
  'ti-tag-dark-bg-color': 'var(--ti-common-color-icon-darkbg-active)',
  'ti-tag-dark-success-bg-color': '#67c23a',
  'ti-tag-dark-info-bg-color': 'var(--ti-common-color-info)',
  'ti-tag-dark-warning-bg-color': '#e6a23c',
  // plain主题
  'ti-tag-plain-text-color': 'var(--ti-common-color-text-link-hover)',
  'ti-tag-plain-border-color': '#b3d8ff',
  'ti-tag-plain-success-text-color': '#67c23a',
  'ti-tag-plain-success-border-color': '#c2e7b0',
  'ti-tag-plain-info-border-color': '#d3d4d6',
  'ti-tag-plain-danger-border-color': '#fbc4c4',
  'ti-tag-plain-warning-text-color': '#e6a23c',
  'ti-tag-plain-warning-border-color': '#f5dab1'
}
