export const tinyTagOldTheme = {
  'ti-tag-disabled-background-color': 'rgba(0, 0, 0, 0.05)',
  'ti-tag-info-background-color': 'var(--ti-common-color-info-bg, rgba(51, 51, 51, 0.06))',
  'ti-tag-primary-background-color': 'var(--ti-common-color-bg-normal, #eef0f5)',
  'ti-tag-primary-close-opacity': '0.5',
  'ti-tag-primary-close-hover-icon-color': 'var(--ti-common-color-text-secondary, #575d6c)',
  'ti-tag-primary-close-icon-color': 'var(--ti-common-color-text-secondary, #575d6c)',
  'ti-tag-primary-text-color': 'var(--ti-common-color-text-secondary, #575d6c)',
  'ti-tag-close-small-margin-right': 'var(--ti-common-space-0, 0px)',
  'ti-tag-close-small-margin-left': 'var(--ti-common-space-6, 6px)',
  'ti-tag-close-medium-margin-right': 'var(--ti-common-space-0, 0px)',
  'ti-tag-close-medium-margin-left': 'var(--ti-common-space-6, 6px)',
  'ti-tag-close-margin-right': 'var(--ti-common-space-0, 0px)',
  'ti-tag-close-margin-left': 'var(--ti-common-space-6, 6px)',
  'ti-tag-close-font-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-tag-font-size': 'var(--ti-common-font-size-base, 12px)',
  'ti-tag-small-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-tag-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-tag-border-weight': 'var(--ti-common-border-weight-normal, 1px)',
  'ti-tag-mini-height': 'var(--ti-common-size-4x, 16px)',
  'ti-tag-small-padding-horizontal': 'var(--ti-common-space-2x, 8px)',
  'ti-tag-small-height': 'var(--ti-common-line-height-4, 20px)',
  'ti-tag-medium-padding-horizontal': 'var(--ti-common-space-2x, 8px)',
  'ti-tag-medium-height': 'var(--ti-common-size-6x, 24px)',
  'ti-tag-height': 'calc(var(--ti-common-size-base, 4px) * 5.5)'
}
