export const tinyDateTableOldTheme = {
  'ti-date-table-week-height': 'var(--ti-common-size-height-normal)',
  'ti-date-table-td-row-disabled-border-radius': '0',
  'ti-date-table-td-disabled-border-radius': '0',
  'ti-date-table-tr-line-height': '32px',
  'ti-date-table-cell-selected-border-radius': '0',
  'ti-date-table-start-date-border-radius': '0',
  'ti-date-table-td-span-top': '5px',
  'ti-date-table-td-div-width': '36px',
  'ti-date-table-td-div-height': '24px',
  'ti-date-table-td-today-circle-border-width': '0',
  'ti-date-table-td-today-circle-border-color': 'transparent',
  'ti-date-table-td-today-border-radius': '0',
  'ti-date-table-td-today-height': '24px',
  'ti-date-table-td-today-width': '36px',
  'ti-date-table-border-radius-current-select': '0',
  'ti-date-table-bg-color-current-select': 'var(--ti-base-color-brand-6, #5e7ce0)',
  'ti-date-table-range-hover-bg-color': 'var(--ti-base-color-brand-2, #e9edfa)',
  'ti-date-table-range-bg-color': 'var(--ti-base-color-brand-2, #e9edfa)',
  'ti-date-table-hover-bg-color': 'var(--ti-common-color-selected-background, #5e7ce0)',
  'ti-date-table-week-bg-color-current-hover': 'var(--ti-base-color-brand-3, #beccfa)',
  'ti-date-table-week-bg-color-current-select': 'var(--ti-base-color-brand-2, #e9edfa)',
  'ti-date-table-td-today-border-color': 'var(--ti-base-color-brand-6, #5e7ce0)',
  'ti-date-table-td-border-radius': '0',
  'ti-date-table-td-span-height': '24px',
  'ti-date-table-td-span-width': '36px'
}
