export const tinyDateTableSmbTheme = {
  'ti-date-table-border-radius-current-select': '14px',
  'ti-date-table-td-span-width': '28px',
  'ti-date-table-td-span-height': '28px',
  'ti-date-table-bg-color-current-select': 'var(--ti-base-color-brand-2)',
  'ti-date-table-week-bg-color-current-select': 'var(--ti-base-color-brand-8)',
  'ti-date-table-week-bg-color-current-hover': 'var(--ti-base-color-brand-8)',
  'ti-date-table-td-today-width': '26px',
  'ti-date-table-td-today-height': '26px',
  'ti-date-table-td-today-border-radius': '13px',
  'ti-date-table-td-today-circle-border-color': 'var(--ti-base-color-brand)',
  'ti-date-table-td-today-circle-border-width': '1px',
  'ti-date-table-hover-bg-color': 'var(--ti-base-color-brand-8)',

  'ti-date-table-range-bg-color': 'var(--ti-base-color-brand-8)',
  'ti-date-table-td-div-height': '28px',
  'ti-date-table-td-div-width': '28px',
  'ti-date-table-range-hover-bg-color': 'var(--ti-base-color-brand-8)',
  'ti-date-table-td-border-radius': '14px',
  'ti-date-table-td-span-top': '3px',
  'ti-date-table-start-date-border-radius': '14px',
  'ti-date-table-td-today-border-color': 'transparent',
  'ti-date-table-cell-selected-border-radius': '14px',
  'ti-date-table-tr-line-height': '16px',
  'ti-date-table-td-disabled-border-radius': '50%',
  'ti-date-table-td-row-disabled-border-radius': 'unset'
}
