export const tinySelectDropdownOldTheme = {
  'ti-select-dropdown-icon-color': 'var(--ti-common-color-icon-normal, #575d6c)',
  'ti-select-dropdown-icon-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-select-dropdown-wrap-padding-bottom': 'var(--ti-common-space-0, 0px)',
  'ti-select-dropdown-search-empty-padding-bottom': 'var(--ti-common-space-6, 6px)',
  'ti-select-dropdown-search-empty-padding-top': 'var(--ti-common-space-6, 6px)',
  'ti-select-dropdown-search-input-padding-left': 'var(--ti-common-space-2x, 8px)',
  'ti-select-dropdown-search-input-padding-right': '54px',
  'ti-select-dropdown-search-prefix-display': 'none',
  'ti-select-dropdown-search-suffix-display': "'block'",
  'ti-select-dropdown-search-border-width': 'var(--ti-common-size-0, 0px)',
  'ti-select-dropdown-search-width': '100%',
  'ti-select-dropdown-search-margin-right': 'var(--ti-common-size-0, 0px)',
  'ti-select-dropdown-search-margin-left': 'var(--ti-common-size-0, 0px)',
  'ti-select-dropdown-search-margin-bottom': 'var(--ti-common-space-base, 4px)',
  'ti-select-dropdown-search-margin-top': 'calc(-1 * var(--ti-common-size-base))',
  'ti-select-dropdown-search-bg-color': 'var(--ti-common-color-bg-white-emphasize, #f2f5fc)',
  'ti-select-dropdown-padding-bottom': 'var(--ti-common-space-base, 4px)',
  'ti-select-dropdown-padding-top': 'var(--ti-common-size-base, 4px)',
  'ti-select-dropdown-empty-padding-vertical': 'var(--ti-common-space-6, 6px)',
  'ti-select-dropdown-empty-padding-horizontal': 'var(--ti-common-space-10, 10px)',
  'ti-select-dropdown-empty-font-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-select-dropdown-empty-text-color': 'var(--ti-common-color-placeholder, #adb0b8)',
  'ti-select-dropdown-max-height': 'calc(30px * 8 + 8px)',
  'ti-select-dropdown-margin-bottom': 'var(--ti-common-dropdown-gap, 2px)',
  'ti-select-dropdown-margin-top': 'var(--ti-common-dropdown-gap, 2px)',
  'ti-select-dropdown-item-padding-horizontal': 'var(--ti-common-space-2x, 8px)',
  'ti-select-dropdown-box-shadow': 'var(--ti-common-shadow-2-down, 0 2px 8px 0 rgba(0, 0, 0, 0.2))',
  'ti-select-dropdown-border-radius': 'var(--ti-common-border-radius-normal, 2px)'
}
