export const tinySelectDropdownSmbTheme = {
  'ti-select-dropdown-border-radius': 'var(--ti-common-border-radius-3)',
  'ti-select-dropdown-empty-text-color': 'var(--ti-common-color-text-secondary)',
  'ti-select-dropdown-empty-padding-horizontal': 'var(--ti-common-size-0)',
  'ti-select-dropdown-empty-padding-vertical': '46px',
  'ti-select-dropdown-empty-font-size': 'var(--ti-common-font-size-0)',
  'ti-select-dropdown-margin-top': 'var(--ti-common-space-base)',
  'ti-select-dropdown-box-shadow': 'var(--ti-common-shadow-2-down)',
  'ti-select-dropdown-padding-top': 'var(--ti-common-space-2x)',
  'ti-select-dropdown-padding-bottom': 'var(--ti-common-space-2x)',
  'ti-select-dropdown-max-height':
    'calc(240px - var(--ti-select-dropdown-padding-top) - var(--ti-select-dropdown-padding-bottom) + var(--ti-common-space-2x))',
  'ti-select-dropdown-search-margin-left': 'var(--ti-common-space-4x)',
  'ti-select-dropdown-search-margin-right': 'var(--ti-common-space-4x)',
  'ti-select-dropdown-search-margin-top': 'var(--ti-common-space-2x)',
  'ti-select-dropdown-search-width': 'calc(100% - var(--ti-common-space-4x)*2)',
  'ti-select-dropdown-search-bg-color': 'var(--ti-common-color-bg-white-normal)',
  'ti-select-dropdown-search-border-width': 'var(--ti-common-border-weight-normal)',
  'ti-select-dropdown-search-suffix-display': 'none',
  'ti-select-dropdown-search-prefix-display': 'block',
  'ti-select-dropdown-search-input-padding-right': 'var(--ti-common-space-3x)',
  'ti-select-dropdown-search-input-padding-left': '28px',
  'ti-select-dropdown-search-empty-padding-top': 'var(--ti-common-space-3x)',
  'ti-select-dropdown-search-empty-padding-bottom': 'var(--ti-common-space-2x)',
  'ti-select-dropdown-wrap-padding-bottom': 'var(--ti-common-space-base)',
  'ti-select-dropdown-icon-size': 'var(--ti-common-font-size-2)',
  'ti-select-dropdown-icon-color': 'var(--ti-common-color-icon-normal)',
  'ti-select-dropdown-search-margin-bottom': 'var(--ti-common-space-2x)'
}
