export const tinyNavMenuOldTheme = {
  'ti-nav-menu-popmenu-node-item-padding-button': 'var(--ti-common-space-base, 4px)',
  'ti-nav-menu-popmenu-node-item-padding-top': 'var(--ti-common-space-base, 4px)',
  'ti-nav-menu-submenu-group-margin-top': 'var(--ti-common-space-4x, 18px)',
  'ti-nav-menu-popmenu-text-font-size': 'var(--ti-common-font-size-1, 14px)',
  'ti-nav-menu-popmenu-node-title-margin-bottom': 'var(--ti-common-space-3x, 12px)',
  'ti-nav-menu-submenu-padding-horizontal': 'calc(var(--ti-common-space-base, 4px) * 21.5)',
  'ti-nav-menu-popmenu-more-item-active-bg-color': 'var(--ti-common-color-selected-background, #5e7ce0)',
  'ti-nav-menu-popmenu-more-item-hover-bg-color': 'var(--ti-common-color-hover-background, #f2f5fc)',
  'ti-nav-menu-popmenu-more-item-selected-bg-color': 'var(--ti-common-color-bg-white-emphasize, #f2f5fc)',
  'ti-nav-menu-popmenu-more-item-hover-text-color': 'var(--ti-common-color-primary-normal, #5e7ce0)',
  'ti-nav-menu-popmenu-more-item-icon-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-nav-menu-popmenu-border-color': 'var(--ti-common-color-border, #adb0b8)',
  'ti-nav-menu-popmenu-text-color': 'var(--ti-common-color-info-normal, #252b3a)',
  'ti-nav-menu-popmenu-selected-font-weight': 'var(--ti-common-font-weight-4, normal)',
  'ti-nav-menu-popmenu-box-shadow': '0 0 4px var(--ti-nav-menu-popmenu-border-color)',
  'ti-nav-menu-item-selected-underline-bg-color': 'var(--ti-common-color-light, #fff)',
  'ti-nav-menu-item-selected-underline-height': 'calc(var(--ti-common-size-base, 4px) - 1)',
  'ti-nav-menu-item-hover-bg-color': '#474c5e',
  'ti-nav-menu-item-text-font-weight': 'var(--ti-common-font-weight-4, normal)',
  'ti-nav-menu-item-more-button-fill': 'var(--ti-common-color-light, #fff)',
  'ti-nav-menu-item-text-color': 'var(--ti-common-color-light, #fff)',
  'ti-nav-menu-padding': 'var(--ti-common-size-6x, 24px)',
  'ti-nav-menu-slot-logo-margin-right': 'var(--ti-common-size-25x, 100px)',
  'ti-nav-menu-slot-logo-margin-left': 'var(--ti-common-space-0, 0)',
  'ti-nav-menu-item-li-margin': 'var(--ti-common-size-3x, 12px)',
  'ti-nav-menu-item-font-size': 'var(--ti-common-font-size-2, 16px)',
  'ti-nav-menu-bg-color': 'var(--ti-common-color-bg-navigation, #282b33)'
}
