export default {
  'tiny-mobile-button-height': '42px',
  'tiny-mobile-button-font-size-default': '16px',
  'tiny-mobile-button-text-color-white': '#fff',
  'tiny-mobile-button-text-color-disabled': '#dbdbdb',
  'tiny-mobile-button-text-color-default': '#191919',
  'tiny-mobile-button-border-color': '#dbdbdb',
  'tiny-mobile-button-bg-color-default': '#fff',
  'tiny-mobile-button-bg-color-primary': '#1e8aff',
  'tiny-mobile-button-bg-color-success': '#1ebe40',
  'tiny-mobile-button-bg-color-warning': '#fccd32',
  'tiny-mobile-button-bg-color-danger': '#eb5454',
  'tiny-mobile-button-bg-color-disabled': '#e8e8e8',
  'tiny-mobile-button-bg-color-info': '#333',
  'tiny-mobile-button-height-medium': '36px',
  'tiny-mobile-button-font-size-medium': '14px',
  'tiny-mobile-button-height-small': '28px',
  'tiny-mobile-button-font-size-small': '12px',
  'tiny-mobile-button-height-mini': '22px',
  'tiny-mobile-button-font-size-mini': '10px',
  'tiny-mobile-button-text-color': '#4a79fe',
  'tiny-mobile-button-text-color-hover': '#6e94fe',
  'tiny-mobile-button-text-color-active': '#4a79fe',
}
