export const tinyCardOldTheme = {
  'ti-card-title-mg-bottom': 'var(--ti-common-space-3x)',
  'ti-card-option-top-border-color': 'var(--ti-base-color-common-1)',
  'ti-card-option-font-size': 'var(--ti-common-font-size-1)',
  'ti-card-option-text-color': 'var(--ti-base-color-common-9)',
  'ti-card-main-text-color': 'var(--ti-base-color-common-6)',
  'ti-card-main-font-size': 'var(--ti-common-font-size-base)',
  'ti-card-title-font-weight': 'var(--ti-common-font-weight-4)',
  'ti-card-title-text-color': 'var(--ti-base-color-common-9)',
  'ti-card-title-font-size': 'var(--ti-common-font-size-1)',
  'ti-card-mini-body-padding': 'var(--ti-common-space-2x)',
  'ti-card-small-body-padding': 'var(--ti-common-space-3x)',
  'ti-card-medium-body-padding': 'var(--ti-common-space-3x)',
  'ti-card-large-body-padding': 'var(--ti-common-space-4x)',
  'ti-card-checked-border-color': 'var(--ti-common-color-line-active)',
  'ti-card-default-border-color': 'var(--ti-base-color-common-1)',
  'ti-card-large-border-radius': 'var(--ti-common-border-radius-2)',
  'ti-card-box-shadow': 'var(--ti-common-shadow-3-down)',
  'ti-card-bg-color': 'var(--ti-base-color-bg-1)'
}
