/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const TinyLoading: (typeof import('@opentiny/vue'))['TinyLoading']
  const TinyModal: (typeof import('@opentiny/vue'))['TinyModal']
  const TinyNotify: (typeof import('@opentiny/vue'))['TinyNotify']
}
