export const tinyCheckboxSmbTheme = {
  'ti-checkbox-border-radius': 'var(--ti-common-border-radius-2)',
  'ti-checkbox-outline-border-radius': 'var(--ti-common-border-radius-3)',
  'ti-checkbox-label-text-color-disabled': 'var(--ti-common-color-text-disabled)',
  'ti-checkbox-bg-color-disable': 'var(--ti-common-color-bg-disabled)',
  'ti-checkbox-icon-color-disabled': '#fff',
  'ti-checkbox-bg-color-checked-disabled': '#dbdbdb',
  'ti-checkbox-border-color-checked-disabled': '#dbdbdb',
  'ti-checkbox-checkline-width': 'var(--ti-common-border-weight-normal)',
  'ti-checkbox-label-margin-right': 'var(--ti-common-space-6x)',
  'ti-checkbox-icon-margin-top': '1px',
  'ti-checkbox-icon-margin-left': '4.5px',
  'ti-checkbox-button-checked-bg-color': '#FFFFFF',
  'ti-checkbox-button-checked-text-color': '#1476FF',
  'ti-checkbox-button-text-color': '#595959',
  'ti-checkbox-button-bg-color-hover': '#FFFFFF',
  'ti-checkbox-button-hover-text-color': '#191919',
  'ti-checkbox-bg-color-checked': '#1476ff',
  'ti-checkbox-border-color-checked': '#1476FF',
  'ti-checkbox-bg-color-hover-checked': '#1476FF',
  'ti-checkbox-border-color-hover-checked': 'var(--ti-common-color-prompt)',
  'ti-checkbox-border-color': 'var(--ti-common-color-line-normal)'
}
