export const tinySliderOldTheme = {
  'ti-slider-margin-left': 'calc(var(--ti-common-space-6, 6px) * -1)',
  'ti-slider-tips-text-color': 'var(--ti-common-color-text-white, #fff)',
  'ti-slider-input-text-align': 'center',
  'ti-slider-input-unit-margin-left': 'var(--ti-common-space-2x, 8px)',
  'ti-slider-input-margin-left': 'var(--ti-common-size-3x, 12px)',
  'ti-slider-input-width': 'var(--ti-common-size-10x, 40px)',
  'ti-slider-handle-disabled-border-color': 'var(--ti-common-color-text-disabled)',
  'ti-slider-handle-icon-disabled-fill-color': 'var(--ti-common-color-text-disabled)',
  'ti-slider-handle-margin-top': 'calc(var(--ti-common-space-10, 10px) * -1)',
  'ti-slider-handle-icon-fill-color': 'var(--ti-common-color-line-active, #5e7ce0)',
  'ti-slider-handle-icon-display': 'inline-block',
  'ti-slider-handle-border-weight-hover': 'var(--ti-common-border-weight-normal, 1px)',
  'ti-slider-handle-box-shadow': 'var(--ti-common-shadow-1-down, 0 1px 4px 0 rgba(0, 0, 0, 0.1))',
  'ti-slider-handle-border-color-hover': 'var(--ti-common-color-bg-hover, #344899)',
  'ti-slider-handle-border-radius': 'calc(var(--ti-common-border-radius-2, 8px) + 2px)',
  'ti-slider-handle-border-color': 'var(--ti-common-color-line-active, #5e7ce0)',
  'ti-slider-handle-bg-color':
    'linear-gradient(\n    153deg,\n    var(--ti-common-color-icon-white, #fff),\n    var(--ti-common-color-bg-light-normal, #e9edfa) 99%\n  )',
  'ti-slider-handle-height': 'var(--ti-common-size-7x, 28px)',
  'ti-slider-handle-width': 'var(--ti-common-size-5x, 20px)',
  'ti-slider-range-disabled-bg-color': 'var(--ti-common-color-text-disabled)',
  'ti-slider-range-margin-top': 'calc(-1 * var(--ti-common-space-base))',
  'ti-slider-range-hover-bg-color': 'var(--ti-common-color-icon-hover, #5e7ce0)',
  'ti-slider-range-bg-color': 'var(--ti-common-color-icon-hover, #5e7ce0)',
  'ti-slider-range-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-slider-range-height': 'var(--ti-common-size-4x, 16px)',
  'ti-slider-border-radius': 'var(--ti-common-border-radius-normal, 2px)',
  'ti-slider-height': 'var(--ti-common-size-2x, 8px)',
  'ti-slider-bg-color': 'var(--ti-common-color-bg-light-normal, #e9edfa)'
}
