export const tinyCalendarViewOldTheme = {
  'ti-calendar-view-not-selected-hover-color': 'rgba(0,103,209,0.05)',
  'ti-calendar-view-is-selected-hover-color': 'rgba(0,103,209,0.1)',
  'ti-calendar-view-events-grey-item-color': '#8D959E',
  'ti-calendar-view-events-cyan-item-color': '#00A2B5',
  'ti-calendar-view-events-purple-item-color': '#745EF7',
  'ti-calendar-view-events-yellow-item-color': '#F36900',
  'ti-calendar-view-events-red-item-color': '#EB171F',
  'ti-calendar-view-events-green-item-color': '#00A874',
  'ti-calendar-view-events-blue-item-color': '#1890ff',
  'ti-calendar-view-events-item-font-weight': 'var(--ti-common-font-weight-4)',
  'ti-calendar-view-events-item-font-size': 'var(--ti-common-font-size-0)',
  'ti-calendar-view-header-right-svg-fill': 'unset',
  'ti-calendar-view-header-left-svg-fill': 'unset',
  'ti-calendar-view-tooltip-content-text-color': '#8d959e',
  'ti-calendar-view-tooltip-date-text-color': '#8d959e',
  'ti-calendar-view-tooltip-title-font-weight': 'var(--ti-common-font-weight-5)',
  'ti-calendar-view-tooltip-title-font-size': 'var(--ti-common-font-size-base)',
  'ti-calendar-view-day-selected-svg-top': '-6px',
  'ti-calendar-view-day-selected-svg-right': '-1px',
  'ti-calendar-view-day-selected-border-radius': 'var(--ti-common-space-2x, 8px)',
  'ti-calendar-view-header-main-text-color': '#161e26',
  'ti-calendar-view-radio-button-inner': 'var(--ti-common-color-text-white)',
  'ti-calendar-view-radio-active-inner-hover': '#0a0b0e',
  'ti-calendar-view-radio-active-inner': 'var(--ti-base-color-brand-6)',
  'ti-calendar-view-radio-active-fill': 'var(--ti-common-color-text-white)',
  'ti-calendar-view-tool-display': 'flex',
  'ti-calendar-view-tool-first-display': 'none',
  'ti-calendar-view-header-margin-bottom': 'var(--ti-common-space-3x, 12px)'
}
