export const tinyModalSmbTheme = {
  'ti-modal-box-shadow': 'var(--ti-common-shadow-4-down)',
  'ti-modal-header-font-size': 'var(--ti-common-font-size-4)',
  'ti-modal-header-padding-bottom': 'var(--ti-common-space-4x)',
  'ti-modal-box-border-radius': 'var(--ti-common-border-radius-4)',
  'ti-modal-close-btn-font-size': 'var(--ti-common-font-size-5)',
  'ti-modal-close-btn-icon-color': 'var(--ti-common-color-icon-normal)',
  'ti-modal-close-btn-hover-icon-color': 'var(--ti-common-color-icon-hover)',
  'ti-modal-zoom-btn-right': 'calc(var(--ti-common-space-base) * 12)',
  'ti-modal-footer-padding-top': 'var(--ti-common-space-6x)',
  'ti-modal-footer-btn-min-width': 'calc(var(--ti-common-space-base) * 24)',
  'ti-modal-footer-btn-border-radius': 'calc(var(--ti-common-space-10) * 5)',
  'ti-modal-small-text-color': 'var(--ti-common-color-text-secondary)',
  'ti-modal-message-font-size': 'var(--ti-common-font-size-base)',
  'ti-modal-message-padding-left': 'var(--ti-common-space-4x)',
  'ti-modal-message-padding-right': 'var(--ti-common-space-3x)',
  'ti-modal-message-padding-vertical': 'calc(var(--ti-common-space-10) - 0.5px)',
  'ti-modal-message-body-padding-horizontal': 'var(--ti-common-space-0)',
  'ti-modal-message-icon-box-height': 'calc(var(--ti-common-space-5x) - 1px)',
  'ti-modal-notification-header-padding-bottom': 'var(--ti-common-space-6x)',
  'ti-modal-footer-align': 'right',
  'ti-modal-body-text-color': 'var(--ti-common-color-text-secondary)',
  'ti-modal-body-text-bottom': 'var(--ti-common-space-4x)'
}
